### PR TITLE
feature(i18n): Parse strings with MessageFormatter instead of sprintf

### LINKED ISSUE #1869: Support plural/singular in language strings (Trac #1869)
_Original ticket http://trac.elgg.org/ticket/1869 on 40087947-08-31 by brettp, assigned to unknown._

Elgg version: 1.7

(Copied from http://trac.elgg.org/elgg/ticket/850)

This is for things like:

A topic has 1 posts

or

A group has 1 members

### LINKED ISSUE #6908: support named parameters for elgg_echo
Backwards compatibility for language strings that take a bunch of parameters is a hassle. Customizing the language string to support a different order of arguments in the output text than in the elgg_echo call is possible with numbered params, but not very fun to keep track of. You have to use numbered parameters but it is not very readable at all.

Being able to use named arguments in new language strings would be awesome, since precise argument ordering wouldn't be as important (we actually learned a long time ago that this was a bad idea which is why we switched the DB querying functions to take a single options array instead of a list of 13 parameters).

### PR DESCRIPTION
**Pull request by ewinslow**
Get excited, people! This will give us much better support for spitting out correct translations so that Elgg won't have to feel so rough around the edges to our non-native-English-speaking friends.

Fixes #6908
Fixes #1869 

TODOs:
- [ ] Figure out a better middle-ground for the fact that the "intl" extension is not necessarily enabled by default
- [ ] Add http://formatjs.io/ to support message format on the JS side of things.
- [ ] Update call sites to provide names for parameters. This occurs a couple hundred times in core... might take a while to do manually...
- [x] Requires #8022 first so we don't break the 1.x branch...
- [x] Update all language strings in core
- [x] Add ext-intl to the list of documented requirements (not just composer.json).
- [x] Add a link to some good docs on ICU's MessageFormatter syntax (and not language-specific APIs).
- [x] Verify that named parameters actually work. I cannot find this feature documented consistently, and the PHP docs on this class are pretty bare bones...
- [x] Point to http://formatjs.io/guide/#messageformat-syntax for details on acceptable message format syntax.

### CODE REVIEW

**Comment by ewinslow** [comment]
Couple issues:

ext-intl is apparently not commonly enabled by default (although it is bundled by default). This is quite unfortunate. I remain convinced that this is the way forward, but I do not want to make it hard to install Elgg over this issue. We need a middle ground.

All the strings in core still need to be adjusted, but I don't want to do that if we're going to extract plugins from core to their own repos, so this is blocked on that.

**Comment by ewinslow** [comment]
There is frustratingly not a good document that documents the valid syntax for MessageFormat messages.

This was the best I could find, but it feels like its written for computers, not people:

http://icu-project.org/apiref/icu4c/classMessageFormat.html#patterns

**Comment by mrclay** [comment]
Yeah I couldn't find a guide for the format either. Intl being commonly disabled seems like a big hurdle.

**Comment by ewinslow** [comment]
Strike that above statement. Glad to have found this page with the JS lib that @mrclay referenced.

http://formatjs.io/guide/#messageformat-syntax

**Comment by ewinslow** [comment]
My current ideas for support in spite of the Intl thing:
 - implement (or integrate) a "polyfill" layer that is unsophisticated (doesn't require too much maintenance) but just barely good enough to not feel completely broken.
 - clear instructions on how to get Intl enabled on various systems
 - downgrade Intl from requirement to recommendation

**Comment by ewinslow** [comment]
So, one way we could do this in 1.x is by putting all message-format style messages in a new directory (e.g. "translations" instead of "languages"). Any messages found in a plugin's "translations" directory would be parsed as message format.

**Comment by juho-jaakkola** [comment]
Adding the ```translations/ ``` dir to 1.x seems like a good idea.

> Update call sites to provide names for parameters.

What does this mean?

**Comment by ewinslow** [comment]
```
elgg_echo('key', ['value']);
```

becomes

```
elgg_echo('key', ['name' => 'value']);
```

**Comment by juho-jaakkola** [comment]
I was just not familiar with the term "call site". Google helped.

**Comment by ewinslow** [comment]
@brettp this introduces a parallel way of doing things with a view towards doing the old way in 2.0. It provides a smooth upgrade path from 1.x, such that someone can write a plugin that is compatible across 1.x and 2.0.

However, it is yet another instance where there is more than one way to do something. How do you feel about this?

**Comment by ewinslow** [comment]
Clarification: introducing a new "translations" directory is what would cause this to happen, not this PR.

We could migrate core and plugins to use the indexed format `{0}` to be fully compatible with existing sprintf strings.

**Comment by ewinslow** [comment]
Main blocker here is that php-intl is not typically installed/enabled by default... we'd need some kind of thin, trivial compat layer in order for this to work...

**Comment by juho-jaakkola** [comment]
Let's add the compatibility layer later and for now just add this to installing/upgrading:
```php
if (!extension_loaded('intl')) {
    echo "You need the php-intl extension to run Elgg. Contact your server host for help.\n";
    exit;
}
```

**Comment by mrclay** [comment]
Without a working polyfill in place (that we've tested extensively), I don't think we should merge anything.

**Comment by ewinslow** [comment]
Agreed. I don't think we can merge this as-is. I want this badly because I truly think it's the best standard out there, but I don't want to alienate people over it.

**Comment by mrclay** [comment]
This needs a significant rebase and a couple motivated devs to evangelize it and push it across the finish line. Closing for now.

**Pull request closed without merging**
