### PR TITLE
feature(i18n): abbreviations for months and weekdays

### PR DESCRIPTION
**Pull request by jeabakker**
In order to make date formating more i18n the abbreviations of the
months and weekdays should be available

### CODE REVIEW

**Comment by mrclay** [comment]
"feature" instead of "add" in commit msg.

**Comment by mrclay** [comment]
Otherwise LGTM

**Comment by jeabakker** [comment]
> "feature" instead of "add" in commit msg.

Duh! I knew I did this wrong. But i couldn't find what is should have been, and i didn't look :)

**Comment by juho-jaakkola** [comment]
I think I'd prefer
```
date:month:1:short
date:month:2:short
```
instead of
```
date:month:short:1
date:month:short:2
```

Not a very strong opinion, though. Current way is fine if others like that more.

**Comment by jeabakker** [comment]
I though it would be easier to concat with date('m') is the number was at the end (like the other date strings)

**Comment by mrclay** [comment]
I know 2.0 is frozen but this seems acceptable to me.

**Pull request merged**
