### PR TITLE
WIP feat(php): require PHP7+

### PR DESCRIPTION
**Pull request by hypeJunction**
BREAKING CHANGE
Elgg now requires PHP 7.0+

### CODE REVIEW

**Comment by mrclay** [comment]
I don't have a horse in this race, but it feels too early. Would any new PHP 7 features/packages make Elgg 3.0 easier to finish?

**Comment by beck24** [comment]
I like the push forward but I'm with @mrclay - wondering if there's a clear gain from dropping 5.6.
Many environments still aren't using PHP 7, especially shared environments.  I'm not opposed to this, but just want it to not be arbitrary.

**Comment by hypeJunction** [comment]
PHP 5.6 is TLS and will be out in Dec 2018, so there will be a little over a year of security releases left by the time we release 3.0

**Comment by jdalsem** [comment]
Bigger companies tend to keep LTS versions around for a long time. Personally i feel this is too soon. We would have issues with this with some of our clients.

Elgg 4.0 is scheduled for 2018, so why not drop it as part of that release?

**Pull request closed without merging**
