### PR TITLE
chore(docs): update current year in copyright notices

### PR DESCRIPTION
**Pull request by nirajkaushal**
chore(docs): update current year in copyright notices

### CODE REVIEW

**Comment by hypeJunction** [comment]
We have a strict commit message policy. It should read something like `chore(docs): update current year in copyright notices`

**Comment by hypeJunction** [comment]
Here is more: http://learn.elgg.org/en/2.0/contribute/code.html#commit-message-format
Thanks for the commit by the way.

**Comment by juho-jaakkola** [comment]
You changed the title of the pull request. Instead you need to change the git commit message.

**Comment by juho-jaakkola** [comment]
Also the `2.0` branch might be better place for the change instead of the `2.x` branch .

**Comment by nirajkaushal** [comment]
sorry, now i am going to close this PR and i will request new PR with correct format

**Pull request closed without merging**
