### PR TITLE
feature(core): added a new admin widget to monitor cron jobs

### PR DESCRIPTION
**Pull request by jdalsem**

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
I don't see why admin would need to see this every time they go to the admin panel.

**Comment by jdalsem** [comment]
i do, some cron jobs are important. This would be an easy way to get that information (instead of going to the statistics/cron page).

**Comment by juho-jaakkola** [comment]
Is there a reason to assume the jobs haven't been ran?

**Comment by jdalsem** [comment]
All kinds of reasons; server config changed, bug in code

**Comment by Srokap** [comment]
I see the value in it. It's something you might want to just see on dashboard to make sure everything runs smoothly and not necessarily go to cron page to do just that. I'd rename it however to something like `cron_status` or `cron_stats` with slight preference of the first one.

**Comment by mrclay** [comment]
Maybe an option to only show the cron jobs obviously not running? A way to register a *hard* dependency on cron jobs might be useful. Admins could get a more intrusive message if they haven't run.

**Comment by ewinslow** [comment]
Yea, a way to highlight when things are clearly broken is critical IMO

**Comment by jdalsem** [comment]
> highlight when things are clearly broken is critical IMO

i think that is for another ticket + we can not assume that things are going wrong. Maybe someone has deliberately only setup 5 min, 1 hour and daily cron (to save requests).



> It's something you might want to just see on dashboard to make sure everything runs smoothly and not necessarily go to cron page to do just that

This is exactly what it is for.

**Comment by ewinslow** [comment]
Dashboard is becoming the place you go to see all the things that need attention. Rightly so. That in general is a good idea. But with this you are presented information and you still have to decide if that merits attention.

I think for that reason it belongs on a separate page for now. It's valuable information because there is nowhere to find it right now.

And I agree with Steve that plugins should be able to register a hard dependency on cron jobs which then warns the admin when they haven't been triggered. Then this info can show up on the dashboard with a link to docs about how to fix it.

**Comment by iionly** [comment]
A dashboard widget is just an option. If an admin does not need the cronjob info to be visible all the time on the dashboard it's easy to remove.

Beside the stats about when the cronjobs have been run I think the info about which callback functions are registered to which intervals is something that is really missing (provided by plugin only: https://community.elgg.org/plugins/1864611).

**Comment by ewinslow** [comment]
Sounds like something that belongs in the developer tools inspector? I agree that this is valuable information and should be surfaced somewhere, but I don't want to keep just adding things in an ad hoc way. That's all

**Comment by iionly** [comment]
@ewinslow I don't think it belongs to the developer tools. The info is useful not only for devs (who can get the same info by other means) but maybe even more so for non-dev site admins who simply want to correctly set up the cronjobs or get an overview on what cron callbacks are registered by plugins. It's perfectly alright for me if it doesn't get added to core - I can live with the info get provided by a plugin (though I've only managed to get it working on Elgg 1.9+ by using private api functions...).

**Comment by jdalsem** [comment]
Some people need it, some don't. That why we have widgets. People can add them to their own liking. This PR just adds a table with useful info (that is available somewhere else) to a widget. Why would we block such a feature?

**Comment by Srokap** [comment]
It's trivial enough to not block it and generally I would prefer to providing as many admin widgets as it really makes sense and does not add complex logic or duplication, so the admin can use whatever they like on their dashboard. We don't add it by default, so initial dashboard remains clean. In case like this, when we talk of inclusion of view as a widget (with some parameter that limits output or simplifies it), I'm totally for it.

Developer tools in general should contain stuff that supports development or testing.

Monitoring stuff, log analysis, content statistics are all domain of administration and we currently tend to include them in the core.

If we added plugins as composer deps, developers plugin should always fit require-dev section. Something that live deployment wouldn't even download.

**Comment by mrclay** [comment]
LGTM

**Comment by ewinslow** [comment]
SGTM

**Comment by Srokap** [comment]
@jdalsem Could you rename the widget? I would call it "Cron status" and use `cron_status` as the key.

**Pull request merged**
