### PR TITLE
feat(upgrade): upgrade service now uses promises

### LINKED ISSUE #11825: logged out going to upgrade.php in walledgarden should forward

### LINKED ISSUE #11888: Get rid of UPGRADING monstrosity
https://github.com/Elgg/Elgg/pull/11883/files#diff-906fae229b5696c49d5e4913d4e662e9R545

### PR DESCRIPTION
**Pull request by hypeJunction**
upgrade.php no longer holds any upgrade logic, instead it routes
the request to a proper controller

Upgrade service now uses promises, consequently cli command correctly
exits with an error code, when one of the upgrades fails.

Fixes #11888
Fixes #11825

### CODE REVIEW

**Comment by hypeJunction** [comment]
Tested the upgrade manually, everything is fine now.
Maybe someone else can do another run.

**Comment by hypeJunction** [comment]
I am done here

**Comment by hypeJunction** [comment]
Also fixes #12004, #11967, #11937, #11825

**Comment by jeabakker** [comment]
Tested the following
- Fresh install using the website => OK
- Fresh install using the website (with `settings.php` present) => OK
- Fresh install using `elgg-cli` => OK
- Upgrade Elgg 2.3 to 3.0 using `elgg-cli` => OK

Everything looks fine to me (can confirm #12004 is fixed ;)

**Review by jeabakker — APPROVED** [review]

**Pull request merged**
