### PR TITLE
fix(routes): use absolute url as base for route url generation

### LINKED ISSUE #12782: Elgg 3.1 - Activity Route Issue
I have just installed a fresh copy of elgg 3.1 in my local system using composer.
I found that "Activity" plugin route is not working properly.

I have installed elgg under `http://localhost/www/ck_31` so ideally the activity page menu link should be `http://localhost/www/ck_31/activity` but the "`www/ck_31`" is getting repeated twice and the menu is actually calling "`http://localhost/www/ck_31/www/ck_31/activity`"

image

Steps for fresh copy of elgg setup:
- composer create-project elgg/starter-project:dev-master ./path/to/my/project
- cd ./path/to/my/project
- composer install

Did i miss out something?

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #12782

### CODE REVIEW

**Comment by hypeJunction** [comment]
Leave the services as they were before and normalize from elgg_generate_url(). Why all this extra unnecessary logic?

**Comment by jdalsem** [comment]
> Leave the services as they were before and normalize from elgg_generate_url()

problems need to be fixed where they occur.. this is the lowest possible place where the problems start and where Elgg is able to fix it. Fixing it only in `elgg_generate_url` allows other functions that call `generateUrl` to run into the same problems.

> Why all this extra unnecessary logic?

Not unnecessary... it fixes issues

**Comment by hypeJunction** [comment]
Then you need to elaborate more on what issues you are trying to fix. I don't see from the code what this is trying to address

**Review by jeabakker — APPROVED** [review]

**Comment by jdalsem** [comment]
Mentioned inline:
- make sure the url is always normalized so it is also usable in CLI
- validate if detected url scheme matches scheme set in config

which one don't you understand?

**Comment by hypeJunction** [comment]
1. Any specific use cases for absolutely URLs in CLI vs non-CLI? The problem with CLI is that the request comes in without the base URL, so wwwroot must be set in config. Perhaps a way around is to block CLI commands until wwwroot is set.

2. Why is that logic not inside elgg_normalize_url()?

**Comment by jdalsem** [comment]
> 1. Any specific use cases for absolutely URLs in CLI vs non-CLI? The problem with CLI is that the request comes in without the base URL, so wwwroot must be set in config. Perhaps a way around is to block CLI commands until wwwroot is set.

Cron in CLI will send mails with generated URLS... generate URL is not using wwwroot for URL generation, so this needs to be tackled



> 2\. Why is that logic not inside elgg_normalize_url()

need to think about that...

**Comment by hypeJunction** [comment]
> Cron in CLI will send mails with generated URLS... generate URL is not using wwwroot for URL generation, so this needs to be tackled

How is that different from non-CLI environment? If it's not normalized in CLI, then it's not normalized in the browser, so the problem is with the notification handler, not URL handler.

**Comment by jdalsem** [comment]
> How is that different from non-CLI environment

Symfony relies on requestContext that gets its information from $_SERVER... that data is empty in CLI... normalization is not needed in non-CLI as autodetection is correct. Notification handler has nothing to do with it...

**Comment by jdalsem** [comment]
the inconsistency is happening during URL generation... output of the url generation should be consistent. We need to be able to rely on the output

**Comment by hypeJunction** [comment]
> Symfony relies on requestContext that gets its information from $_SERVER... that data is empty in CLI... normalization is not needed in non-CLI as autodetection is correct. Notification handler has nothing to do with it...

Correct, so the problem is lacking `wwwroot` in settings file. It is also more reliable to have `wwwroot` set even for HTTP requests, in cases where Elgg lives in a subdirectory. The simpler way would be to throw an exception from CLI saying the use of CLI requires that wwwroot is set in config. End of story.

**Comment by hypeJunction** [comment]
https://github.com/Elgg/Elgg/issues/12180

**Comment by jdalsem** [comment]
like i said... not the reason... even with a url set this is a problem

**Comment by hypeJunction** [comment]
> even with a url set this is a problem

What is the problem?

**Comment by jdalsem** [comment]
> What is the problem?

no normalized url

**Comment by hypeJunction** [comment]
I don't think it's a problem per se, but more of a usability issue. It's ok to normalize it, but do it properly at least, inject the resposible service and use the instance method.

**Comment by jdalsem** [comment]
> inject the resposible service and use the instance method

normalize_url does not have a service at the moment

**Comment by hypeJunction** [comment]
Perhaps it should be part of the router if you feel there is a compelling need to normalize things.

**Comment by jdalsem** [comment]
updated the pr: moved the http/https logic to normalize_url

**Pull request merged**
