### PR TITLE
feature(routing): Use views system to render pages

### PR DESCRIPTION
**Pull request by ewinslow**

### CODE REVIEW

**Comment by ewinslow** [comment]
I skipped blog because that one uses more logic to render the views instead of just having a pages/* script for each one.

**Comment by hypeJunction** [comment]
One though I had is we should introduce an event/hook trigger after setting the page owner in 1.x. This way plugin devs can start moving page owner related logic out of pagesetup event.

**Comment by ewinslow** [comment]
@hypeJunction seems unrelated to this PR. Can you help me connect the dots?

**Comment by hypeJunction** [comment]
Pagesetup is triggered whenever elgg_view is called for the first time.
Prior to this PR, plugins would have set a page owner then use include with
elgg_view. I imagine there are plugins that expect page owner to be set
when  pagsetup is triggered.

**Comment by mrclay** [comment]
pagesetup -> #8374

**Comment by hypeJunction** [comment]
LGTM, but we should pull the trigger on this sooner than later. This will be a bundle of merge conflicts :)

**Comment by mrclay** [comment]
This might help testing this http://www.mrclay.org/2015/05/27/pass-all-the-breakpoints/

**Comment by juho-jaakkola** [comment]
LGTM, but it would definitely be safer to test some more

**Comment by ewinslow** [comment]
I've still got quite a bit of converting to do :). Testing will be a good idea, yes :)

**Comment by ewinslow** [comment]
OKAY! This is ready for testing!

Though I'm sort of tempted to pull this in and leave testing for later because conflicts will inevitably build up if this gets delayed too long... :(

**Comment by mrclay** [comment]
Gave it a quick runaround. There will be bugs, no big deal.

**Comment by ewinslow** [comment]
Thank you Steve! This results in a huge improvement in developer experience, I think. Customizing pages used to be kinda convoluted. I'm pretty excited that customizing the index page is now as easy as "put a php file at views/default/resources/index.php".

**Pull request merged**
