### PR TITLE
Merge 2.2 2.x

### PR DESCRIPTION
**Pull request by hypeJunction**

### CODE REVIEW

**Comment by hypeJunction** [comment]
Argh, Travis is going mad with commit message tests again...

**Comment by mrclay** [comment]
Use git reset to make sure your local branches match origin exactly. Has always worked for me.

**Comment by hypeJunction** [comment]
Origin or upstream? I reset to upstream. In any case that inconvenient. I can't cherry pick merge commits, so need to fix merge conflicts all over again.

**Comment by hypeJunction** [comment]
I give up. I tried all I could think of, but travis still goes crazy with commit messages.

**Comment by mrclay** [comment]
I can take a shot at this in a few hours.

**Comment by mrclay** [comment]
...I can't tell yet if that happening is a real omen of something we want to avoid.

**Pull request closed without merging**
