### PR TITLE
chore(forms): apply checkbox exceptions earlier when rendering fields

### PR DESCRIPTION
**Pull request by hypeJunction**
Normalize checkbox options earler to correctly build the checkbox field markup

### CODE REVIEW

**Comment by jdalsem** [comment]
LGTM, but shouldn't this be a fix?

**Comment by hypeJunction** [comment]
It's not in the release yet.

**Comment by jdalsem** [comment]
> It's not in the release yet.

elgg_view_field is... and this fixes something wrong in that function AFAICS

**Comment by jdalsem** [comment]
oh no.. it is not... sorty

**Pull request merged**
