### PR TITLE
Release 1.11.3

### PR DESCRIPTION
**Pull request by beck24**

### CODE REVIEW

**Comment by iionly** [comment]
There are language files (zh-Hans.php) pulled that have non-valid filenames / language codes.

**Comment by beck24** [comment]
@Srokap - do you know why we're getting non valid languages?

**Comment by iionly** [comment]
@beck24 most likely because there's still no check of the language codes of the files pulled from Transifex (suggested in https://github.com/Elgg/Elgg/issues/7154). The codes are invalid only in the sense of not included in the list of allowed codes of Elgg (see getAllLanguageCodes() in engine/classes/Elgg/I18n/Translator.php) while they are valid from Transifex's point of view.

It's not the first time that this happened (https://github.com/Elgg/Elgg/issues/8316) and I'm afraid if it's not stopped better sooner than later there might get even more of the "invalid" language files added.

**Comment by iionly** [comment]
@beck24 Is the issue with language files the reason there has been no 1.11.3 released so far? If that's the reason, I think it's necessary to discuss what to do as the same problem is likely to occur not only for 1.X but also when releasing any 2.X.

I don't know if it's possible to allow / disallow certain languages within a Transifex project. Maybe it's possible to prevent invalid languages from being added by not allowing these languages in the first place at Transifex if anyone is requesting them to be added. And for any invalid languages already added it might be necessary to deal with the problem also on Transifex by changing them to a valid language or by removing them if that's not possible.

**Comment by beck24** [comment]
Yeah, sorry I wanted to check with the rest of the team regarding what we should do.  The consensus was that the additional files wouldn't affect anything in the immediate term, so I can release this.  I just ran out of time before I heard back from people.
We have a plan for how to prevent it in the future we just need to add it to the release build scripts.

**Pull request merged**
