### PR TITLE
feature(filestore): adds API to reliably set file modification time

### PR DESCRIPTION
**Pull request by hypeJunction**
Updates PHPUnit bootstrap to allow working with file entity objects. Modifies and adds new file related tests.

Adds two new methods ElggFile::setModifiedTime and ElggFile::getModifiedTime,
which invalidate stat cache to ensure we always have latest modified time information

Refs #9571
- [x] Needs rebase after #9580 (tests will fail now)

### CODE REVIEW

**Comment by hypeJunction** [comment]
Rebased. Second commit is mostly needed if we will start allowing last updated timestamp to be empty in requests.

**Comment by mrclay** [comment]
LGTM

**Comment by hypeJunction** [comment]
I could use this in my other PR, could we get another set of eyes and merge?

**Comment by hypeJunction** [comment]
I am merging.

**Pull request merged**
