### PR TITLE
fix(relationships): Restores functionality of `$inverse_relationship` argument for `get_entity_relationships`

### PR DESCRIPTION
**Pull request by jboulen**
Hello,

When we have tried to upgrade from elgg 1.9 to elgg 1.10, we found a bug on get_entity_relationships() function.

There is a small typo error on $inverse_relationship variable.

Regards,

### CODE REVIEW

**Comment by hypeJunction** [comment]
Thanks for catching.
Yikes. This really needs to be covered by tests.

**Comment by hypeJunction** [comment]
I think this should go into 1.11 branch, as it's a bug fix.

**Comment by ewinslow** [comment]
@jboulen Thanks for the fix!

I notice you changed your PR title to match the commit message format. You actually need to change the git commit message format instead. This is a very common point of confusion. I wonder what we can do to make that clearer...

Also, can we change the commit message to describe the fix rather than the bug? That'd be awesome.

Something like:
```
fix(relationships): Restores functionality of `$inverse_relationship` argument for `get_entity_relationships`
```

**Comment by jboulen** [comment]
Sure, you can change the commit message. No problem.

**Comment by ewinslow** [comment]
Can you do it?

**Comment by jboulen** [comment]
Sorry, I tought that use `push --force` would have broken something... but it seems that github doesn't deal with the commit hash.

**Comment by ewinslow** [comment]
@jboulen Last thing is to re-submit against our 1.11 branch so that we can get this fix out with 1.11.3 instead of making folks wait for 2.0.

Thanks again for catching that and submitting the fix!

**Comment by jboulen** [comment]
It seems I can't change base branch now. I'm going to create new PR.

**Pull request closed without merging**
