### PR TITLE
feature(assets): Auto-link /cache/ dir to simplecache on composer install/update

### PR DESCRIPTION
**Pull request by ewinslow**
- [ ] Should skip linking if dataroot isn't set
- [ ] should delete existing Symlink in case the site was recently moved

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
LGTM

**Comment by ewinslow** [comment]
This won't work on a fresh install. Dataroot is not set yet.

Hmmm...

**Comment by ewinslow** [comment]
This strictly a performance enhancement and convenience issue. I no longer think it should block 2.0

**Comment by hypeJunction** [comment]
Do we still want this after https://github.com/Elgg/Elgg/pull/9678?

**Comment by mrclay** [comment]
@hypeJunction agreed. Closing.

**Pull request closed without merging**
