### PR TITLE
fix(views): show spinner when ajax loading walled garden forms

### LINKED ISSUE #5612: Add loading indicator when loading content via AJAX for walled garden
On walled garden page we load registration and password recovery forms via AJAX, after clicking on the link. There is some delay between click and content display and may be confusing users.

Idea is to display some popup-like loader (ajax loader should e fine) that would indicate operation in progress and be hidden when response content would be availible.

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #5612

### CODE REVIEW

**Comment by mrclay** [comment]
Looks right. It's still an issue that we have to make a request to load elgg/spinner here. Starting to think elgg/spinner needs to be rolled into js/elgg for immediate use.

**Comment by mrclay** [comment]
...separate issue of course. This LGTM

**Comment by jdalsem** [comment]
well i think maybe we should add the spinner to js/elgg as there still we be a delay with this current setup (if there is no cached version available). #5612 is about giving an indication to end user about background stuff being done, but with the current spinner, we may need a spinner to show before the spinner is loaded...

**Comment by jdalsem** [comment]
@mrclay do you still think we should add the spinner to js/elgg? If so are you willing to PR that? I can rebase and use it in this issue then...

**Comment by jdalsem** [comment]
@mrclay shall i pull this in or wait for you to add the spinner to the global js?

**Comment by mrclay** [comment]
Adding more to js/elgg isn't acceptable right now. Simplest solution I see is too entre spinner require to the init method and have it set `elgg.walled_garden._spinner`. In load, use that car only if it's defined at that point. That way if the user invokes load earlier than the spinner module loads, it still loads, just without the spinner.

Ideal would be converting this library to AMD but that would have to wait.

**Comment by mrclay** [comment]
Or can we just use elgg_require_js (in PHP) when drawing this page? That would make the current PR ok I think.

**Comment by jdalsem** [comment]
> Or can we just use elgg_require_js (in PHP) when drawing this page? That would make the current PR ok I think.

Added the lib requirement to the elgg.walled_garden.init js function, with the same intended effect.

**Pull request merged**
