### PR TITLE
fix(core): elgg_get_plugin_setting() respects defaults for values that haven't been cached or created.

### LINKED ISSUE #9781: elgg_get_plugin_settings() doesn't respect default value if any settings are cached
```php
	public function getSetting($name, $default = null) {
		$values = _elgg_services()->pluginSettingsCache->getAll($this->guid);

		if ($values !== null) {
			return isset($values[$name]) ? $values[$name] : null;
		}
```

If any settings have been saved or are cached, the if block ignores the default values, even if the cached settings don't include the setting we're requesting.

### PR DESCRIPTION
**Pull request by mrclay**
Fixes #9781

(I just rebased this for 2.1)

### CODE REVIEW

**Comment by jdalsem** [comment]
LGTM

**Comment by hypeJunction** [comment]
I still would encourage a test. This regression shouldn't have happened.

**Comment by brettp** [comment]
Thanks, @mrclay!

**Comment by mrclay** [comment]
Added test.

**Pull request merged**
