### PR TITLE
fix(likes): count is updated after liking/unliking

### LINKED ISSUE #9100: Likes count doesn't update on like/unlike
Pretty sad we haven't fixed this yet. Can we do it in a BC way?

### PR DESCRIPTION
**Pull request by mrclay**
Also removes focus from the icon so it's state is more apparent.

Also adds ability to attach ajax success functions to toggle menu items.

Fixes #9100
- [ ] needs a feature commit for extending `elgg.ui.registerTogglableMenuItems`
- [ ] or maybe better, reimplement so we can ship in 2.0.1

### CODE REVIEW

**Comment by hypeJunction** [comment]
I really dislike `elgg.ui.registerTogglableMenuItems`, and the fact that we toggle markup visiblity, instead of updating item state. I have already had problems with this in themes that set `display: inline-block` on menu items, and `.hidden` class being overrided by more precise selectors. 
I would prefer we build some stateful button object instead, and use `data-` to define before and after states.

**Comment by mrclay** [comment]
Agreed, but I don't see how we can do that in a BC way until 3.0.

**Comment by hypeJunction** [comment]
What happened to the a-la websockets feature you were working on? I think that could be one way of looking at it: force update the count from the global scope, rather than from item scope.

**Comment by mrclay** [comment]
Replaced by #9148

**Pull request closed without merging**
