### PR TITLE
docs(ajax): Adds more complete Ajax docs

### LINKED ISSUE #8277: Fully document the current Ajax API
E.g. In ajax views I vaguely remember input is mapped into $vars, "guid" is auto-injected as the loaded "entity", and action responses have kind of special JSON auto-wrapping stuff with system_message(). AFAIK very little of this magical stuff is clearly documented.

At minimum it should be straightforward for a dev to create ajax views/actions that return JSON, and know what that JSON is going to look like.

### PR DESCRIPTION
**Pull request by mrclay**
Fixes #8277

### CODE REVIEW

**Comment by mrclay** [comment]
@ewinslow @hypeJunction would love input here. Anything I'm missing...

**Comment by ewinslow** [comment]
Looks really good. I say ship it and we can continue to improve I'd anything else is missing.

**Comment by hypeJunction** [comment]
@mrclay, I am late for the show, but looks good. I can't of anything else to add

**Comment by hypeJunction** [comment]
Can't think* :) bloody autocorrect

**Pull request merged**
