### PR TITLE
New web services features

### PR DESCRIPTION
**Pull request by hypeJunction**
Submitting an abridged version of earlier PR against 1.x branch.
- allows passing $assoc parameter to force assoc array as the only callback argument
- gets rid of the eval() and parameter serialization
- updates tests

### CODE REVIEW

**Comment by hypeJunction** [comment]
If no one is interested in improving web services, I will stop wasting time on trying to devise BC solutions, and roll out a new clean plugin. I need working webservices for 3 projects and this is holding me back.

**Comment by hypeJunction** [comment]
I have moved on to my custom implementation. WS is a mess and I don't want to be held back with my projects.

**Comment by mrclay** [comment]
Sorry it's not a focus right now. Do you mind if we reopen this to be picked up later?

**Comment by hypeJunction** [comment]
Sure, we can try, but I doubt I will have interest in revisiting and redoing it all over again once I ship out my plugin. I am building out a full package, with granular method access on per-consumer basis, key/token management ui, auth config, a ton of methods etc.

**Comment by mrclay** [comment]
Replaced by #9406

**Pull request closed without merging**
