### PR TITLE
feature(views): allow multiple paths in views.php files

### PR DESCRIPTION
**Pull request by mrclay**

### CODE REVIEW

**Comment by hypeJunction** [comment]
LGTM

**Comment by hypeJunction** [comment]
This has a strange side effect. i can't seem to be able to override the colorbox theme. Tried creating `lightbox/elgg-colorbox-theme/colorbox.css` view, tried setting it to a different location with views.php at no avail.

**Comment by hypeJunction** [comment]
Basically we added a new `colorbox.css` view. So, if someone was overriding `lightbox/elgg-colorbox-theme/colorbox.css`, we are no longer using the replacement view...

**Comment by mrclay** [comment]
Is the problem really that we changed the view name for colorbox CSS?

**Comment by mrclay** [comment]
@hypeJunction see #9690

**Pull request merged**
