### PR TITLE
feat(cron): adds cron service

### PR DESCRIPTION
**Pull request by hypeJunction**
Adds cron service.
Adds cron elgg-cli command.
Deprecates cron page handler.

### CODE REVIEW

**Comment by mrclay** [comment]
Do we need to mention that cron tasks now run (and all plugins boot) in the CLI environment? I've been bit a ton by differences in PHP configs.

**Comment by hypeJunction** [comment]
> Do we need to mention that cron tasks now run (and all plugins boot) in the CLI environment? I've been bit a ton by differences in PHP configs.

I don't follow

**Comment by jdalsem** [comment]
Shared hosts might still need the wget cron... Do we really want to deprecate that?

**Comment by hypeJunction** [comment]
I dont't want to compromise security and add overhead because of shared hosts.

**Comment by jdalsem** [comment]
> I dont't want to compromise security

what security issue?



> because of shared hosts

i think they are Elgg users.... why not let them decide? just give them both options

**Comment by hypeJunction** [comment]
We don't have to remove it. A notice will nudge them towards command line

**Comment by mrclay** [comment]
>  differences in PHP configs.

CLI PHP can be completely different--config, extensions, version--than the web server. I suppose we can rely on composer to check our requirements be met.

**Comment by hypeJunction** [comment]
> CLI PHP can be completely different--config, extensions, version--than the web server. I suppose we can rely on composer to check our requirements be met.

You will need an installed application that meets all requirements. I don't see any difference between running cron from CLI or web.

**Comment by jdalsem** [comment]
what did you fix/change in your latest commit/push?

**Comment by hypeJunction** [comment]
> what did you fix/change in your latest commit/push?

Removed the deprecation. Can't remember what else.

**Pull request merged**
