### PR TITLE
chore(settings): clearer notion of where the site description is used

### PR DESCRIPTION
**Pull request by mrclay**

### CODE REVIEW

**Comment by jdalsem** [comment]
but what if i use it as a footer in the email... or as a subtext in the header.... just leave as is...

**Comment by mrclay** [comment]
Then I'll add separate metadata for this. It appears in search results, pretty important.

**Comment by jeabakker** [comment]
maybe add a help text to explain possible uses? that's easier

**Comment by hypeJunction** [comment]
> Then I'll add separate metadata for this. It appears in search results, pretty important.

We need better controls over this.
Maybe a plugin could call `elgg_set_page_metadata([])`, which will tap into `head` hooks and set it for the page. Currently, it's really hard to do that for individual pages.

**Comment by mrclay** [comment]
Description is not used anywhere in core AFAIK. Why even ask for it and what to label it?

**Comment by hypeJunction** [comment]
> Description is not used anywhere in core AFAIK

What I've done in custom projects, is replace that form to modify the site entity: add icon, description, meta tags etc.

**Comment by jdalsem** [comment]
> maybe add a help text to explain possible uses? that's easier

think this solves your reason for this PR... easier metadata management could be another ticket

**Comment by jdalsem** [comment]
> What I've done in custom projects, is replace that form to modify the site entity: add icon, description, meta tags etc.

did something similar for metadata in a very old plugin https://github.com/ColdTrick/metatag_manager...

**Comment by mrclay** [comment]
Now this just adds help text "With bundled plugins this appears only in the description meta tag for search engine results."

**Review by jeabakker — APPROVED** [review]

**Pull request merged**
