### PR TITLE
fix(rss): blog and groups rss missing views

### PR DESCRIPTION
**Pull request by rohit1290**
Fix for https://github.com/Elgg/Elgg/issues/12339

The RSS was not showing because the view does not exist in rss folder. This will fix the blog and group rss views.

### CODE REVIEW

**Comment by jdalsem** [comment]
There should be no need for rss views for the resources... this should happen because of some viewtype fallback logic. The solution for #12339 is probably something completely different

**Comment by rohit1290** [comment]
What I found was for both blog and group, the resource pages are calling elgg_view for files under listing folder. This is causing the problem. Example: resources/blog/all.php is calling elgg_view for blog/listing/all (Same for other file as well).

If I copy the code logic of blog/listing/all to resources/blog/all then the rss is working absolutely fine.

What i was thinking is that we can create a lib function for blog and group respectively with the code logic defined at listing/all file and call that function instead elgg_view. Can that be an accepted solution? 

Or can you point me to exact function where view fallback logic is defined. I can do some more testing and see if i can come up with a better solution.

**Comment by jeabakker** [comment]
Apparently RSS doesn't fallback and therefor a solution must be found. Will look into this further

**Comment by jeabakker** [comment]
This PR was going in the right direction, only it didn't fix all plugins.

In #12494 this is done

**Pull request closed without merging**
