### PR TITLE
feature(files): update file plugin to new file serving API

### PR DESCRIPTION
**Pull request by hypeJunction**
Backports #9365 to 2.x
Refs #9517

### CODE REVIEW

**Comment by hypeJunction** [comment]
Not sure how to handle this best. I cherry-picked the other PR's commit, but it has breaking change in it, but if I reword the commit, it will have a different SHA. I guess no matter what we do, we will end up with conflicts to resolve, so I might as well squash.

**Comment by mrclay** [comment]
Yeah, squash and see if you can get the docs builder to stop complaining.

**Comment by mrclay** [comment]
I doubt you have to worry about the merge into master.

**Comment by hypeJunction** [comment]
It's just a tilde, I will fix that.

**Comment by hypeJunction** [comment]
Travis is green.

**Comment by mrclay** [comment]
Let's do this!

**Comment by hypeJunction** [comment]
You know what, I just woke up and the first thing in my head is what's going to happen to an embed plugin... we bind thumb URLs to tge session so we can't really use those for embedding.

**Pull request merged**
