### PR TITLE
Empty menu href

### PR DESCRIPTION
**Pull request by jdalsem**
- feature(output): passing href false sets href to javascript:void(0)
- fixed(menus): menu items will always output an anchor

### CODE REVIEW

**Comment by hypeJunction** [comment]
I don't think that is right. Perhaps you should just allow anchors without href

**Comment by jdalsem** [comment]
> Perhaps you should just allow anchors without href

that is already possible by passing `null`

**Comment by jdalsem** [comment]
> Perhaps you should just allow anchors without href
> 
> that is already possible by passing null

not in menu's though

**Comment by mrclay** [comment]
SGTM

**Pull request merged**
