### PR TITLE
feature(html): moves favicon registration to a hook

### PR DESCRIPTION
**Pull request by hypeJunction**
Makes it easier to remove all core branded favicons by unregistering
a hook handler.

### CODE REVIEW

**Comment by mrclay** [comment]
Looks useful, not tested.

**Comment by hypeJunction** [comment]
Head before:
```html
<head>
    <title>Dev 2.0</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="description">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<meta name="mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<link rel="apple-touch-icon" href="http://hackathon2.dev/cache/0/default/aalborg_theme/homescreen.png">
	<link rel="icon" href="http://hackathon2.dev/cache/0/default/favicon.ico">
	<link rel="icon" sizes="16x16 32x32 48x48 64x64 128x128" type="image/svg+xml" href="http://hackathon2.dev/cache/0/default/favicon.svg">
	<link rel="icon" sizes="16x16" type="image/png" href="http://hackathon2.dev/cache/0/default/favicon-16.png">
	<link rel="icon" sizes="32x32" type="image/png" href="http://hackathon2.dev/cache/0/default/favicon-32.png">
	<link rel="icon" sizes="64x64" type="image/png" href="http://hackathon2.dev/cache/0/default/favicon-64.png">
	<link rel="icon" sizes="128x128" type="image/png" href="http://hackathon2.dev/cache/0/default/favicon-128.png">
	<link rel="alternative" type="application/rss+xml" title="RSS" href="http://hackathon2.dev/?view=rss">
	<link rel="manifest" href="http://hackathon2.dev/manifest.json">
	<link rel="stylesheet" href="http://hackathon2.dev/cache/0/default/font-awesome/css/font-awesome.css">
	<link rel="stylesheet" href="http://hackathon2.dev/cache/0/default/elgg.css">
</head>
```

Head ater (stripped JS):
```html
<head>
    <title>Dev 2.0</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="description">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<meta name="mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<link rel="alternative" type="application/rss+xml" title="RSS" href="http://dev2.dev/?view=rss">
	<link rel="apple-touch-icon" href="http://dev2.dev/cache/0/default/aalborg_theme/homescreen.png">
	<link rel="icon" href="http://dev2.dev/cache/0/default/favicon.ico">
	<link rel="icon" sizes="16x16 32x32 48x48 64x64 128x128" type="image/svg+xml" href="http://dev2.dev/cache/0/default/favicon.svg">
	<link rel="icon" sizes="16x16" type="image/png" href="http://dev2.dev/cache/0/default/favicon-16.png">
	<link rel="icon" sizes="32x32" type="image/png" href="http://dev2.dev/cache/0/default/favicon-32.png">
	<link rel="icon" sizes="64x64" type="image/png" href="http://dev2.dev/cache/0/default/favicon-64.png">
	<link rel="icon" sizes="128x128" type="image/png" href="http://dev2.dev/cache/0/default/favicon-128.png">
	<link rel="manifest" href="http://dev2.dev/manifest.json">
	<link rel="stylesheet" href="http://dev2.dev/cache/0/default/font-awesome/css/font-awesome.css">
	<link rel="stylesheet" href="http://dev2.dev/cache/0/default/elgg.css">
</head>
```

**Comment by hypeJunction** [comment]
I could reface `elgg_view_page()` into a class, but I don't see much gain except for making it testable.

**Comment by juho-jaakkola** [comment]
What is the use case for removing the favicons completely instead of overriding them with your own versions?

**Comment by hypeJunction** [comment]
Most projects I work on only have/want only one favicon size. Additionally
favicons affect page load time.

**Comment by juho-jaakkola** [comment]
Ok, LGTM

**Pull request merged**
