### PR TITLE
feature(entities): allow to dynamically alter entity constructor class

### PR DESCRIPTION
**Pull request by hypeJunction**
This allows the plugins to dynamically alter the constructor class of an entity.

### CODE REVIEW

**Comment by hypeJunction** [comment]
@mrclay Not sure if this is a good idea, but it would help in cases when you want to use a different class instead of default 'ElggUser', 'ElggGroup', 'ElggObject' or 'ElggSite'. There is currently no way to alter those if they don't have a subtype.

Potentially, we could deprecate add_subtype(), and feed class names currently stored in the database to the hook, and eventually switch to dynamic loading. I believe @ewinslow also had an idea of using a separate file for these definitions.

Either way, I need to alter some of the methods in ElggUser, as I am working on a site that has higher security requirements.

**Comment by mrclay** [comment]
Definitely adds flexibility to mapping entities to classes, though I lean towards thinking extending the core classes is not a great idea since only one plugin can really do this. Also if the class isn't available, we still have to instantiate a completely different class. Using composition to apply behavior to vanilla ElggObjects solves both problems.

**Comment by hypeJunction** [comment]
Where can I read up on composition?

**Comment by mrclay** [comment]
```php
$wrapped = new Wrapper($entity);
$wrapped->doSomething();
// or simply
function doSomething($entity) { ... }
```
https://en.wikipedia.org/wiki/Composition_over_inheritance

**Comment by hypeJunction** [comment]
Seems like a lot of code rewrite to achieve that. Plus $entity would still
need to be constructed to be injected in the wrapper, so the problem of
class mapping still exists, IMHO.

**Comment by hypeJunction** [comment]
I have tried this approach and it worked, but I wasn't too crazy about it in the end.

**Pull request closed without merging**
