### PR TITLE
LICENSE update

### PR DESCRIPTION
**Pull request by johnnymast**
Updated the license date in the license.txt file.

### CODE REVIEW

**Comment by jdalsem** [comment]
Hi Johnny,

the commit check is failing because your commit message is not in the expected format. You can read here about commit message formats: http://learn.elgg.org/en/stable/contribute/code.html#commit-message-format

In this case i would expect something like:
`chore(license): updated license year to 2017`

Are you able to update the wording of this commit?

**Comment by johnnymast** [comment]
@jdalsem Thanks for pointing this out to me. I will have a look and make it right.

**Comment by jdalsem** [comment]
@johnnymast great... make sure to leave just one commit message... you might need to squash the commits or, if you do not know how to do that, you might just as easily create a new PR with a new commit...

**Comment by johnnymast** [comment]
I will make a new PR thank you.

**Comment by johnnymast** [comment]
Aah .. Also a dutch guy ..

**Comment by jdalsem** [comment]
> Aah .. Also a dutch guy ..

Jazekers!

**Comment by johnnymast** [comment]
Nice 🥇

**Pull request closed without merging**
