### PR TITLE
chore(composer): Updating elgg/elgg will auto copy plugins to /mod/

### PR DESCRIPTION
**Pull request by ewinslow**
- [ ] create /mod/ dir first
- [ ] fix doc comments

### CODE REVIEW

**Comment by mrclay** [comment]
Besides doc comments looks good. https://travis-ci.org/Elgg/Elgg/jobs/69754466#L487

**Comment by mrclay** [comment]
Do we need to create the `mod` directory first?

**Comment by iionly** [comment]
Is this the WIP to fix the problem of https://github.com/Elgg/Elgg/issues/8712? If that's the case, should this issue be a blocker for release of 2.0?

**Comment by ewinslow** [comment]
Added as blocker

**Comment by ewinslow** [comment]
I dislike this approach now. I think when I get time I'm going to go with a symlink approach instead. This won't work for setting up a zip bundle, but that's ok... I feel a symlink approach would be far less dirty.

**Pull request closed without merging**
