### PR TITLE
chore(js): Use npm-asset instead of bower-asset

### PR DESCRIPTION
**Pull request by ewinslow**
Seems faster. Also, seems like npm is essentially becoming the standard JS package repo over all others

### CODE REVIEW

**Comment by hypeJunction** [comment]
Nice, but it removes views and as such is a breaking change

**Comment by ewinslow** [comment]
What views were removed? I didn't expect that as a side effect.

**Comment by hypeJunction** [comment]
Eh, never mind. The views are mapped without prefixes. It would only break someone trying to  use an asset directly from vendors, but hopefully noone is trying to do that.

**Comment by mrclay** [comment]
Could use a mention in guides/upgrading and maybe a warning not to rely on vendors/ directly in the Views docs.

**Pull request closed without merging**
