### PR TITLE
fix(discussions): reply form is now only rendered when container permissions are satisfied

### PR DESCRIPTION
**Pull request by hypeJunction**

### CODE REVIEW

**Comment by mrclay** [comment]
Looks right to me

**Comment by iionly** [comment]
Was this merged into 2.x intentionally? I have just noticed that the same bug also occurs on 2.2 (and the community site). The former PR that was not merged and replaced by this one was commited against the 2.0 branch.

**Comment by mrclay** [comment]
@hypeJunction You remember why 2.x?

**Comment by hypeJunction** [comment]
I think this relies on container logic check.

**Pull request merged**
