### PR TITLE
feature(views): elgg_get_excerpt output now comes from a view

### LINKED ISSUE #8925: Option to alter the output of elgg_get_excerpt() function.
It will be better is there is an option to alter the output of elgg_get_excerpt(). 

For example in some of our user cases we needed to pass a "...read more..." text with hyperlinks and class / id names instead of the current "...." output thing. If this is available, we don't have to unnecessarily duplicate the same code for this simple thing.

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #8925

### CODE REVIEW

**Comment by hypeJunction** [comment]
Is it a page element? Maybe better to put it under object elements?

**Comment by jdalsem** [comment]
agreed

**Comment by hypeJunction** [comment]
To consider: `elgg_view_excerpt()` that calls `elgg_get_excerpt()`. I suppose you want to have control over how the excerpt is displayed, so maybe trigger a hook from `elgg_get_excerpt()`?

**Comment by jdalsem** [comment]
You already have control with the view vars hook, but for a we could introduce `elgg_view_excerpt` that uses an entity and checks `$entity->excerpt` before using `$entity->description` to create an excerpt and also always adds a clickable link...

Scenario's that can not use elgg_view_excerpt (like non entities) should use elgg_get_excerpt.

Is this something we should add in 2.x or in master?

**Comment by mrclay** [comment]
Why object/elements? Confusing because has nothing to do with objects in the Elgg sense or the PHP sense. Why not output/excerpt?

**Comment by jdalsem** [comment]
> Why not output/excerpt?

was also on my mind (same as friendly_time), but i always thought the input/output views were mostly for the matching html form elements... 

More people in favor of output/excerpt? I can only move it one more time... :wink:

**Comment by hypeJunction** [comment]
`output/excerpt` sgtm

**Comment by jdalsem** [comment]
moved to `output/excerpt`

**Comment by hypeJunction** [comment]
This started causing trouble in non-default viewtypes that do not fallback

**Comment by jdalsem** [comment]
you should have similar problems with other functions that use views for output... like elgg_view_friendly_time

**Comment by hypeJunction** [comment]
Yep, that's probably true. I was just working with some json output and noticed I wasn't getting any output for excerpts.

**Pull request merged**
