### PR TITLE
perf(engine): only update attributes/metadata if value is changed

### PR DESCRIPTION
**Pull request by jdalsem**
rebranched version of #8594

### CODE REVIEW

**Comment by ewinslow** [comment]
Lgtm

**Comment by jdalsem** [comment]
This also fixes #8043

**Comment by mrclay** [comment]
This isn't necessarily BC because a write could change the `access_id` even if value doesn't change. https://github.com/Elgg/Elgg/issues/8043#issuecomment-77581164

**Comment by jdalsem** [comment]
@mrclay you are right for the very specific usecase where you do ```$entity->metadata = value``` and actually expect access_ids to be reset on the metadata... If you were aiming on changing the access of a metadata you should however be using ```$entity->setMetadata(x,x,x,x)```

**Comment by mrclay** [comment]
Yeah, I think we can let this be. I'll continue to push for no access_id in metadata :)

**Pull request merged**
