### PR TITLE
fix(install): remove obsolete _graphics rewrite rule

### LINKED ISSUE #8732: Wrong (or at least unnecessary) rewrite rule on zip install of Elgg 2.0
.htaccess contains the rewrite rule
```
RewriteRule ^(_graphics|js)/(.*)$ vendor/elgg/elgg/$1/$2
```
This makes no sense at least when installing Elgg 2.0 using a zip archive. I don't know if it might even result in issues.

### PR DESCRIPTION
**Pull request by iionly**
Fixes #8732.

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
Steve didn't mean that you need to replace ```chore()``` with ```fix()```.

He meant that instead of just this:
```
chore(install): remove obsolete _graphics rewrite rule
```
the commit message should also have the issue number:
```
chore(install): remove obsolete _graphics rewrite rule

Fixes #8732
```

You can edit the commit message of an existing PR like this: https://help.github.com/articles/changing-a-commit-message/

**Comment by ewinslow** [comment]
The git commit message itself needs to be ammended, not just the PR (everyone gets this confused)

**Comment by iionly** [comment]
As I was never asked before to include the "Fixes" line into the commit message on previous PRs I made I was kind of confused regarding what is expected.

Commit message is updated. I hope it's right this time.

**Comment by juho-jaakkola** [comment]
Yep, it is!

**Pull request merged**
