### PR TITLE
chore(upgrades): Removes pre-1.11 upgrade scripts, actions, and views

### LINKED ISSUE #5703: Put all mysql_* calls behind the API
This is step towards DBAL.

There several issues:
- [ ] upgrade scripts
- [ ] tests
- [ ] installer
- [ ] Elgg_CacheHandler
- [ ] mod/profile/icondirect.php

Id like all of them to use Elgg_Database methods instead of mysql_* directly, so we could abstract DB layer inside this class only.

### PR DESCRIPTION
**Pull request by mrclay**
Also removes 3 deprecated functions that use ext/mysql resources directly

Fixes #5703

### CODE REVIEW

**Comment by beck24** [comment]
LGTM - ran a successful test install with it

**Comment by juho-jaakkola** [comment]
LGTM

**Comment by Srokap** [comment]
I'm not convinced that just removing upgrade scripts is a good idea. As I mentioned in the chat:

perhaps we shouldn't try to support the past with new dby types
if you upgrade from mysql, you can very well upgrade to mysql first and than migrate to different type
if you install from scratch, you don't care about the old upgrade scripts

Removing all of them just complicates upgrading of Elgg by requiring to go to last 1.x before skipping to 2.0 (which would be recommended, but not required at this point). I'm not sure that's even beneficial for us at this point. We don't even introduce any new upgrade system. I think we should live with those scripts as it's only ugly and doesn't cause any direct problems.

That would at least require some motivation to write down why we decided on doing that.

**Comment by juho-jaakkola** [comment]
In fact skipping minor upgrades is not only discouraged but impossible at the moment. Skipping e.g. 1.9 causes you to have a broken site.

**Comment by juho-jaakkola** [comment]
If this does get merged, it should also remove ```classes\Elgg\Upgrades\Helper2013022000.php```.

**Comment by Srokap** [comment]
I imagine we could perhaps start using something like http://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html, but I'd keep old upgrades until we do.

**Comment by mrclay** [comment]
I've removed more upgrade-specific stuff and clarified the commit message. Could removing these actions/views break anything?

**Comment by jdalsem** [comment]
LGTM; i do not have a problem with dropping all this code

**Comment by juho-jaakkola** [comment]
I don't think removing these will break anything.

I'm actually working on a rewamp to the upgrading features for 2.0. The new way won't be compatible with these old files anyway.

**Pull request merged**
