### PR TITLE
feat(core): added config to disable RSS feeds and Elgg branding

### PR DESCRIPTION
**Pull request by jdalsem**
image

### CODE REVIEW

**Comment by hypeJunction** [comment]
Shoudl also remove favicons

**Comment by jdalsem** [comment]
> Shoudl also remove favicons

you mean in case of elgg branding it should not register the default favicons? agreed

**Comment by hypeJunction** [comment]
I have moved all favicon registrations to a separate hook at some point, so it's easy to remove them. Maybe just add another setting for favicons, because people can override them using view system.

**Comment by jdalsem** [comment]
removing favicons with the branding config is a bad plan... it is no branding specific icons... just generic views which happen to map to default elgg icons... i could add a config flag for disabling favicons, but why would you want to do that? Better to provide your own or unregister the hook in your custom plugin

**Pull request merged**
