### PR TITLE
chore(lightbox): Pull Elgg’s custom colorbox theme back in

### LINKED ISSUE #8416: master: lightbox CSS broken
It's registered to the js/lightbox.css view? @ewinslow

### PR DESCRIPTION
**Pull request by mrclay**
None of the themes in vendor/bower-asset match ours.

Fixes #8416

### CODE REVIEW

**Comment by ewinslow** [comment]
https://github.com/Elgg/Elgg/pull/8434 adds support for images in vieww. How about we check that in and then we can just put our custom theme in the views system where it belongs...

**Comment by mrclay** [comment]
We got this issue from under reviewing a big change, so I don't suggest we do the same to fix it. I've also got a ton of work awaiting review so I get how you feel, but we have plenty of opportunities to get features in now and we can even push back 2.0 if it seems worth it.

**Comment by ewinslow** [comment]
Looks like you may have to rebase to get the .travis.yml fix I just submitted.

**Comment by jeabakker** [comment]
lgtm

**Comment by mrclay** [comment]
Pulling this in. #8434 will give us opportunities to refactor a bunch later.

**Pull request merged**
