### PR TITLE
chore(refactoring): cleanup an unused filestore function

### PR DESCRIPTION
**Pull request by jeabakker**
- [ ] deprecate file_delete() in 1.x

### CODE REVIEW

**Comment by jeabakker** [comment]
this function is also handled by 
https://github.com/Elgg/Elgg/blob/master/mod/file/classes/FilePluginFile.php#L28-L41

and useless because of 
https://github.com/Elgg/Elgg/blob/master/engine/classes/ElggEntity.php#L2095
https://github.com/Elgg/Elgg/blob/master/engine/lib/filestore.php#L407-L413

**Comment by mrclay** [comment]
SGTM, but add this to the removed functions list in docs/guides/upgrading.rst

**Comment by juho-jaakkola** [comment]
Don't we first need to deprecate this in 1.x? It's a public function after all.

**Comment by mrclay** [comment]
@juho-jaakkola yes. If it's not needed we could rewrite it as a no-op in 1.x

**Comment by mrclay** [comment]
...err, rather get rid of the thumbnail cleanup code

**Comment by hypeJunction** [comment]
Chore is synonymous with refactor. chore(filestore) is clearer

**Comment by jeabakker** [comment]
i'll make a new pr to deprecate in 1.x

**Pull request closed without merging**
