### PR TITLE
feat(ajax): add support for FormData and multipart form data requests

### PR DESCRIPTION
**Pull request by hypeJunction**
elgg/Ajax now uses FormData API to objectify form data.
Subsequently Elgg ajax requests can be used to submit multipart form-data.

### CODE REVIEW

**Comment by hypeJunction** [comment]
@mrclay Could you take a look, when you have a chance. This would be the first step, eventually I'd like to start using axios, instead of hacky jQuery Ajax module.

**Comment by mrclay** [comment]
I'm cool with this, but would a FormData polyfill work?

**Comment by hypeJunction** [comment]
I suppose we could add it, but most browsers already support it. Is modernizr still a thing for polyfills? I can do some background research

**Comment by hypeJunction** [comment]
@mrclay Any thoughts about the tests?

**Comment by hypeJunction** [comment]
I got the tests to pass.

**Comment by jdalsem** [comment]
yay... is this ready for a review/merge now?

**Comment by hypeJunction** [comment]
Yes

**Comment by jdalsem** [comment]
LGTM. Don't you think this could break something?

**Comment by hypeJunction** [comment]
> LGTM. Don't you think this could break something?

It will break anyone piggybacking request data using JS hooks, but I doubt that anyone is even using that feature.

**Pull request merged**
