### PR TITLE
fix(datepicker): Prevents month navigation links from overlapping with other elements

### LINKED ISSUE #7542: Datepicker: text overlay (language depending) and popup not wide enough (Aalborg theme)
Text overlay is an issue that can happen depending on the (site/user) language used. Some months' names are longer in other languages compared to English and this can result in the "Prev" link and month name to overlay.

When Aalborg theme is used the problem gets slightly worse (due to the larger larger font). Now there's not only an overlay of the text but also the content of the datepicker popup is wider than the popup itself.

### PR DESCRIPTION
**Pull request by juho-jaakkola**
It is difficult to predict how much translatable strings need space in each language. This
replaces the textual representation with icons to make sure that the Next and Previous
links do not take up too much space.

Fixes #7542
- [x] Add better styles for the icons

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
@PerJensen Could you take a look at the styles? The icons don't look very good ATM.

**Comment by mrclay** [comment]
This should go in 1.x, right?

**Comment by juho-jaakkola** [comment]
I'd consider this a bugfix because the Previous/Next strings are currently overlapping with other elements.

datepicker2

**Comment by PerJensen** [comment]
This is how it looks with your fix, seems ok:

datepicker

**Comment by jdalsem** [comment]
LGTM

**Pull request merged**
