### PR TITLE
fix(views): view can only exist if it is string

### PR DESCRIPTION
**Pull request by hypeJunction**

### CODE REVIEW

**Comment by mrclay** [comment]
LGTM

**Comment by ewinslow** [comment]
Cool, and thanks for the test. I think the test name could be changed to "testViewCanOnlyExistIfString". That is more in keeping with our pattern of describing the expected behavior rather than just describing the inputs.

**Comment by jdalsem** [comment]
LGTM

**Comment by hypeJunction** [comment]
@ewinslow renamed the test

**Pull request merged**
