### PR TITLE
chore(members): Fix members/index page

### LINKED ISSUE #8514: master: members pages 404
The resources/members/index view is looking for `$vars['page']`. That needs to be passed via set/get_input().

### PR DESCRIPTION
**Pull request by ewinslow**
Fixes #8514

### CODE REVIEW

**Comment by jdalsem** [comment]
why not add the $_REQUEST['page'] to $vars in the page_handler? less changes...

**Comment by ewinslow** [comment]
End result is cleaner.

**Comment by ewinslow** [comment]
Oh, and that wouldn't actually work. `elgg_view_resource` doesn't pass `$vars` to the view.

**Comment by jdalsem** [comment]
> End result is cleaner.

why? can you explain why a get_input in a view is better then in the page_handler?

> elgg_view_resource doesn't pass $vars to the view

is that by design? if it is a view, i would like to have $vars available in the view right?

**Comment by ewinslow** [comment]
It is how all the resources views do it right now.

You are certainly welcome to voice your company in a separate ticket. I can see this confusing others as well.

**Comment by ewinslow** [comment]
Voice your complaint*

**Comment by jdalsem** [comment]
Opened #8532 to let my voice be heard

**Pull request merged**
