### PR TITLE
feature(file): file search menu is now displayed in the sidebar when dis...

### PR DESCRIPTION
**Pull request by socialatm**
...playing a file

the file search sidebar does not appear in full view. This adds it in.

### CODE REVIEW

**Comment by hypeJunction** [comment]
Looks good, but perhaps we can extend the file/sidebar with a new typecloud view. That way plugins can unextend.

**Comment by twentyfiveautumn** [comment]
Thanks @hypeJunction I'm going to sleep on it ;)

**Comment by twentyfiveautumn** [comment]
> Looks good, but perhaps we can extend the file/sidebar with a new typecloud view. That way plugins can unextend.
I guess that would be a good thing to have but it's not an option any of the other views in the file plugin. This PR just adds the missing menu.

**Comment by hypeJunction** [comment]
> it's not an option on any of the other views
Not good enough reason to not do things the better way :)
If I wanted to change the position of the typecloud menu to go under the other views, I would have to really hack my way through. Making it a view extension would greatly simplify dev usability in the long run.

**Comment by twentyfiveautumn** [comment]
@hypeJunction I get that, thanks. So if it's added to the full view I'm thinking it should be added to the list and gallery views as well?

**Comment by hypeJunction** [comment]
I see why not.

**Comment by juho-jaakkola** [comment]
The merge commit doesn't belong to the PR. You should use ```rebase``` command instead of ```merge```.

**Comment by jdalsem** [comment]
@hypeJunction what is needed (other then the merge commit issue) to get this one in?

**Comment by hypeJunction** [comment]
This can go in as is, I suppose, but I would prefer to have a new view that extends file/sidebar with an earlier priority.

**Comment by mrclay** [comment]
**Note:** This was closed simply because the 1.x branch was retired. Send a new PR for the 2.x branch if this is still being considered.

**Pull request closed without merging**
