### PR TITLE
fix(profile): moved topbar profile menu registration to profile plugin

### PR DESCRIPTION
**Pull request by jdalsem**
Refs #5967

### CODE REVIEW

**Comment by hypeJunction** [comment]
Lgtm

**Comment by mrclay** [comment]
LGTM. I don't know if this would have a BC issue.

**Comment by PerJensen** [comment]
If you have a plugin that unregisters profile menu item in order to move it to another menu, account for instance, it will now fail. 

So the menu item will appear in the old spot and not appear where you want it to, because there's not anything to unregister anymore.

Why not register the item the way it was registered in users.php?

**Comment by jdalsem** [comment]
> If you have a plugin that unregisters profile menu item in order to move it to another menu, account for instance, it will now fail.

Good point


> Why not register the item the way it was registered in users.php?

Yeah, that will prevent the issue you mentioned. I prefer registering menu items in the register hook, but to keep it BC i will change it to the old fashioned way :)

**Comment by PerJensen** [comment]
:+1:

**Comment by ewinslow** [comment]
Not 1.10?

**Pull request merged**
