### PR TITLE
WIP merging mrclay into master

### PR DESCRIPTION
**Pull request by mrclay**
All commit messages here: https://gist.github.com/mrclay/65ee222e991a34564572d2d3781d4142

Notable stuff to look over:

- https://github.com/Elgg/Elgg/pull/11049/files#diff-eac4394d790d566d38ea6e3adc64911b
- https://github.com/Elgg/Elgg/pull/11049/files#diff-ab6e60fdb4d0b38dff291eca00824036
- https://github.com/Elgg/Elgg/pull/11049/files#diff-c27907a0c7e9cdceaf76a833068bde35
- https://github.com/Elgg/Elgg/pull/11049/files#diff-5e880a7dea5c3b65eb64958449651550

TODO

- [ ] move "no-data-demo" somewhere
- [ ] must remove the `Elgg\Project\NoDataElgg` class, too?

### CODE REVIEW

**Comment by mrclay** [comment]
OK so remaining problem here is a bunch of essentially duplicate commits, stuff I earlier cherry-picked over to get into master.

**Comment by jdalsem** [comment]
This can not go in. There are too many duplicate commits. Also the env file needs some discussion. Other changes look good. Hopefully you can split this PR is a few smaller ones.

**Comment by mrclay** [comment]
@Elgg/core Does anyone else see particular deal-breakers here?

**Comment by beck24** [comment]
There's a lot in here, I haven't read through all of them yet but I like the ones you've linked.

**Comment by mrclay** [comment]
Replaced by #11092

**Pull request closed without merging**
