### PR TITLE
chore(docs): updated the release docs

### PR DESCRIPTION
**Pull request by jeabakker**

### CODE REVIEW

**Comment by jdalsem** [comment]
Typo in commit message... Dows

Op 27 jan. 2017 12:18 p.m. schreef "Jerôme Bakker" <notifications@github.com

**Review by jdalsem — APPROVED** [review]

**Comment by jeabakker** [comment]
> Typo in commit message... Dows

fixed

**Comment by mrclay** [comment]
You need to also remove the earlier reference (line 21).

**Comment by jeabakker** [comment]
> You need to also remove the earlier reference (line 21).

thanks, fixed it

**Review by hypeJunction — APPROVED** [review]

**Pull request merged**
