### PR TITLE
chore(views): removed unused view output/checkboxes

### LINKED ISSUE #4649: output/checkboxes needs help (Trac #4649)
_Original ticket http://trac.elgg.org/ticket/4649 on 42497439-01-19 by cash, assigned to unknown._

Elgg version: 1.8

it is using output/tags. That does not make any sense.

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #4649

No need to keep this around, not used in core anywhere... probably a relic from the site_categories plugin

### CODE REVIEW

**Comment by hypeJunction** [comment]
Hm, I think we need an output view for each input view. Eventually we will allow profile/group fields to be an array of fields config. Outputting those values will need corresponding views, unless we do some internal mapping...

**Comment by jdalsem** [comment]
> I think we need an output view for each input view

that will bring you a lot of work... 



> Eventually we will allow profile/group fields to be an array of fields config. Outputting those values will need corresponding views, unless we do some internal mapping...

we currently do not have that 'requirement'

i do something similar in Profile Manager (as we extended the available input types) and we do a mapping to output views...

**Comment by jdalsem** [comment]
I would like to merge this... if we want to discuss if we want output views for every input view... we could discuss that in another ticket...

**Comment by hypeJunction** [comment]
Is it bothering you so much?

**Comment by jdalsem** [comment]
well it fixes an issue.. so yeah :)

**Pull request merged**
