### PR TITLE
fix(plugins): reduce callstack and optimized cached for boot plugins

### PR DESCRIPTION
**Pull request by jdalsem**

### CODE REVIEW

**Comment by jdalsem** [comment]
@hypeJunction any idea why this fails? What relationship does the hooks have with the active plugins?

**Comment by hypeJunction** [comment]
That test case makes sure that testing application is bootstraped correctly for each test. Whatever changes you made are either getting cached or something else is happening, subsequently the application state is different.

**Comment by jdalsem** [comment]
is the test case correct? it looks like it tests if hooks registrations stay the same between application changes

**Comment by jdalsem** [comment]
> Yes, it is correct. To speed up integration tests we recycle the application, whatever changes you made alters the state of the application, i.e. plugin order, which results in hooks being ordered differently.

fine, but this test tests if they stay the same between changes of the application...

**Comment by hypeJunction** [comment]
If you disable a plugin and then enable it with the same priority, the hook stack should be the same. So, whatever you are trying to do is either getting somewhere where it shouldn't (I'd suspect boot plugins), or the changes are not being propagated correctly without page reload, which shouldn't happen as it reduced reliability of test cases.

**Review by jeabakker — APPROVED** [review]

**Comment by iionly** [comment]
Does this also fix https://github.com/Elgg/Elgg/issues/12140 (and https://github.com/Elgg/Elgg/issues/12152 that I had closed as being a duplicapte of 12140)? PR https://github.com/Elgg/Elgg/pull/12143 had fixed these two issues but now @hypeJunction closed it due to this PR here being merged resulting in conflicts. If the two issues are not fixed, the other PR would have to be re-opened...

Would this PR here also fix https://github.com/Elgg/Elgg/issues/12191?

**Pull request merged**
