### PR TITLE
chore(plugins): removed the plugin screenshot page handler

### PR DESCRIPTION
**Pull request by jdalsem**
Did this because of #8593. Screenshots are no longer loaded on the plugins list page. Only in the lightbox. As we use the thumbnail AND the full image both in the lightbox, these images could just as well be the same (just resize them with css). This saves an extra webserver call and uses regular browser cache.

### CODE REVIEW

**Comment by mrclay** [comment]
LGTM, have not tested.

**Comment by mrclay** [comment]
Add `Fixes #8593` to commit.

**Comment by mrclay** [comment]
Should this be considered a breaking change? Particularly I'm imagining users already using one of the ColdTrick plugins that we adapted from.

**Comment by jdalsem** [comment]
> Add Fixes #8593 to commit.

it is not really fixing it.. rather making it obsolete



> Should this be considered a breaking change?

De page handler function is private... i guess we need better guidance on when we can declare something private or not...

**Comment by mrclay** [comment]
I decided to not worry about it :)

**Pull request merged**
