### PR TITLE
Release 2.0.0 beta.3

### PR DESCRIPTION
**Pull request by mrclay**

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
I don't understand. We added the Transifex config: https://github.com/Elgg/Elgg/blob/2.0/.tx/config#L52 and we added the --force flag: https://github.com/Elgg/Elgg/blob/2.0/.scripts/release.php#L52

But translations for discussions are still missing!

Did you notice anything funny with the Transifex client when you were making the release?

**Comment by mrclay** [comment]
No message from the client

**Comment by mrclay** [comment]
Correction: I don't know. I lost my console history from creating the release.

**Comment by mrclay** [comment]
I'm re-running it to see

**Comment by mrclay** [comment]
The client mentions them, but just doesn't install them.
```
...
Pulling new translations for resource elgg-core-2.discussions (source: mod/discussions/languages/en.php)
 -> de: mod/discussions/languages/de.php
New translations found for the following languages: zh-Hans, eu_ES, pt_BR
Pulling translations for resource elgg-core-2.embed (source: mod/embed/languages/en.php)
 -> fr: mod/embed/languages/fr.php
...
```

**Comment by mrclay** [comment]
They didn't meet 95%.

**Comment by juho-jaakkola** [comment]
Huh, weird. I could swear e.g. Finnish has been at 100% all the time.

**Pull request merged**
