### PR TITLE
WIP feat(ajax): ajax responses can load CSS

### LINKED ISSUE #11302: elgg_load_css not working for elgg.ajax
elgg_require_js is working, but elgg_load_css not... would be nice

### PR DESCRIPTION
**Pull request by mrclay**
Fixes #11302

This doesn't respect ordering when SS are added, but that doesn't seem a dealbreaker.

### CODE REVIEW

**Review by jeabakker — DISMISSED** [review]

**Comment by jeabakker** [comment]
if tests are fixed it can be merged

**Comment by jdalsem** [comment]
@mrclay is this something you can finish?

**Comment by jdalsem** [comment]
@mrclay can you at least let us know why this is WIP? maybe someelse can finish up...

**Comment by mrclay** [comment]
It seems unwise to add uncertainly about order of CSS loading. And unlike AMD there's no way for the system to know when a CSS view has already been loaded by, eg, appending to elgg.css. Those are my only objections though.

**Comment by jdalsem** [comment]
Closing this as there will be no solution on the horizon where we have control over order or know if css is already loaded

**Pull request closed without merging**
