### PR TITLE
docs(upgrading): Warn site owners about MultiViews and /settings URLs

### LINKED ISSUE #8806: MultiViews with root settings.php breaks settings URLs
It is not possible to access www.site.com/settings/* if ```settings.php``` is located at the Elgg root.

This also could be a problem with other magic/common Elgg directories like "views" or "actions".

Possible solutions:

 1. Prefix with `elgg-` (`elgg-settings.php`, `elgg-views/`, etc...)
 1. Move `index.php` handler into subdir (e.g., `public/index.php` like Laravel). Means you have to do some more work to make sure that "/public" isn't part of your website's path. :cry: 
 1. Place into `elgg-config/` directory: (`elgg-config/settings.php`, `elgg-config/views/`, etc.).
 1. Rename settings to something better like `.env.php` (might be a good idea anyways, but we'd still need to address the `views/`, `actions/`, etc. conflict.)
 1. Make `engine/start.php` the default location for non-composer installs.
 1. Just `elgg-` prefix the settings file.

### PR DESCRIPTION
**Pull request by mrclay**
Fixes #8806

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
LGTM

**Comment by iionly** [comment]
Is it really the MultiViews option that is causing the problem with the settings.php file / settings page?

I've just updated a test installation to beta1 and now I have the problem with a WSOD on the settings page for the first time. On another test installation on the same server (possibly still rc1 or even older) there's no issue with the settings page.

MultiViews option is enabled on the server but even disabling it (or uncommenting the lines in .htaccess) makes no difference, i.e. always WSOD on settings page on beta1.

Could it be that the RewriteBase makes any difference (I have to set it on this server)? Also, what's the meaning of "If you place your ``settings.php`` file in the installation root"? Where else can the settings.php file be placed on Elgg 2.0?

**Comment by iionly** [comment]
Okay... this other installation can't be taken as reference. It has the the settings.php still in the engine directory (elgg not in vendors etc.). As I said, it's rc1 or older.

Creating an "engine" folder in root and moving settings.php into it resulted in the settings page getting displayed again. But I wouldn't say this is really a solution but rather a workaround!!!

As I said before, disabling MultiViews and/or uncommenting the lines in .htaccess doesn't work for me.

**Comment by mrclay** [comment]
A separate issue is affecting the settings page. #8923 (embed has a syntax error in it.php).

**Comment by iionly** [comment]
The it.php file of the embed plugin wasn't the reason for the WSOD on the settings page. I already had to delete this file to be able to run upgrade.php when updating to beta1. The WSOD turned up afterwards. I even deleted all language files (apart en.php and de.php) and this didn't help either.

**Comment by iionly** [comment]
Found my error! I had tried it with the code changes in .htacces of #8922 instead of the changes proposed in this PR... Adding "Options -MultiViews" to .htaccess worked indeed (as moving settings.php into a newly created engine directory).

**Pull request merged**
