### PR TITLE
WIP chore(js): make elgg.js a true AMD module

### PR DESCRIPTION
**Pull request by mrclay**
Elgg's JS boot is now completely in the `page/elements/foot` view, and better documented.

Adds `elgg.echo_ready()` to delay code until the user's language module is loaded.

BREAKING CHANGE:
Plugins registering synchronous scripts with `elgg_load_js` **must** use `require()` to gain access to `elgg`, `jquery`, and other dependencies.

`elgg.echo()` may not always find translations unless `elgg.elgg_ready()` is used.

Plugins can no longer extend `elgg.js`, but for BC Elgg automatically extends a new synchronous script instead.

### CODE REVIEW

**Comment by hypeJunction** [comment]
Just a thought about deprecation. Should we perhaps leave elgg.js be, and introduce elgg/Application module. elgg.js would require the app and then run the sync code?

**Comment by mrclay** [comment]
I definitely need to make a deprecation PR for 2.x (and reach consensus about the plan) before moving more on this.

**Comment by beck24** [comment]
I like the extendability of elgg.js - for any site-wide js it saves calls.  Require is awesome, but there's still a time cost for multiple calls to load multiple scripts that could otherwise be combined just fine.

**Comment by mrclay** [comment]
FYI elgg.echo_ready would not be necessary if using an async API #9028.

**Comment by mrclay** [comment]
:-1: loading elgg.js asynchronously. Not worth the cost.
:+1: improving docs RST and around the boot process.
:+1: loading language async and `elgg.echo_ready`, probably easier than transitioning to #9028

**Comment by hypeJunction** [comment]
I think this is a time waster for now. Let's first convert all core JS to AMD and we can then think if it's still necessary.

**Pull request closed without merging**
