### PR TITLE
feature(file plugin): Add upload button to sidebar search pages

### LINKED ISSUE #8110: Upload a file button missing from file plugin sidebar search
When you search specific file types from the sidebar in the files plugin the page you are taken to is missing the **Upload a flle** button in the title menu.
Even if you click **All** in the sidebar the button is missing.

Adding
```
elgg_register_title_button();
```
to line 20 of **mod/file/pages/file/search.php** corrects the issue.

### PR DESCRIPTION
**Pull request by socialatm**
Fixes #8110

### CODE REVIEW

**Comment by jdalsem** [comment]
PR is ok but the commit message format is not correct. Please have a look at this documentation on how to format your commit messages: http://learn.elgg.org/en/latest/contribute/code.html#commit-message-format

**Comment by twentyfiveautumn** [comment]
Thanks @jdalsem . I'll go have a look at that.

**Comment by juho-jaakkola** [comment]
This part tells how to update the commit message of an existing pull request: http://learn.elgg.org/en/latest/contribute/code.html#rewriting-commit-messages

(No need to close this one and create a new one)

**Comment by twentyfiveautumn** [comment]
Thank you @juho-jaakkola . I'm kinda new at this

**Comment by twentyfiveautumn** [comment]
Is that closer?

**Comment by juho-jaakkola** [comment]
You changed the title of the Github issue. You need to change the git commit message instead.

**Comment by twentyfiveautumn** [comment]
Thanks

**Comment by jdalsem** [comment]
dont forget the colon :

**Comment by twentyfiveautumn** [comment]
applied ``git push -f origin master`` everything looks right on my local copy but I can't tell if the changes made it to here?

**Comment by hypeJunction** [comment]
@twentyfiveautumn Doesn't look like they did

**Comment by hypeJunction** [comment]
Is this meant to go to master or 1.x?

**Comment by jdalsem** [comment]
i think it should go to 1.x

**Comment by twentyfiveautumn** [comment]
Meant to go on master. my github repository looks like it picked up the change so not sure on the next step?

**Comment by hypeJunction** [comment]
I am not sure master to master pull requests are working as expected. 
Best to create a branch off the branch you are making a pull request again.
This is for the future reference. Given your change is so small, perhaps it's best to recreate a PR.

```sh
git fetch upstream
get checkout master
git reset --hard upstream master
git checkout -b mybranch

git commit -a -m 'fix(file): commit message'
git push origin mybranch
```

The make a PR using mybranch against master

**Comment by twentyfiveautumn** [comment]
Thanks @hypeJunction I'll try to figure this out

**Comment by hypeJunction** [comment]
Made a quick edit, reset --hard needs a slash

**Comment by hypeJunction** [comment]
If you don't have a remote setup:

```sh
git remote add upstream https://github.com/Elgg/Elgg.git
git remote -v
```

**Comment by juho-jaakkola** [comment]
Wait, why is this going to master? Why not in 1.x?

**Comment by juho-jaakkola** [comment]
This doesn't change any existing feature. Only adds a new one. Therefore it should go to 1.x branch.

**Comment by hypeJunction** [comment]
That was my question :)
@twentyfiveautumn Please make a PR against 1.x branch.

**Comment by twentyfiveautumn** [comment]
day job got in the way. I'll do PR against 1.X

**Pull request closed without merging**
