### PR TITLE
chore(docs): add php_version to plugin dependencies documentation

### LINKED ISSUE #7847: add missing doc for php_version to dependencies
There is no record of php_version in the docs

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #7847

### CODE REVIEW

**Comment by mrclay** [comment]
:+1:

**Comment by ewinslow** [comment]
FYI this could probably have been a `docs(manifest)` commit or something.

**Comment by jdalsem** [comment]
Oh yeah... do you want me to revert and reword?

**Comment by ewinslow** [comment]
No not at all. Just for future reference we have a `docs()` commit type you can avail yourself of.

**Pull request merged**
