### PR TITLE
feat(comments): the comments form is collapsed if there are comments

### PR DESCRIPTION
**Pull request by jdalsem**
image

### CODE REVIEW

**Comment by hypeJunction** [comment]
Should be the opposite, IMO.

**Comment by jdalsem** [comment]
> Should be the opposite, IMO.

When there are comments the focus should be on the comments... if none is written yet, the form is opened by default

**Comment by hypeJunction** [comment]
I think it should be the opposite, if there are comments already, make it easier to respond. If there are no comments, maybe it's not worth people's attention.

**Comment by jdalsem** [comment]
well this wish is based on user and designer feedback

**Comment by hypeJunction** [comment]
Go for it, I don't use core comments.

**Comment by jdalsem** [comment]
> Go for it, I don't use core comments.

what do you use then? discus?

**Comment by hypeJunction** [comment]
hypeInteractions

**Pull request merged**
