### PR TITLE
Merge 1.12 into 1.x

### PR DESCRIPTION
**Pull request by mrclay**
We've neglected this branch for awhile.

### CODE REVIEW

**Comment by mrclay** [comment]
AFAICT the only commit unique to 1.x is https://github.com/Elgg/Elgg/commit/9415c4136849028304327e097c84ac707c21d833

**Comment by mrclay** [comment]
It also has the `['rest:output', $method]` hook.

**Comment by mrclay** [comment]
@Elgg/owners AFAICT the 1.x branch has no custom code at this point. It's already in 2.0/2.x. Shall we delete this branch? We're not going to release 1.13 right?

**Comment by juho-jaakkola** [comment]
Yes, 1.x should be deleted. Let's concentrate on 2.0+

**Pull request closed without merging**
