### PR TITLE
chore(tests): allow running JS tests in Chrome

### PR DESCRIPTION
**Pull request by mrclay**
Adds a couple README links to docs.

Also updates `requirejs` to 2.2, as 2.1 was no longer available. Maybe due to
the kik/left-pad fiasco.

### CODE REVIEW

**Comment by hypeJunction** [comment]
```sh
$ npm install
npm WARN install Couldn't install optional dependency: Unsupported
Elgg@ D:\wamp\www\hackathon2
├─┬ karma-chrome-launcher@0.2.3
│ ├─┬ fs-access@1.0.0
│ │ └── null-check@1.0.0
│ └─┬ which@1.2.4
│   ├─┬ is-absolute@0.1.7
│   │ └── is-relative@0.1.3
│   └── isexe@1.1.2
└── UNMET PEER DEPENDENCY requirejs@~2.1

npm WARN EPEERINVALID karma-requirejs@0.2.4 requires a peer of requirejs@~2.1 bu          t none was installed.
npm WARN EPACKAGEJSON Elgg@ license should be a valid SPDX license expression
```

**Comment by hypeJunction** [comment]
```sh
$ npm run chrome

> Elgg@ chrome D:\wamp\www\hackathon2
> node_modules/karma/bin/karma start js/tests/karma.conf.js --browsers Chrome

'node_modules' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\          node_modules\\npm\\bin\\npm-cli.js" "run" "chrome"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! Elgg@ chrome: `node_modules/karma/bin/karma start js/tests/karma.conf.j          s --browsers Chrome`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Elgg@ chrome script 'node_modules/karma/bin/karma start j          s/tests/karma.conf.js --browsers Chrome'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Elgg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/karma/bin/karma start js/tests/karma.conf.js --browser          s Chrome
npm ERR! You can get their info via:
npm ERR!     npm owner ls Elgg
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\wamp\www\hackathon2\npm-debug.log
```

**Comment by mrclay** [comment]
Can you delete node_modules and npm install again?

**Comment by hypeJunction** [comment]
That didn't do anything. Same error.

**Comment by mrclay** [comment]
1.12 has the same problem. I don't know why Travis can run tests.

**Comment by hypeJunction** [comment]
I was reading yesterday that someone broke internet by pulling out a few packages from NPM, maybe it's related :)  https://medium.com/@mproberts/a-discussion-about-the-breaking-of-the-internet-3d4d2a83aa4d#.jln3i1xei

**Comment by mrclay** [comment]
I added a commit that fixes npm testing for me.

**Comment by mrclay** [comment]
If the new commit fixes `npm install` for you, please merge.

**Comment by mrclay** [comment]
Doesn't affect sites so merging.

**Pull request merged**
