### PR TITLE
docs(faqs): fixed typo in IDE section

### PR DESCRIPTION
**Pull request by lehkonev**
Fixed the possessive form of "it" under the IDE section.

### CODE REVIEW

**Comment by mrclay** [comment]
Thanks. We have [guidelines for commit messages](http://learn.elgg.org/en/2.0/contribute/code.html#commit-message-format). So if you recreate/reword the commit message:
```
docs(faqs): fixed typo in IDE section
```
...then our CI will pass and we can pull it in.

**Comment by lehkonev** [comment]
Oops, sorry. Fixed that.

Didn't think of checking the Writing Code section too...

**Comment by mrclay** [comment]
It's not sufficient to re-title the pull request, you must update the git commit and force push. This guide might help: https://elgg.org/pages/view/1123546/2-altering-your-github-pull-request

**Comment by lehkonev** [comment]
I managed to make a new commit, but if that doesn't help, I'll rather scrap this and do it like it's supposed to be done. (I thought I'd start easy and made the change and commit on github's editor. Not a good idea it seems...)

**Comment by mrclay** [comment]
You need to squash these commits to a single one. You can get things done from GitHub's editor, but you can't rewrite commits and other advanced stuff.

I made this setup guide to walk you through the whole process of submitting PRs for Elgg (or any other project): https://elgg.org/pages/view/1123473/preparing-to-develop-elgg-patches, then submit this change on 1.12: https://elgg.org/pages/view/1123538/elgg-bug-fixing-with-git

**Comment by lehkonev** [comment]
Okay, now I got it. Hopefully!

Thanks for bearing with me, mrclay.

**Comment by mrclay** [comment]
Thanks! The JS test is failing for an unrelated reason. When I get that working I'll merge this in.

**Pull request merged**
