### PR TITLE
Empty settings forms

### LINKED ISSUE #9704: No way to remove a usersettings view
I want to get rid of user settings for a certain plugin. If I overwrite the view with an empty string, it still renders the form without the body.
I quite dislike our user settings magic. We need to reconsider our approach.

### PR DESCRIPTION
**Pull request by hypeJunction**
Fixes #9704

### CODE REVIEW

**Comment by jdalsem** [comment]
i would rather have a way to prevent the form from being drawn completely...

I have various use cases of a user settings form that conditionally outputs content, so in some cases there is no form needed (and i also do not want to see the 'no_results' text).

**Comment by hypeJunction** [comment]
That's exactly the problem I am trying to solve. This prevents the form from being drawn if there are no inputs.
IMO, no results text makes sense for page views, i.e. we are still registering menu items as we can only check for `elgg_view_exists()`. Once user on the page, we need at least some feedback.

**Comment by jdalsem** [comment]
Agree... this is good. I thought you echoed no results for all user settings forms, but only for the full page, so this LGTM

**Comment by hypeJunction** [comment]
This will create a conflict when merging up. Whoever merges, please move the logic to the resource view from pages.

**Comment by mrclay** [comment]
We should not approve PRs this quickly, especially since this is not at all a pressing issue and has some BC implications.

We should make this fully BC by adding an option to the input/form form, and probably do this in 2.x.

**Pull request merged**
