### PR TITLE
fix(bookmarks): bookmark pin copies title into form

### LINKED ISSUE #8995: elgg.bookmarks.init doesn't add the title
`a.elgg-bookmark-page` is the wrong selector for the bookmark pin.

Not sure when this was broken

### PR DESCRIPTION
**Pull request by mrclay**
Fixes #8995

### CODE REVIEW

**Comment by hypeJunction** [comment]
Wohoo. Anniversary #9000

**Comment by hypeJunction** [comment]
LGTM, though it's really odd we have to do this client side.

**Comment by mrclay** [comment]
Feel free to rewrite it :)

**Comment by hypeJunction** [comment]
I don't think I have ever used the bookmarks plugin :)

**Pull request merged**
