### PR TITLE
feat(translations): download translations from transifex

### PR DESCRIPTION
**Pull request by hypeJunction**

### CODE REVIEW

**Comment by jdalsem** [comment]
this contains so much garbage... don't even know where to begin... 

picked a random install translation https://github.com/Elgg/Elgg/pull/11514/files#diff-d6adb2ef92bfb71b95d76cb5d0c99a7bR1... that is just english

did you push to transifex before the pull? If not, these translation files are based on a very outdated version of the originals as master has changed...

these do not exist in master... https://github.com/Elgg/Elgg/pull/11514/files#diff-3a94562779d2334d3b4b23493f5cc037R376 for example.. the file is not even a translation... just a copy of core

**Comment by jdalsem** [comment]
if you think about this a little more, maybe you see why i think it is a waste of our time

**Comment by hypeJunction** [comment]
I just pulled. I am only using Elgg in English, so if anyone cares, they can waste their time. I'd just strip all translations out of core. People can upload their translation plugins to community

**Comment by juho-jaakkola** [comment]
I believe that the outdated translations are caused by the fact that Elgg 3 does not yet have it's own project in Transifex. There's just these two:
 - https://www.transifex.com/elgg/elgg-core/dashboard/
 - https://www.transifex.com/elgg/elgg-core-2/dashboard/

So this PR in fact has the translations meant for Elgg 2 instead of Elgg 3.

**Comment by jdalsem** [comment]
true... but even than it has garbage as the language files do not contain the expected contents

**Comment by juho-jaakkola** [comment]
How can you know there will be garbage when we don't even have an own Transifex project for Elgg 3 yet?

**Comment by jdalsem** [comment]
because even if this PR contains a pull from 2.3 language files the issues i pointed out in this PR are the garbage... somehow various translation files just contain english language strings...

if we would use transifex than at least we need to update the translation in 2.3 first, than upmerge, than create new project for 3.x, than push etc...

**Comment by jdalsem** [comment]
question is also if we want to pull in unreviewed translations.... or want translations in that are only a few percent completed...

**Pull request closed without merging**
