### PR TITLE
chore(topbar): Simplify CSS for topbar menu

### PR DESCRIPTION
**Pull request by ewinslow**
I started out looking into #8733 but got sidetracked with cleaning up what felt like technical debt. It's no good if several different variables in distant files have to stay in sync just-so in order to work correctly. I think this is a more robust approach...

Before:
topbar-before

After:
topbar-after

### CODE REVIEW

**Comment by mrclay** [comment]
No visual change?

**Comment by ewinslow** [comment]
There is actually. Slight, but can post screenshots tonight.

**Comment by juho-jaakkola** [comment]
We agreed not to make non-BC changes to Aalborg's CSS. Let's fix Aalborg's possible shortcomings in the next official theme.

**Comment by ewinslow** [comment]
Can you explain how this is non-BC?

**Comment by ewinslow** [comment]
I don't think I have a good understanding of what backwards compatibility means yet with regard to css

**Comment by juho-jaakkola** [comment]
If someone's theme is overriding e.g. just ```elements/navigation.css``` but not ```aalborg_theme/css.php``` this PR breaks their topbar.

**Comment by juho-jaakkola** [comment]
This doesn't fix a bug nor introduce a new feature, so its not worth the risk.

**Comment by juho-jaakkola** [comment]
We decided the same for #8566

**Comment by ewinslow** [comment]
Very well. I will explore with these sorts of things on Elgg.org where bc doesn't matter. Then maybe we can create the next theme from those learnings.

**Comment by ewinslow** [comment]
Count this among the reasons we should organize CSS views in a fine-grained way by component.

**Pull request closed without merging**
