### PR TITLE
feature(discussions): added a site menu item for discussion/all

### LINKED ISSUE #8668: master: discussion needs a site menu item

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #8668

### CODE REVIEW

**Comment by mrclay** [comment]
Lgtm

**Comment by hypeJunction** [comment]
To keep the UX intact, do we need to automatically put this into `More`?

**Comment by jdalsem** [comment]
core prepares the menu and if there are more than 6 they will move to more... no need to configure that somewhere...

**Comment by jdalsem** [comment]
see https://github.com/Elgg/Elgg/blob/2.x/engine/lib/navigation.php#L375

**Comment by hypeJunction** [comment]
Ok. Was just something that popped to mind.

**Pull request merged**
