### PR TITLE
chore(entities): tracking online users works again

### LINKED ISSUE #11306: master: no online users
Hey at least they don't fatal.

### PR DESCRIPTION
**Pull request by mrclay**
Fixes #11306

### CODE REVIEW

**Comment by jdalsem** [comment]
hmmm i thought i intended last action to go to the entity table, not the metadata, need to take a better look why that did not work...

**Comment by mrclay** [comment]
It's never made sense that we had a separate last_action in the users_entity table. I'd rather rename this "last_request" for clarity. It gets changed with every session request. Let last_action really be the time an action occurred.

**Review by jdalsem — CHANGES_REQUESTED** [review]
i need to take a look why it is not working as it should at the moment

**Comment by jdalsem** [comment]
Replaced by #11457

**Comment by jdalsem** [comment]
More specific https://github.com/Elgg/Elgg/pull/11457/commits/ed9596fbef8bc8aafca2b8b91a8c9092537cd18d

**Pull request closed without merging**
