### PR TITLE
chore(views): reworked the account settings form

### PR DESCRIPTION
**Pull request by jdalsem**
BREAKING CHANGE:
Account settings forms and actions have been reworked. The
'usersettings:save' hook is no longer available.

Why the rework:
- no longer obscure user settings save hook (hard to see how it works)
- form body views moved in forms directory (where they belong)
- every section is now its own form
  - clear action file per section
  - can do required fields
  - performing an action is more clear (you know what you are submitting)
- sections are collapsed and toggle with the change link
- could easily do ajaxed submissions
# **Before:**

settings_default
# **After (collapsed):**

settings_collapsed_all
# **After (expanded a few sections):**

settings_expanded_some

_disclaimer: the form looks longer this way, but the before form only has 5 sections... after have 7_

### CODE REVIEW

**Comment by mrclay** [comment]
Hiding the current values is bad UX. Separate forms, actions, etc 👍

**Comment by mrclay** [comment]
Biggest problem: User is free to open multiple forms, but only one will be submitted.

**Comment by mrclay** [comment]
Loading the form in lightbox would solve the latter issue. No option but to submit the form or dismiss it.

**Comment by mrclay** [comment]
Strawman: each section is a button, some show the current value (email), some don't (change password). Clicking the button does one of two things: Either displays the form in a lightbox (does not submit via ajax) or replaces the button with the form and disables all other sections. Like widgets, each button has a view so plugins can extend/show what they want.

**Comment by mrclay** [comment]
I'll try one of these in a separate PR.

**Comment by mrclay** [comment]
Doubt I'm getting to this soon. Opened discussion about alternate approaches in #10671

**Comment by mrclay** [comment]
Take a look at #11530.

**Comment by jdalsem** [comment]
going to live with the current implementation

**Pull request closed without merging**
