### PR TITLE
fix(friends): Runtime error when a user is not logged in

### PR DESCRIPTION
**Pull request by SirbitoX**
runtime error of `_elgg_setup_collections_menu()` function in "friends" lib was fixed.

### CODE REVIEW

**Comment by mrclay** [comment]
I bet this problem exists on 1.11. If so that's where we need the fix. Also the commit msg should include the `Fixes #` declaration.

**Comment by mrclay** [comment]
Can you please resubmit this for 1.11?

**Comment by SirbitoX** [comment]
@mrclay I can't see any code on master branch either so I created PR on master branch. Am I wrong??

**Comment by SirbitoX** [comment]
@mrclay I resubmitted it by PR https://github.com/Elgg/Elgg/pull/8689

**Pull request closed without merging**
