### PR TITLE
chore(forms): update profile edit form to use new fields api

### PR DESCRIPTION
**Pull request by hypeJunction**
Updates profile edit form to use new fields API and views

### CODE REVIEW

**Comment by hypeJunction** [comment]
Looks like we need a way to extend an input view from within `elgg_view_input()`, so we could pass stuff like access input.

**Comment by mrclay** [comment]
Yeah, input/access is a mess. Thank me :)

**Comment by hypeJunction** [comment]
Should we add `footer` param and view to the field view? That will give another extension point.

**Comment by mrclay** [comment]
The "About me" label used to sit right on the textarea/CKeditor. In this there's a 1em gap (I assume made by the Edit HTML toggles). We probably don't want to introduce this in 2.1.

The new views also remove a bit of whitespace between the labels and inputs. Can we nudge the CSS for the new field elements to match the 2.0 look?

**Comment by hypeJunction** [comment]
```css
.elgg-field-label {
   margin-bottom: 3px;
}
.elgg-menu-longtext {
   margin-top: -17px;
}
```

**Comment by hypeJunction** [comment]
PR #9417

**Comment by hypeJunction** [comment]
It's pull request, the PR I referenced was to address your comment. This still need to be reviewed and pulled in.

**Comment by mrclay** [comment]
My mistake. LGTM!

**Comment by juho-jaakkola** [comment]
When writing commit messages, try to think them from the point of view of the people who read the changelog in a non-PR context.

Compare e.g. these two:
 - update profile edit form to use new fields api
 - profile editing form now uses the new fields api

IMO latter is more reader friendly when being read e.g. from the elgg.org blog.

**Pull request merged**
