### PR TITLE
fix(database): updated Phinx to prevent Symfony conflicts

### LINKED ISSUE #12805: Getting issue while install of Elgg 3.1.2
Hi,

i am getting issue while install of Elgg 3.1.2 on ``Database installation`` step ie. 3rd

img_20190829

cant proceed to next step
installation doesn't shown any error message just this message mentioned in image

### PR DESCRIPTION
**Pull request by jeabakker**
fixes #12805, #12806, #12809

### CODE REVIEW

**Comment by leboemori** [comment]
Ok. Its probably just me then.  I have however tried this installation  all from scratch and had someone else from another part of the world attempt it - still stuck on this page :( :

**Comment by jdalsem** [comment]
how did you try 'this installation'? did you do a composer install?

**Comment by leboemori** [comment]
Oh yes:
 24  php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
   25  php -r "if (hash_file('sha384', 'composer-setup.php') === 'a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
   26  php composer-setup.php
   27  php -r "unlink('composer-setup.php');"
   30  mv composer.phar /usr/bin/composer
   33  composer create-project elgg/starter-project:dev-master elgg
   38  composer install && composer install
   95  history|grep compose
Not sure what I'm doing wrong.  Somewhere online it is perceived as being an XML/Database issue with driver being referenced as "msqli" and not "msql".  I'm by no means an expert in these things but I've tried many things to avoid saying no to elgg installation/adoption!

**Comment by jeabakker** [comment]
the `elgg/starter-project` project by default installs stable (released) versions of Elgg.

In order to try it with a development build add the following after you created the project
`composer require --no-update elgg/elgg:3.1.x-dev`

**Pull request merged**
