### PR TITLE
fix(site_notifications): correctly position site_notifications menu

### LINKED ISSUE #6809: Consistency in elgg-image-block - site-notifications
Normally elgg-image-block consists of elgg-image (the icon) and elgg-body (everything else).

In site-notifications a third div has been added.
```HTML
<div class="elgg-image-block">
	<div class="elgg-image"> ... </div>
	<div class="elgg-image-alt"> ... </div>
	<div class="elgg-body"> ... </div>
</div>
```
There should be consistency.

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #6809

### CODE REVIEW

**Comment by mrclay** [comment]
I would rather this go in master since it will break custom styling of this element, right?

**Comment by jdalsem** [comment]
There is a possibility that it will break, but HTML is not part of the BC policy, and the impact of this change is relatively low. Currently the outputted HTML is even causing styling issue, like mentioned in the ticket #6809

**Comment by jdalsem** [comment]
How do we need to proceed with this? It is fixing a styling issue in a plugin.

**Comment by jdalsem** [comment]
bumping

**Comment by juho-jaakkola** [comment]
I'd say master. The menu has been like this since beginning of 1.9 so there is the risk that doing this change now would break someone's theme.

**Comment by jdalsem** [comment]
added a rebased PR

**Pull request closed without merging**
