### PR TITLE
fix(views): elgg_view_form now accepts class to be an array in form_vars

### PR DESCRIPTION
**Pull request by jdalsem**
input/form accepts an array of classes, elgg_view_form did not

### CODE REVIEW

**Comment by mrclay** [comment]
This accepts a new type for an argument, so needs to go in 2.x.

**Comment by jdalsem** [comment]
If considered a bug fix.. then there is nothing new. Documentation states it is passed to input/forms... that accepts class as an array

**Comment by mrclay** [comment]
If it never accepted an array then it was a documentation bug. A plugin built on 2.1.2 must work on 2.1.0.

**Comment by jdalsem** [comment]
will resubmit on 2.x

**Pull request closed without merging**
