### PR TITLE
feat(tests): migrate simpletests to phpunit

### PR DESCRIPTION
**Pull request by hypeJunction**
PHPUnit can now run integration tests with database connection.

Simpletest test cases have been moved to integration tests

### CODE REVIEW

**Comment by hypeJunction** [comment]
Obviously a bunch of tests are failing, but a head start if anyone cares to put in more time.

**Comment by mrclay** [comment]
Should we keep the DB tests in the same suite? I imagine wanting to run each separately.

**Comment by jdalsem** [comment]
🙄 wow

**Comment by hypeJunction** [comment]
> Should we keep the DB tests in the same suite? I imagine wanting to run each separately.

They are in separate suites

**Comment by hypeJunction** [comment]
@mrclay Bootstrapping an Elgg app has become way too complicated, with all the config madness, services etc. `_elgg_services()` with its static storage is quite bad. We can build an app without building service provider where we inject the app, seems a bit round the circle.

**Comment by hypeJunction** [comment]
Like WTF is the testing config coming from when running install plugins? https://travis-ci.org/Elgg/Elgg/jobs/263150724#L611
The state keeps being shoved around. There should be an easy way to just reset everything when the apps is booted or started or whatever.

**Comment by hypeJunction** [comment]
Same here: https://travis-ci.org/Elgg/Elgg/jobs/263150724#L723
I have reinstantiated the app, replaced the services, but the bloody config from previous test suite is still there.

**Comment by mrclay** [comment]
One change I made is that "app" is now stored in the SP. Could that be an issue?

**Comment by mrclay** [comment]
> There should be an easy way to just reset everything

Much agreed. Well, we could pull the plug and get rid of Application::$_instance and all the static methods but one has to be stowed away in elgg() at least.

**Comment by mrclay** [comment]
Last really big overhaul was in the middle of 2.x so we have more freedom now.

**Comment by hypeJunction** [comment]
I completely replace services, so it shouldn't matter. But in general we need to decide what is it that we want to persist and work from there. Having Application as entry point to build services and then injecting Application back in services doesn't seem straightforward. Resetting services should be easy. Perhaps _elgg_servivrs should just read services from Application instance that will keep them public static.

**Comment by mrclay** [comment]
Worth a shot.

**Comment by hypeJunction** [comment]
Another example: you can't call _elgg_services() until you load an application, for which you need factory where you inject SP returned by _elgg_services() or instantiate be SP where you would inject the app before it's even loaded... It's become too convoluted.

**Comment by hypeJunction** [comment]
> but one has to be stowed away in elgg() at least.
I don't see why elgg() needs Application at all. Just create a new class that will have a magic _get and be done with it.

**Comment by mrclay** [comment]
> I don't see why elgg() needs Application at all. Just create a new class that will have a magic `__get` and be done with it.

There's no way to have global function APIs without a global/static reference. Maybe I'm not getting what you mean.

**Comment by hypeJunction** [comment]
Add Application::services() as a replacement for _elgg_services() (latter can just call former for BC). Add Di\PublicServiceProvider with _get method that will just call Application::services()->$method if service is public or emit error.

**Comment by mrclay** [comment]
See https://github.com/Elgg/Elgg/pull/11150/files

**Comment by hypeJunction** [comment]
I really don't know how many of these simple tests were passing. We should make this a priority to finish migrating everything to phpunit. I don't trust simpletests anymore after digging deeper into it.

**Comment by hypeJunction** [comment]
All right, I can't see this anymore. Leaving it here, feel free to finish it.

**Comment by mrclay** [comment]
Yeah, I just looked at the build log, take a long break. Are there any low-hanging fruit/obvious next steps here?

**Comment by hypeJunction** [comment]
- [ ] Go through failing integration tests (some are failing due to bad mapping of assertions, some really need work, because they are written badly)
- [ ] Reset the App for the simpletest suite
- [ ] See what can be done about performance, integration tests are slow, but I guess that's expectable

**Comment by hypeJunction** [comment]
Thinking out loud: we should leave simpletests in until before the release, they only cost us a few seconds on Travis builds, but might help catch issues with this refactor.
So the strategy would be to:
- clean up and break down seeding even more, possibly add tests
- add permissions change as a separate PR
- look into the annotation bug (no entity triggers 'annotate', null hook. I don't know exactly what that does and not sure if we even have tests for that (@mrclay could you grab this?)
- add integration test skeleton
- add simpletest migration classes

**Pull request closed without merging**
