### PR TITLE
Fix installer, clean up plugin api, speed up tests

### PR DESCRIPTION
**Pull request by hypeJunction**

### CODE REVIEW

**Comment by jdalsem** [comment]
Looks good.. have not done an in depth review as this is way to big... please try to provide smaller PR's so it is easier to review. Anything specific we need to take a look at?

**Comment by hypeJunction** [comment]
It's not all that much. Most of it is tests.

**Comment by jdalsem** [comment]
Did you try a manual fresh install?

**Comment by hypeJunction** [comment]
I did when I worked on the installer. Given it wasn't working before this I don't know how it can get worse

**Comment by jdalsem** [comment]
indeed... was just wondering if you did

**Comment by hypeJunction** [comment]
The whole point of adding automated tests is not h

**Comment by hypeJunction** [comment]
Oops. Accidentally closed

**Comment by jdalsem** [comment]
no i merged

**Pull request merged**
