### PR TITLE
chore(assets): Check in assets that don't have bower repos

### LINKED ISSUE #8420: Ditch custom repositories in favor of actual bower/npm packages
This custom repositories config needs to be copied to `elgg/starter-project` in order to install successfully. It'd be better just to drop them in favor of equivalent newer packages that are already registered with bower/npm.

```json
{
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "bower-asset/sprintf",
                "version": "0.7.0",
                "dist": {
                    "type": "zip",
                    "url": "https://github.com/alexei/sprintf.js/archive/v0.7.zip"
                }
            }
        },
        {
            "type": "package",
            "package": {
                "name": "bower-asset/jquery-imgareaselect",
                "version": "0.9.10",
                "dist": {
                    "type": "zip",
                    "url": "https://github.com/odyniec/imgareaselect/archive/v0.9.10.zip"
                }
            }
        },
        {
            "type": "package",
            "package": {
                "name": "bower-asset/jquery-ui-extensions",
                "version": "dev-master",
                "dist": {
                    "type": "zip",
                    "url": "https://github.com/scottgonzalez/jquery-ui-extensions/archive/fb7fd7df3d70e0288394f07bfe78262b548c30d6.zip"
                }
            }
        },
        {
            "type": "package",
            "package": {
                "name": "bower-asset/jquery-jeditable",
                "version": "1.7.3",
                "dist": {
                    "type": "zip",
                    "url": "https://github.com/tuupola/jquery_jeditable/archive/1.7.3.zip"
                }
            }
        }
    ],
}
```

### PR DESCRIPTION
**Pull request by ewinslow**
The whole point of going through composer-asset-plugin is to get automatic updates,
but that's not possible with these 4 libraries because they aren't available on
bower at all, so we get no benefit and only complications from depending on them
via bower-asset/\* repos.

This is also much easier than finding a replacement library and updating the code
to use the new library.

Fixes #8420

### CODE REVIEW

**Comment by mrclay** [comment]
`vsprintf` doesn't seem to be working. Right path in views.php?

**Comment by ewinslow** [comment]
Might be the wrong version of the sprintf library...

**Comment by ewinslow** [comment]
Updated the `karma.conf.js` and `elgg.js.php`

**Comment by mrclay** [comment]
LGTM

**Pull request merged**
