### PR TITLE
3.x

### PR DESCRIPTION
**Pull request by AbdulazizSobh**
Sync notifications and messages without refreshing the page
As the messages and notifications do not appear until the page is reloaded
This will make the site more responsive

### CODE REVIEW

**Comment by jeabakker** [comment]
I have no idea what you wanted to do?

Where you trying to report an issue, or make a Pull Request from your own branch?

**Comment by AbdulazizSobh** [comment]
I mean, if I receive a message or a notification, whoever does not reach me when the page is updated

**Comment by AbdulazizSobh** [comment]
In other words, notifications do not appear to members until the page is reloaded
It is not synced with the site

**Comment by jeabakker** [comment]
Then please report it as an issue here https://github.com/Elgg/Elgg/issues

**Pull request closed without merging**
