### PR TITLE
chore(css): more useful helpers

### PR DESCRIPTION
**Pull request by RiverVanRain**

### CODE REVIEW

**Comment by jdalsem** [comment]
For what usecases do you want these helpers? Is this a specific set that you see in use with other frameworks?

**Comment by RiverVanRain** [comment]
They are not needed when I use Bootstrap. 
But I use them all the time if I create custom themes without 3rd-party frameworks.
Existing helpers in Elgg are not enough, IMO.

**Comment by jdalsem** [comment]
There is an error in this PR. You are writing the CSS in a PHP section of this file.

**Comment by RiverVanRain** [comment]
Let's close this PR. I may come back to it later.

**Pull request closed without merging**
