### PR TITLE
chore(pages): replaced pages images with FontAwesome page icons

### LINKED ISSUE #4967: Pages plugin doesn't have tiny size icon (Trac #4967)
_Original ticket http://trac.elgg.org/ticket/4967 on 42970390-12-18 by brettp, assigned to unknown._

Elgg version: 1.8

See #3907

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #4967 
# Before

pages_before
# After

pages_after

### CODE REVIEW

**Review by hypeJunction — COMMENTED** [review]
I don't like mixing markup with images. I's prefer consistency in how we overwrite icon URLs. I prefer @mrclay's suggestion of using owner icon.

**Comment by mrclay** [comment]
We currently visually differentiate subpages in entity lists (with a different icon). Is this important?

**Comment by mrclay** [comment]
Maybe we start with replacing current icons with bitmap versions from the font-awesome glyphs? That seems a big immediate improvement and uncontroversial.

**Comment by hypeJunction** [comment]
Leave the icons to me. I have started on a PR to make using fallback easier.

**Comment by hypeJunction** [comment]
Do we really need icons for pages?

**Comment by mrclay** [comment]
I'm also thinking get rid of page icons altogether, and try to make it clearer when there are subpages.

**Comment by jdalsem** [comment]
Going to do a pr to remove the icons and just use owner icons instead.. like the rest of Elgg does :)

**Pull request closed without merging**
