### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by orions-stars**
This is my first try at Github, so please tell me what I have missed. I only wanted to make a pull request for just the first commit on my list as a trial (thanks Ismayil), but cannot find how to make the partial pull request. (mostly because I made some mistakes and have some useless commits here.)

I did read the Elgg comment standards and tried to follow those.

### CODE REVIEW

**Comment by mrclay** [comment]
These look great, though I'd like you to squash these to 1 commit. It's not necessary to put a ton of detail about docs changes in the commit message. A simple summary is fine.

**Comment by mrclay** [comment]
Reason to squash is that these would be noisy when rendered in the CHANGELOG.

**Comment by orions-stars** [comment]
Sounds good. I will look into how to squash these.

Thank you!

**Comment by hypeJunction** [comment]
You can do a soft reset and recommit.

```sh
git remote add upstream https://github.com/elgg/elgg.git

git fetch upstream

git reset --soft upstream/2.0 # or whatever branch you forked

git commit -a -m 'chore(docs): update docs to reflect API changes'

```

**Comment by hypeJunction** [comment]
Or you can squash using vim.

```sh

# setup upstream if not set
git fetch upstream
git rebase -i upstream/2.0 

# use vim to reword first commit and squash or force up the rest

git push --force origin branch-name

```

**Pull request closed without merging**
