### PR TITLE
perf(engine): only update attributes/metadata if value is changed

### LINKED ISSUE #8043: Metadata causes a lot of db writes
Calling ```$entity->foo = 'bar'``` currently triggers this:
 1. [That particular metadata gets removed regardless if it has changed
at all](https://github.com/Elgg/Elgg/blob/1.10/engine/classes/ElggEntity.php#L401-L415)
 2. [The metadata gets written again to the database](https://github.com/Elgg/Elgg/blob/1.10/engine/classes/ElggEntity.php#L425-L430)

Is there a reason why we don't:
 1. Compare the value to existing db value and act only if it has changed
 2. Update the existing row instead of writing a new one

Something related to caches or ACLs perhaps?

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #8043 

Very easy fix to save a lot of dbcalls when editing (went from 118 to 38 on blog edit if nothing was changed). Could not think of anything wrong with this approach.

Sry about the trailing spaces changes, but i believe that was allowed in master now...

### CODE REVIEW

**Comment by mrclay** [comment]
Could go in 1.x

**Comment by jdalsem** [comment]
any objections?

**Comment by ewinslow** [comment]
Yup, 1.x it!

**Comment by jdalsem** [comment]
Redid it on 1.x #8596

**Pull request closed without merging**
