### PR TITLE
docs(install): bootstrapping Elgg in Laravel Homestead

### PR DESCRIPTION
**Pull request by hypeJunction**
Provides detailed instructions how to set up Elgg in the Laravel Homestead
Vagrant Box

### CODE REVIEW

**Comment by hypeJunction** [comment]
Also see https://github.com/laravel/homestead/pull/616

**Comment by jdalsem** [comment]
Do we need to wait for the homestead PR before merging this doc?

**Comment by hypeJunction** [comment]
No, the code is referenced in the doc. We can update the doc if/when homestead merges it.

**Comment by hypeJunction** [comment]
But this probably should go into 2.3 docs. I think @mrclay rewired routing to use Symfony request, so we don't need those .htaccess/nginx rewrite rules anymore

**Comment by jdalsem** [comment]
sphinx not building correctly

**Comment by hypeJunction** [comment]
I will look into it next week. Let it sit, maybe someone can do a run through to see if everything works for them.

**Comment by mrclay** [comment]
> we don't need those .htaccess/nginx rewrite rules

True but we probably want the [caching section](https://github.com/Elgg/Elgg/pull/10960/files#diff-2c7d4519a99944a2bb46255743c92340R68).

**Comment by hypeJunction** [comment]
> True but we probably want the caching section.

That is only master for now?

**Comment by hypeJunction** [comment]
Replaced by #11038

**Pull request closed without merging**
