### PR TITLE
feature(file): file search menu is now displayed in the sidebar when displaying a file

### PR DESCRIPTION
**Pull request by socialatm**
the file search sidebar does not appear in full view. This adds it in.

### CODE REVIEW

**Comment by beck24** [comment]
Why are there 9 seemingly unrelated commits listed for this?

**Comment by twentyfiveautumn** [comment]
I'm making a mess but my attitude is really good. I don't think I broke anything.

**Comment by twentyfiveautumn** [comment]
I'm thinking I should have done pull before rebase but I'm going to use the new guy excuse.

**Comment by hypeJunction** [comment]
You need to rebase.
```
git rebase upstream/1.x
git push --force origin/1.x
```

**Comment by hypeJunction** [comment]
Ideally, you should create a new branch for each issue. In this case you can:

```sh
git chekout -b filebranch
git fetch upstream
git reset --hard upstream/1.x
git cherry-pick 4950324
git push origin filebranch
```

and resubmit the PR from the filebranch.

That way you can keep your 1.x up to date with upstream 1.x.

**Comment by twentyfiveautumn** [comment]
Thanks @hypeJunction  I'll give it a shot

**Comment by hypeJunction** [comment]
So you understand, 4950324 is the SHA of your commit. You can see it above in the list.

**Comment by twentyfiveautumn** [comment]
Yes, I get that part.

**Comment by twentyfiveautumn** [comment]
sorry for the mess. I'll close this and try again

**Pull request closed without merging**
