### PR TITLE
Disabled buttons

### PR DESCRIPTION
**Pull request by jdalsem**
Now all buttons have a styled disabled state and buttons (not anchors) can get the disabled state class if they are disabled with the `disabled` attribute

### CODE REVIEW

**Comment by mrclay** [comment]
Does the admin CSS need this?

**Comment by jdalsem** [comment]
yep... and maintenance also i guess..., but maybe we can try to reuse the buttons.css view in the admin/maintenance as a separate task as there is more button related stuff missing in those views...

**Comment by mrclay** [comment]
The commit says "all the buttons", so the changes should affect *all* the buttons, right?

> more button related stuff missing in those views

I get that they're out of sync, but let's not make them even *more* out of sync.

**Comment by jdalsem** [comment]
> I get that they're out of sync, but let's not make them even more out of sync.

agree... but adding a lot of boilerplate and then removing them in another ticket feels a bit awkward

**Comment by hypeJunction** [comment]
I don't think it would be boilerplate given that styles are different in admin interface.

**Comment by jdalsem** [comment]
k, i will add the disabled classes and attribute css to admin and maintenance css also

**Comment by jdalsem** [comment]
Updated so admin css also has correct disabled state button css. Maintenance css did not have any css related to disabled buttons, so i did not add it to that css file.

**Comment by mrclay** [comment]
Cool. Why not merge these commits and rebase for 2.2? I think it's ready.

**Comment by jdalsem** [comment]
This can still be merged for 2.x amirite?

**Comment by hypeJunction** [comment]
Either 2.2 or 2.x is fine by me

**Comment by jdalsem** [comment]
cannot go into 2.2 as the commit messages are 'feature'

**Comment by hypeJunction** [comment]
Then LGTM

**Pull request merged**
