### PR TITLE
feat(groups): add hooks to alter edit form fields

### PR DESCRIPTION
**Pull request by hypeJunction**
Adds hooks to filter fields displayed on the profile, tools and access
parts of the group edit form

### CODE REVIEW

**Comment by jdalsem** [comment]
i do not get why we would need this... we already have hooks to influence fields and tools...

**Comment by hypeJunction** [comment]
The fields hooks are dumb, they only support key value pairs. These are helpful if you want to hide a specific field, e.g. forcing all groups to be private etc.

**Comment by mrclay** [comment]
Seems reasonable.

**Comment by hypeJunction** [comment]
I think we should be using whatever ways we have to help plugins deal with forms without touching views. Overriding views is a huge pain in the ass, plugins keep fighting who gets to override the view first, and it's impossible to keep track of them during upgrade. But whatever.

**Pull request closed without merging**
