### PR TITLE
WIP feat(theme): integrate Bootstrap and rewrite core theme and components

### PR DESCRIPTION
**Pull request by hypeJunction**
wip

### CODE REVIEW

**Comment by hypeJunction** [comment]
Just getting started on this. It will take some time, but I think it's worth the effort and will make theming a lot easier in the long run.

**Comment by jdalsem** [comment]
Nice. Keep up the good work!

**Comment by jdalsem** [comment]
Are you going for a full width or a fixed design? I would like to see the default design assume 720p (1280px) is default (if going for a fixed (max) width design).

**Comment by hypeJunction** [comment]
I am going to use `.container` class, but moving it inside inividual views, so themes can go full width on certain elements if they want to.

**Comment by hypeJunction** [comment]
wip2

**Comment by hypeJunction** [comment]
wip3

**Comment by hypeJunction** [comment]
wip5

**Comment by hypeJunction** [comment]
wip6

**Comment by jdalsem** [comment]
i think user profile should also be above the widget columns, just as the groups have... user info tends to grow big and it feels a bit cramped on the side

**Comment by jdalsem** [comment]
the dropdown entity menu is perfect, but i do not like the cog next to it. Just the dropdown icon is enough i think.

**Comment by hypeJunction** [comment]
User profile details is above widgets. The screenshot is a bit outdated. Cog was just a temp thing.
I ma not sure about the strategy here. This is massive and I am not sure how we are going to merge. I will try to o extract some of it into smaller PRs.
Also, I think we should forgo using utility classes, like display, margins, paddings. They are convenient but will make it way harder to restyle

**Comment by jdalsem** [comment]
I think we can do a massive PR... we need to accept there will be some rework afterwards and the fact that you might have missed some things... i do not want this to cause you too much trouble to get in.

When you are almost done i can make some time for a thorough review, so we can try and wrap this up very soon

**Comment by hypeJunction** [comment]
Ok. Sounds good.

**Comment by hypeJunction** [comment]
I've seemed to have turned this into a project of a lifetime. I am nuking most of the boilerplate in resource views in favor of ``elgg_view_profile_page()`` and ``elgg_view_listing_page()``, so look out for all the changes when you review. Will be adding ``elgg_view_form_page()``, and we can say good bye to dealing with stupid breadcrumbs and all the hassle that comes with resource views.

All of the menus are changing as well. Full/profile entity views will now always have a meta block, which is handy to put all the change like Status: Draft, and will be easy to extend via menu hooks.

Due to page handling, we now have a proper entity in title/page menus, as well as head tags. So, I will be moving out most of the non-essential stuff out of the title menu (and some page menu) items into the entity menu. 

Listing page now comes with a filter, and I have converted a river dropdown into a proper menu. Will be doing the same for file type filter, and list type toggle will be moved from extras menu to listing menu.

**Comment by hypeJunction** [comment]
wip1
wip2
wip3
wip4

**Comment by jdalsem** [comment]
> I've seemed to have turned this into a project of a lifetime.

Sounds more like cleaning out your closet... Hmmm maybe in my case that would be a project of a lifetime 😄

**Comment by hypeJunction** [comment]
Ok, I can't do this anymore. Taking a break for a few weeks. Feel free to start reviewing and adding some upgrade docs along the way. 
I have updated how likes and comments appear/function.
Files now show in a gallery view by default.
And did some more nitpicking here and there.

wip1
wip2
wip3
wip4

**Comment by hypeJunction** [comment]
You know what, fuck it. I don't want to spend any more time on this, ever. Elgg is just hopeless.

**Comment by mrclay** [comment]
Should I bother trying to resurrect #10684?

**Pull request closed without merging**
