### PR TITLE
fix(search): hooks no longer reset group subtype

### PR DESCRIPTION
**Pull request by hypeJunction**
Registering custom group subtypes with elgg_register_entity_type()
would result in the same results appearing for all group subtypes. This
allows groups subtypes to be searched individually.

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
Is it still possible to search all groups regardless if they have a subtype or not?

**Comment by hypeJunction** [comment]
Yes, it's a normal ege* call

**Comment by juho-jaakkola** [comment]
I'm asking because this would do the exact opposite of 0056e5cfe5c588907b1d7e2b7c050176bb5e3afa. Apparently that problem doesn't exists anymore?

**Comment by hypeJunction** [comment]
@brettp Do you remember why this was added?

**Comment by juho-jaakkola** [comment]
The original problem was that back in the day `get_entities()` took multiple parameters instead of an array of options. If no subtype was passed, the default was an empty string (`$subtype = ""`) meaning "Entities without a custom subtype".

Nowadays that we take an array of options, and merge them to the defaults (`'subtypes' => ELGG_ENTITIES_ANY_VALUE`), this problem doesn't exist anymore.

So yes, I believe this PR is fine. Also we should most likely remove that line also from user search.

**Comment by mrclay** [comment]
These commit both handle the same issue, can you squash them? LGTM

**Comment by hypeJunction** [comment]
Squashed and updated commit message

**Comment by mrclay** [comment]
LGTM

**Pull request merged**
