### PR TITLE
fix(file): re-added cannotload language string for file plugin

### PR DESCRIPTION
**Pull request by iionly**
Fixes https://github.com/Elgg/Elgg/issues/9013.

### CODE REVIEW

**Comment by mrclay** [comment]
Looks fine. I guess it's complaining about the commit summary

**Comment by jdalsem** [comment]
Uh do we want this merged against 1.9? I think you need 1.12. 1.9 is no longer supported.

**Comment by iionly** [comment]
I've made the PR against 1.9 because the string got lost in 1.9. But for whatever reason the checks still fail even after renaming the commit message. I can make a new try against 1.12 if wanted - tomorrow then though.

**Comment by juho-jaakkola** [comment]
Transifex fetches translation strings for Elgg 1.* specifically from the `1.12` branch anyway, so there aren't really any benefits in adding it back to `1.9` branch.

**Comment by iionly** [comment]
@juho-jaakkola are the en.php files fetched from Transifex, too?

**Comment by iionly** [comment]
Replaced by https://github.com/Elgg/Elgg/pull/9682.

**Comment by juho-jaakkola** [comment]
No, `en.php` is not fetched. But I meant that we're not making a Elgg `1.9.x` releases anymore, and additionally Transifex does not fetch anything from `1.9` branch, so there's no use for the string there.

**Pull request closed without merging**
