### PR TITLE
Fixes typos in menu guide

### PR DESCRIPTION
**Pull request by knezmilos13**

### CODE REVIEW

**Comment by hypeJunction** [comment]
Thanks. This looks good. For small changes like this that are semantically connected you can just make one commit in the future.

**Comment by hypeJunction** [comment]
Oh, just noticed that you made a PR against master. This should go into 1.11

**Comment by knezmilos13** [comment]
Should I redo this PR then? What is the gerenal rule then, so I don't make the same mistake in the future?

**Comment by hypeJunction** [comment]
That would be great.
The general rule is that bugfixes/chores go into the current active branch (1.11), new features go into (1.x), breaking changes go into the next major release (2.0)

**Pull request closed without merging**
