### PR TITLE
fix(uservalidationbyemail): only forward to emailsent page if email sent

### LINKED ISSUE #7788: Uservalidation by email should only forward on register succes
The function uservalidationbyemail_after_registration_url always forwards (also if register fails and you are forwarded back to the register form). It should probably do the same check as in the email_sent page: 
```
$email = $session->get('emailsent', '');
if (!$email) {
	forward('');
}
```

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #7788

### CODE REVIEW

**Comment by jdalsem** [comment]
Anybody with feedback? @Elgg/owners

**Comment by ewinslow** [comment]
I believe this is WAI for "security"? I.e. we don't want to reveal whether or not the email is in the database.

**Comment by jdalsem** [comment]
No this is something else. This is the forward url hook after a registration of a new user. If that registration fails this hook will still redirect you to home instead of go back to the register form.

**Comment by juho-jaakkola** [comment]
LGTM

**Pull request merged**
