### PR TITLE
chore(phpcs): update to latest PHP CodeSniffer

### PR DESCRIPTION
**Pull request by hypeJunction**

### CODE REVIEW

**Comment by hypeJunction** [comment]
It's a mess, and I am not going to spend anymore time on it than I already have.

**Comment by mrclay** [comment]
Hopefully https://github.com/hypeJunction/Elgg/pull/23 will help.

**Comment by hypeJunction** [comment]
It's impossible. I am giving up. If anyone feels adventurous and has a few days to spare, go ahead.

**Comment by jdalsem** [comment]
what was your plan?

**Comment by jdalsem** [comment]
updating to latest codesniffer and then fix all issues that arise?

**Comment by hypeJunction** [comment]
We can not longer run composer update or install because security advisories are conflicting with older versions of phpcs. We need to either 1) rewrite all the sniffs, 2) switch the standards and fix the issues, 3) drop security advisories until someone has time to write the sniffs from scratch. My attempts to update the sniffs are resulting in too many changes, like arrays as arguments span over into new line etc. Too much work, I can't be bothered any more, I have already spend 12 hours on this.

**Comment by mrclay** [comment]
Main issue is CS has to convert our tabs to spaces to process, so I'm converting our custom sniffs to handle tabs that have been converted to spaces. Reopening to keep it on our radar.

**Comment by hypeJunction** [comment]
See my merge to master PR. It handles tabs.

**Pull request closed without merging**
