### PR TITLE
fix(core): increase column size of datalist table as prerequisite for Elgg 1.8 upgrade

### PR DESCRIPTION
**Pull request by iionly**
Makeshift for https://github.com/Elgg/Elgg/issues/6814

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
The name of the file should be the date when the upgrade was added. So something like 2015030200.

@Elgg/owners We're not going to merge 1.7 up to 1.8 anymore at this point, so I guess it doesn't really matter how the file has been named?

**Comment by hypeJunction** [comment]
I don't like the commit message. It should probably say what's fixed. Current message is a but too broad and too vague

**Comment by iionly** [comment]
@juho: Maybe I should have commented on the filename. I had looked into the upgrade code of Elgg 1.7 and (maybe I'm wrong..) it looks to me that the naming of upgrade scripts was different back then for Elgg 1.7 (especially Elgg version = latest upgrade script filename/date). Also, the upgrade script added last before (https://github.com/Elgg/Elgg/commit/3e373809c7344d13671b322883c2824c3ed7b964) did also not follow the filename = current date rule but just incremented the latest script already available. That's what I have done then, too.

Would "fix(core): datalist grow up as prerequisite for a future upgrade to Elgg 1.8" be a better commit message? Then point is that the only point of this commit is to fix the current upgrade problem from 1.7 to 1.8. For usage of Elgg 1.7 itself this change has no benefit (or harm).

**Comment by juho-jaakkola** [comment]
I've got to say I'm not familiar with the 1.7 naming conventions. So I'm fine with the current filename.

Yes, something like that would be better commit message. Maybe add a bit more details:
> fix(core): increase column size of datalist table as prerequisite for Elgg 1.8 upgrade

**Comment by iionly** [comment]
Message changed.

**Comment by juho-jaakkola** [comment]
LGTM

**Comment by juho-jaakkola** [comment]
BTW, what will MySQL do when you attempt to update a table that already matches the result of the ALTER command?

**Comment by iionly** [comment]
So far I had no issues whatsoever when upgrading to Elgg 1.8 afterwards. The increase needs to be done before you start with the Elgg 1.8 upgrade or the upgrade from 1.7 will not work at all. Of course, the better solution would be to fix the problem within the 1.8 upgrade sequence itself but nobody seems interested in doing it.

**Comment by ewinslow** [comment]
Is this ready to be pulled in? Anything else blocking it?

Seems straightforward enough. Will we need to tag a 1.7.23 release?

**Comment by juho-jaakkola** [comment]
This seems ready. Needs the 1.7.23 tag and I believe also a zip package.

Might be best to make a blog post to remind admins that they should update to latest 1.7.x before upgrading to 1.8.

**Comment by mrclay** [comment]
I think we really need a message in the upgrade RST docs to close #6814. Additional blog post is fine.

**Comment by iionly** [comment]
Sorry but I'm not sure how to proceed.

Any doc upgrades would have to be made to the Elgg 1.8 and/or 1.9 branch than the 1.7 branch (where this PR here has to be made to).

I also don't know where to add any message and what the message should be.

**Comment by juho-jaakkola** [comment]
I guess the docs would have to go to 1.9 branch of this page: http://learn.elgg.org/en/1.10/admin/upgrading.html#from-1-7-to-1-8

That way they would get included in the oldest version of the new docs.

**Comment by juho-jaakkola** [comment]
I believe this is fine to merge. Any possible docs need to be added to another branch anyway.

**Pull request merged**
