### PR TITLE
chore(css): increase z-index of site menu class from 1 to 50

### PR DESCRIPTION
**Pull request by iionly**
- [x] mark as breaking change
- [x] update docs/guides/upgrading.rst

### CODE REVIEW

**Comment by beck24** [comment]
I think it's failing on the commit message.

Try ```chore(css): increase z-index of site menu class from 1 to 50```

**Comment by iionly** [comment]
Message changed.

**Comment by beck24** [comment]
Awesome, LGTM

**Comment by mrclay** [comment]
As a breaking change it needs explanation in the plugin upgrade guide and commit message. For example: https://github.com/Elgg/Elgg/commit/ba0c12f227e0d2df64722d364af34b6c00e3bfbb

**Comment by mrclay** [comment]
Where does 50 come from?

**Comment by mrclay** [comment]
Can you please explain how we can test that this change fixes something? A screenshot comparison would be helpful.

**Comment by iionly** [comment]
I've chosen the z-index value of 50 because it's in the middle of the old value (1) and the next higher z-index value used by Elgg core (100 in login-dropdown).

With z-index of 1 it looks like this (example with Event Calendar plugin that uses several z-index values):
site-more-menu-z-index-1

and with the increased z-index of 50 it looks like:
site-more-menu-z-index-50

**Comment by beck24** [comment]
So the issue is that there is no room for intermediate z-index from content, any content using any kind of z-index will show above the more dropdown.  This can be fixed in a plugin pretty easily, but if any plugin using any z-index needs to overwrite core css to make it work that's a minor bug.

**Comment by mrclay** [comment]
OK makes good sense. PR needs updating so we can get this in.

**Comment by iionly** [comment]
Hope I got the changes right.

**Comment by mrclay** [comment]
Thanks!

**Pull request merged**
