### PR TITLE
fix(router): current_page_url() now respects route:rewrite hook values

### PR DESCRIPTION
**Pull request by hypeJunction**
When routes are rewritten with route:rewrite hook they should be
considered the current page URL segments

### CODE REVIEW

**Comment by mrclay** [comment]
It depends on whether you're using this function for creating URLs or internal routing.

Let's say I rewrite the external URL `/my-title-1234/` to the internal `/page/view/1234`. When I add `?offset=10` to the URL for the next set of comments, I don't want users to end up at the internal URLs.

**Comment by mrclay** [comment]
So the current function returns the "external" URL. We could add the argument `$internal = false`.

**Comment by hypeJunction** [comment]
I just need the page owner API to use internal URLs. There are probably other places where we would want internal URLs. Strawman: add elgg_get_current_route() and use it where we sniff URL segments.

**Comment by mrclay** [comment]
`elgg_get_current_route()` returns `"pages/view/123"`? 👍

**Comment by mrclay** [comment]
Can we instead figure out how this should fit into #10042?

**Comment by hypeJunction** [comment]
Replaced by #10362

**Pull request closed without merging**
