### PR TITLE
fix(ui): prevent button jumping on widget add panel toggle

### LINKED ISSUE #7705: Add widget button on profile and dashboard jumps when clicked

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #7705

### CODE REVIEW

**Comment by PerJensen** [comment]
This does not fix the bug added by the toggle change. It's compensatingm, so all themes must adjust their CSS.

**Comment by jdalsem** [comment]
The cause is actually this line of css https://github.com/Elgg/Elgg/blob/1.11/views/default/css/elements/core.php#L114. Admin css does not have this issue. Toggle jumping is not happening there (check it yourself at the admin dashboard).

But i think i can not fix it by removing the `.elgg-button` in the css/elements/core file as that will be a more breaking change. That is why i made this work around.

**Comment by PerJensen** [comment]
Well, the CSS line was there already when the toggle was changed :) As you mention:

>the small jump is related to the .toggle() jquery function that toggles hidden elements by setting >display to inline instead of inline-block
>

**Comment by ewinslow** [comment]
What is the status of this PR? Can we pull it in or no? @PerJensen latest comment is not clear.

**Comment by jdalsem** [comment]
i still think this could go in. i agree with @PerJensen that it is a workaround, but it needs to do for now, so i say merge

**Pull request merged**
