### PR TITLE
fix(views): do not drop elgg-button-submit class when using input/submit

### PR DESCRIPTION
**Pull request by jdalsem**
Also the input/button and input/submit views can now handle
$vars['class'] to be an array.

### CODE REVIEW

**Comment by mrclay** [comment]
The change to input/submit breaks BC. You can argue letting the dev replace that class was a mistake but the view `@uses` even called that out as a feature.

**Comment by jdalsem** [comment]
you are correct. Would you agree with the change if i rebased to master?

**Comment by mrclay** [comment]
Sure. You could put just the input/button changes in 1.x if you wanted.

**Comment by jdalsem** [comment]
not that much in a hurry. having to add `elgg-button-submit` everytime i add a custom class to `input/submit` is the most annoying

**Pull request closed without merging**
