### PR TITLE
3.x fixes

### PR DESCRIPTION
**Pull request by jdalsem**

### CODE REVIEW

**Review by jeabakker — APPROVED** [review]
if all tests pass....

**Review by hypeJunction — COMMENTED** [review]
I don't see a point here with deprecating external file loading. The core is still using it so there is an obvious need for it. Also I would expect elgg_require_css() to work with Ajax, similar tojs, but I don't see any related logic

**Comment by jdalsem** [comment]
> I don't see a point here with deprecating external file loading.

i am not deprecating external file loading, only deprecating the elgg_register_css and elgg_register_js logic. This way plugin devs are encouraged to reconsider how they include their resources.



> Also I would expect elgg_require_css() to work with Ajax, similar tojs, but I don't see any related logic

At the moment we have no clear idea on how to load the css dependencies via js (in a similar way as requirejs), but push people to use `elgg_require_css` makes the transition to a solution in the future easier.

**Comment by hypeJunction** [comment]
> At the moment we have no clear idea on how to load the css dependencies via js (in a similar way as requirejs), but pushing people to use elgg_require_css makes the transition to a solution in the future easier.

Don't entirely agree, but ok.

**Pull request merged**
