### PR TITLE
Add toggle event and auto-focus river comment input (jQuery version)

### PR DESCRIPTION
**Pull request by mrclay**
(this is the jQuery event version of #9159)

feature(js): elgg.ui.toggle now triggers jQuery event

After a toggle is activated, an event is fired on the toggle element. Listeners receive a jQuery-wrapped reference to the target element(s).

fix(river): opening comment form auto-focuses input

The button is also blurred when the form is hidden.

The river filter now uses event delegation.

### CODE REVIEW

**Comment by mrclay** [comment]
@hypeJunction @juho-jaakkola I'm leaning towards this $ version. Any prefs here?

**Comment by hypeJunction** [comment]
@mrclay I don't understand the question

**Comment by mrclay** [comment]
I have 2 PRs that do the same thing. This and #9159 (which uses elgg.trigger_hook). I'm leaning towards the $.trigger version.

**Comment by hypeJunction** [comment]
What happens if you trigger `.ui.toggle`, `elgg`, `elgg.ui`, `.toggle`?

**Comment by mrclay** [comment]
Removed namespaces from the event.

**Comment by hypeJunction** [comment]
:+1: 
I prefer the `$` implementation

**Pull request merged**
