### PR TITLE
fix(forms): userpicker works again when friends constraint is set

### LINKED ISSUE #11697: input/userpicker not acting correctly on only_friends = false

### PR DESCRIPTION
**Pull request by hypeJunction**
Fixes issues with the userpicker and friendpicker view and json endpoint

Fixes #11697

### CODE REVIEW

**Review by jeabakker — APPROVED** [review]
lint issues ;)

**Comment by jdalsem** [comment]
can we change this PR so i can use the userpicker without a friendsfilter AND without a visible friends checkbox (so it becomes a userpicker?)

**Comment by hypeJunction** [comment]
> can we change this PR so i can use the userpicker without a friendsfilter AND without a visible friends checkbox (so it becomes a userpicker?)

I already wrote a plugin that replaces the view completely, so I am not going back there.

**Comment by jdalsem** [comment]
don't know why that is related... i am not suggesting to remove this view

**Comment by hypeJunction** [comment]
You are asking for a feature that has no use to me, so I am not going to invest any time into it. Merge this and get rid of the friends filter if you want.

**Pull request merged**
