### PR TITLE
chore(categories): Remove the categories plugin

### LINKED ISSUE #7584: Suggest to drop site categories plugin
I suggest we drop the site categories for the following reasons:
- current implementation is completely flawed #6150 and fixing it is almost impossible
- looking at the amount of feature requests for this plugin it is probably not a really good implementation at this moment
- it is (in the current state) offering almost the same functionality as tags

If we drop this we could put more focus on improving tag related functionality instead of the categories. It is easier to add support for tags in your plugin instead of support for the site categories plugin...

What do you think?

### PR DESCRIPTION
**Pull request by ewinslow**
BREAKING CHANGE:
We've removed the "categories" plugin from core.

You may access it at https://github.com/Elgg/categories

Fixes #7584

### CODE REVIEW

**Comment by ewinslow** [comment]
In our previous discussions about this plugin we said we'd leave in the "input/categories" usages in other plugins in order to preserve BC. Since this is in 2.0, we don't strictly need to do that, but I think the spirit of 2.0 is to preserve BC as much as reasonably possible as long as it doesn't get in the way of other goals. Breaking BC "just because" or for the sake of "cleanup" isn't a good enough reason. So I vote we leave those other plugins alone in this case.

**Comment by hypeJunction** [comment]
Yes, please. There are other plugins that use those views.

**Comment by beck24** [comment]
Seconded, I use plugins that use that view/extension

**Comment by beck24** [comment]
PR LGTM

**Comment by ewinslow** [comment]
Added docs to admin/upgrading.rst. Will merge this tomorrow unless I hear otherwise.

**Comment by ewinslow** [comment]
Or someone else can feel free to do it before then.

**Pull request merged**
