### PR TITLE
fix(aalborg_theme): changes the navbar class name to ID

### LINKED ISSUE #7790: Navbar toggle does not work - 1.10

### PR DESCRIPTION
**Pull request by PerJensen**
Fixes #7790

### CODE REVIEW

**Comment by mrclay** [comment]
When did this feature break? Was is a JS change that we should revert?

**Comment by PerJensen** [comment]
I think it has something to do with this fix, #7508

**Comment by juho-jaakkola** [comment]
It was in fact this one that broke it: #7538

**Comment by ewinslow** [comment]
We should fix the issue that caused this, not work around it. This is a BC problem

**Comment by mrclay** [comment]
BC fix in #7790

**Pull request closed without merging**
