### PR TITLE
chore(upgrades): introduces method for checking if upgrade is required

### LINKED ISSUE #10517: Upgrade Locator should validate version before registering upgrades
Found out when running upgrade after fresh install (group icon transfer upgrade should not be needed)

### PR DESCRIPTION
**Pull request by juho-jaakkola**
Fixes #10517

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
Still working on the tests.

**Comment by juho-jaakkola** [comment]
Tests added/updated.

**Review by hypeJunction — APPROVED** [review]

**Comment by jdalsem** [comment]
is version also checked somewhere?? or was that already in place??

**Comment by hypeJunction** [comment]
> is version also checked somewhere?? or was that already in place??

I don't think it's needed anymore. `isRequired()` takes care of that.

**Comment by jdalsem** [comment]
what if we do both??  Some upgrades might be hard to check if they are required... like the groups check... it will have to check all groups on disk, but maybe none is required to be updated... certainly feels a bit unnecessary for fresh installs to also check if upgrades are needed...

**Comment by juho-jaakkola** [comment]
Sure, we can add a separate checking also for the version.

**Pull request merged**
