### PR TITLE
WIP add webdriver.io tests

### PR DESCRIPTION
**Pull request by mrclay**
A start towards running real browser tests.

Next steps:
- Allow running in PhantomJS instead of opening a Chrome window
- What can we test on most (customized) Elgg sites?
- How can we set up a default installation for testing?
- Can be run in Travis?

### CODE REVIEW

**Comment by mrclay** [comment]
@hypeJunction take a look

**Comment by hypeJunction** [comment]
Not familiar with it. Will have to do some homework

**Comment by mrclay** [comment]
The bad:
- Super confusing that the `browser` within specs is a synchronous API and http://webdriver.io/api.html is not.
- The WebDriver API is optimized for user interaction, you can't really use it to make specially crafted HTTP request and analyze responses. Trying to use Node's `request` within a spec basically fails silently. Seems like we'd need a separate test suite for low-level HTTP testing.

Maybe @ewinslow has some ideas here.

**Comment by ewinslow** [comment]
Yea, WebDriver is for simulating user interaction. Great for end-to-end tests. Not so great for lower-level stuff.

Is this meant to be for testing Elgg, or as a starting point for developers to write tests for their own sites?

**Comment by mrclay** [comment]
Ideally both, but really our immediate need is to make sure we don't break HTTP caching/content-type/status as @hypeJunction moves all responses into Symfony responses. This is an area where tests of the Response object don't tell the full story of what a client receives.

**Pull request closed without merging**
