### PR TITLE
chore(core): allows static analysis/autocomplete of internal config usage

### PR DESCRIPTION
**Pull request by mrclay**
`_elgg_config()` returns the Config object and property reads call get().
Removes many usages of $CONFIG.

### CODE REVIEW

**Comment by mrclay** [comment]
Note I purposefully left some elgg_get_config() usages in place: In views and actions (so the private _elgg_config doesn't get copied by devs), and where I don't want to conflict with later PRs.

**Comment by jdalsem** [comment]
why do you want to keep elgg_config private?

**Comment by mrclay** [comment]
My original plan was for elgg()->config to return Config, but documented as the more limited interface, so we could keep the extra methods out of the public API. I changed my mind because it seemed like just Yet Another Way for plugins to do it.

Same is true here, and also I'd prefer plugins authors not get autocomplete for a bunch of internal settings that they shouldn't mess with.

**Comment by mrclay** [comment]
In general I just want to improve internals static analysis in the short term. We can always decide the best API for plugins later.

**Review by jdalsem — APPROVED** [review]

**Pull request merged**
