### PR TITLE
fix(css): keep tabs together on smaller screens

### LINKED ISSUE #12173: Please preserve "All | Mine | Friends" tab structure when upgrading from 2x to 3x, for consistent UI experience
The new tabs in Elgg 3x, vertically stacked, takes up a lot of screen space in hand held devices ( majority users are using this ). And thus, Upgrading from 2x to 3x give multitude of users a different UI - unexpected and less user friendly

"All Site Activity" is unnecessarily larger in Elgg 3x

Can there be a secondary collapsible menu on left side of "All site activity" that on click will show "All | Mine | Freinds". If not, at least the tab structure of "All | Mine | Friends" as in 2x, please let be preserved in 3x or at minimum provide an option in Settings to do this. Many thanks.

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #12173

### CODE REVIEW

**Comment by jdalsem** [comment]
It will stretch tabs on tablet (and down)
image

in worst case scenario multiple lines

image

but in most case scenario it looks fine

image

**Review by jeabakker — APPROVED** [review]

**Comment by jdalsem** [comment]
@iionly and @rohit1290 what is your opinion?

**Comment by rohit1290** [comment]
This solution is definitely better.

Just a small suggestion (if possible), for the multiple lines, can there be a way to show only first few tab and a button to expand and show the renaming tabs. This way the tabs would be more compact and if any user want to select any hidden tabs then he/she can click on the expand button, the menu would open up one below the other (as shown in multiple lines) and the user can select his/her choice of the menu.

**Comment by jdalsem** [comment]
ultimately we need something like https://nl.wordpress.org/plugins/responsive-tabs/ where the tabs are also a hamburger menu, but that is for later

**Comment by rohit1290** [comment]
I think this is good for 3.0.. something can be worked out for later release.

**Pull request merged**
