### PR TITLE
docs(support): updates support policy and tentative release schedule

### PR DESCRIPTION
**Pull request by mrclay**
This was informally agreed upon here: https://elgg.org/discussion/reply/view/2362008/2359491
- [ ] make blog post
- [x] rewrite to first option in #9347

### CODE REVIEW

**Comment by mrclay** [comment]
At the current level of involvement I think this support burden is unrealistic but we might as well document what we agreed to for now.

**Comment by juho-jaakkola** [comment]
I'd prefer to first agree on a new policy. We're following semver properly, so there is no reason to support anything but the latest minor release.

**Comment by juho-jaakkola** [comment]
Let's vote here: #9347

**Comment by mrclay** [comment]
Decided on first option in #9347.

**Comment by iionly** [comment]
I think the release schedule displayed is no longer valid. It still says release of 2.2 is June 2016 but there's no 2.2 released yet. I guess 2.2 and all other release dates / end of support dates would need to be adjusted correspondingly - with a new date for 2.2 decided on first.

**Comment by mrclay** [comment]
Yeah, we need to get 2.2.0 out the door ASAP.

**Comment by mrclay** [comment]
docs PR #10196

**Pull request closed without merging**
