### PR TITLE
(WIP) Search hooks

### PR DESCRIPTION
**Pull request by hypeJunction**
Starting work on refactoring the search.

TODO:
- [ ] Write tests
- [ ] Update and extend documentation
- [ ] Add group profile fields to advanced search

### CODE REVIEW

**Comment by hypeJunction** [comment]
@ewinslow I haven't had time to look into this yet. I think I will need some pattern that I could follow. Any chance you could create a skeleton and I would fill in the rest?

**Comment by hypeJunction** [comment]
I have started converting this to OO. What is our plan with mb_wrapper functions?

**Comment by mrclay** [comment]
Are you asking about the future of elgg_substr() and friends? I don't think they're going anywhere.

**Comment by hypeJunction** [comment]
Ok. Should we convert them to DI class?

**Comment by mrclay** [comment]
It's not a pressing issue to me.

**Comment by ewinslow** [comment]
No, those don't need to be converted because they are "pure" stateless
functions iirc.

**Comment by ewinslow** [comment]
Could be fun to have our own String class, though...

**Comment by hypeJunction** [comment]
I think we have different ideas of fun ;)

**Comment by ewinslow** [comment]
@hypeJunction :). Laravel has their own, but it's all static methods. I'd love to be able to type hint for string internally and we could do that if we had a class for it...

**Comment by hypeJunction** [comment]
We could convert a bunch of string and output functions in a class, I suppose. Could avoid all the boilerplate to check if mb is present

**Comment by mrclay** [comment]
http://www.mrclay.org/2010/08/06/php-utf-8-string-class/ I'm not advocating this, though. I saw a PHP package recently that provide polyfill for all mb_* functions across all environments.

**Comment by ewinslow** [comment]
Why not advocate it? Seems handy?

**Comment by hypeJunction** [comment]
Closing this as it's impossible to rebase at this point. Will put together a strawman for OO.

**Pull request closed without merging**
