### PR TITLE
Search treats "0" as a valid query

### PR DESCRIPTION
**Pull request by stucky**
If an object has the valid tag "0", search will return an error if the tag is clicked. This pull request changes search to treat "0" as a valid query.

### CODE REVIEW

**Comment by hypeJunction** [comment]
LGTM

**Comment by brettp** [comment]
@stucky - Thanks for the PR ;-)

This causes an error in Travis because of the commit message. We have a strict format for commit messages so we can generate change logs. Checkout http://learn.elgg.org/en/1.11/contribute/code.html?highlight=commit%20message#commit-message-format to see the format.

**Comment by ewinslow** [comment]
I wonder why all the extra commits are here? Should only be one commit, yea?

**Comment by jdalsem** [comment]
You also need to update the commit message according to Elgg standards. Take a look at this documentation on the correct format for the commit message. http://learn.elgg.org/en/1.11/contribute/code.html#commit-message-format

**Comment by hypeJunction** [comment]
This was merged with #8215

**Comment by stucky** [comment]
@ewinslow I'm a long time Elgg developer but a total git newb. It turns out that friends shouldn't let friends rebase on their own. As @hypeJunction pointed out, I eventually got it together and the fix was merged with a different PR.

**Comment by ewinslow** [comment]
@stucky Glad you got it figured out. Welcome to git :)

**Pull request closed without merging**
