### PR TITLE
WIP feat(database): transition towards OO database queries

### PR DESCRIPTION
**Pull request by hypeJunction**
Motivation:

1. Combine `elgg_get_entities()`, `elgg_get_entities_from_relationship()`, `elgg_get_entities_from_metadata()`, and `elgg_get_entities_from_annotations()`

2. Start testing queries using PHPUnit without SQL sting madness

3. Allow closures in `wheres` and `joins`

```php
elgg_get_entities([
   'types' => 'object',
   'joins' => [
      function(QueryBuilder $qb) {
          return [
              'alias' => 'oe',
              'table' => $dbprefix . 'objects_entity',
              'condition' => $qb->expr()->eq('e.guid', 'oe.guid'),
          ];
     },
   ],
   'wheres' => [
      function(QueryBuilder $qb) {
          return $qb->expr()->andX(
             $qb->expr()->in('oe.title', ['lorem', 'ipsum']),
             $qb->expr()->like('oe.desription', "'%dolores%'"],
          );
      }
   ]
]);
```

### CODE REVIEW

**Comment by jdalsem** [comment]
wow... another big one...wanted to combine the ege* functions for a long time... good to see someone working on it. This will probably become a big PR... is it possible to split it in multiple smaller PR's / steps so the PR's are easier to review?

**Comment by hypeJunction** [comment]
I think so. This currently should work for metadata/annotations without any modifications. I will try to wrap this part first, and then we can slowly migrate other queries.

**Comment by hypeJunction** [comment]
Should probably also finish the subtypes table work first.
We need to get in Upgrade path tests, then test Phinx migrations with new tests, and then finalize subtypes.

**Comment by jdalsem** [comment]
Ref #5071

**Comment by jdalsem** [comment]
Also check #7500

**Pull request closed without merging**
