### PR TITLE
chore(vendor): stay on 1.11 branch of jquery-ui

### PR DESCRIPTION
**Pull request by iionly**

### CODE REVIEW

**Comment by mrclay** [comment]
@hypeJunction you think we should add composer.lock to 2.2 as well? I don't see the harm.

**Comment by hypeJunction** [comment]
That wouldn't bother me, but I would check with those who use the starter project.

**Comment by iionly** [comment]
If composer.lock could be a problem when using the starter project, won't there be the same kind of problem once Elgg 2.3 is released?

**Comment by mrclay** [comment]
@iionly Well yes but at least it's not in a bugfix release.

**Comment by hypeJunction** [comment]
What is the specific BC break you encountered? Javascript is quite easy to shim., maybe there is an easy workaround. I would prefer we use latest jQuery

**Comment by mrclay** [comment]
Even without lock file this will work. Can you add `Fixes #10199` to the commit and mention that this is for back compatibility?

**Comment by iionly** [comment]
@hypeJunction the problem I've noticed (there might be others with jquery-ui 1.12 I've not yet noticed) is with icon usage in the Plupload uploader script used in Tidypics (see https://jqueryui.com/upgrade-guide/1.12/#deprecated-icons-options-in-favor-of-icon-and-iconposition). For this specific issue I might have been able to make a fix in Plupload. But jquery-ui 1.12 also deprecated other functionality and this stuff will get removed in 1.13 (https://jqueryui.com/upgrade-guide/1.12/#preparing-for-jquery-ui-1-13). The version scheme used by jquery-ui is not semver and with our current composer.json version 1.12, 1.13 or any other newer version < 2.0 will get pulled regardless if it breaks any BC-compatibility.

@mrclay adding it to the commit message or just making a comment here? If adding to commit message can I do this with --amend (still not knowing all the git stuff)?

**Comment by mrclay** [comment]
> jquery-ui is not semver

Then I'm definitely for nailing down to 1.11.* in short term. Making conscious decision to upgrade it later.

`git commit --amend` will open a text editor for changing commit msg. 👍

**Comment by iionly** [comment]
Commit message updated.

Maybe it would be a good idea to discuss/review either in a separate issue or on the community site the upgrade policy of the other vendor scripts required in composer.json, too. If they are not having a strictly semver policy it's risky to just let new releases get pulled possibly on any bugfix release. It might get unnoticed that some stuff is broken. Maybe updating the requirements should be limited to new major releases (or at least reviewed when making a new feature release if bleeding edge versions are really necessary).

**Comment by mrclay** [comment]
> If they are not having a strictly semver policy it's risky to just let new releases get pulled possibly on any bugfix release

That's why composer.lock is essential. vendor upgrades don't happen outside of PRs. Feel free to brainstorm on formal policy in Plugin dev group on community.

**Pull request merged**
