### PR TITLE
chore(phpcs): updates elgg/sniffs and makes small changes necessary

### PR DESCRIPTION
**Pull request by mrclay**

### CODE REVIEW

**Comment by hypeJunction** [comment]
You have remove function comment sniffs completely, so no function doc comments are being checked, hence all is green and wonderful.

**Comment by mrclay** [comment]
I thought it would use CS's built-in checkers...

**Comment by hypeJunction** [comment]
All checks have to be defined in XML. CS doesn't have built-in checks, unless you do ``phpcs --standard=PSR2``

**Comment by hypeJunction** [comment]
Changes to 2.3 will be minimal, so I don't see a problem with ignoring doc blocks for now, and rolling with new standards in master

**Pull request merged**
