### PR TITLE
fix(install): don't block install if can't make internal requests

### LINKED ISSUE #10236: Cache/upgrade unusable on port-forwarded configurations
Problem: While developing I can't use the cache or run upgrade.php (well there is a workaround for upgrade.php).

Reason: Elgg checks the connection to itself before allowing upgrades to occur, or attempting to use the symlink cache.  In a port forwarded configuration the port of the external URL is not the port the system can use when using curl or get_headers() so those fail.

    /**
     * Checks if /cache has been symlinked to views simplecache directory,
     * and if HTTP requests to /cache are are successful
     * @return bool
     * @access private
     */
    function _elgg_is_cache_symlinked() {
	if (!is_dir(elgg_get_root_path() . 'cache/')) {
		return false;
	}
	$headers = get_headers(elgg_get_simplecache_url('elgg.js'));
	return substr($headers[0], 9, 3) == 200;
    }

Proposal: Add a config flag for power users to bypass the internal connection checks for these instances.

### PR DESCRIPTION
**Pull request by mrclay**

### CODE REVIEW

**Review by hypeJunction — APPROVED** [review]

**Comment by beck24** [comment]
This doesn't fix #10236 

For that to be fixed it needs to eliminate the rewrite check on upgrade.php and the symlink cache admin setting action.

**Comment by beck24** [comment]
To be clear the symlink cache admin setting doesn't use the rewrite tester, it uses get_headers() on the cache url.

**Comment by mrclay** [comment]
Is this change still needed?

**Comment by beck24** [comment]
I think emitting warnings is better than blocking in this instance

**Comment by mrclay** [comment]
Removed mention of #10236

**Pull request merged**
