### PR TITLE
chore(tests): use atypical dbprefix for travis installer

### LINKED ISSUE #7056: Use atypical DB prefix on Travis install
See https://github.com/Elgg/Elgg/issues/7033#issuecomment-48598556

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #7056

### CODE REVIEW

**Comment by mrclay** [comment]
LGTM

**Comment by ewinslow** [comment]
sweet.

**Comment by Srokap** [comment]
Does it actually work as expected? Originally I didn't include it as `batchInstall` was ignoring prefix parameter. On the first glance I don't see it fixed here https://github.com/Elgg/Elgg/blob/1.10/engine/classes/ElggInstaller.php#L171

**Comment by jdalsem** [comment]
$defaults is merged with $params, so providing params should override the defaults

**Pull request merged**
