### PR TITLE
fix(session): Remember me no longer results in occasional fatal errors

### LINKED ISSUE #8104: Remember me fatal error
Just tried logging into the community site clicking "Remember me" and got this error:

Duplicate entry 'XXX' for key 'PRIMARY'

QUERY: 
INSERT INTO elggusers_remember_me_cookies (code, guid, timestamp)
VALUES ('XXX', 11814, 1427204361)

### PR DESCRIPTION
**Pull request by mrclay**
Fixes #8104

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
LGTM

**Comment by ewinslow** [comment]
Seems fine. Would "on duplicate update" work just as well?

**Comment by ewinslow** [comment]
Net improvement, so pulling this in. Don't need it to get stale while waiting for perfection to happen

**Comment by mrclay** [comment]
ON DUPLICATE UPDATE does seem better, but I don't know how to test that. The current tests just mock the DB and I can't reproduce the bug locally. Any ideas?

**Comment by mrclay** [comment]
I could just run the queries manually through a MySQL client.

**Pull request merged**
