### PR TITLE
deprecate(views): Support for custom template handlers will end soon

### PR DESCRIPTION
**Pull request by ewinslow**
This functionality was never really properly implemented anyways.
Even the docblock comments on the API functions says "experimental."

Refs #8440

### CODE REVIEW

**Comment by ewinslow** [comment]
@brettp any opinion on this?

**Comment by jdalsem** [comment]
:+1: to remove this

**Comment by ewinslow** [comment]
Figure we deprecate here, then merge up and remove on master

**Comment by brettp** [comment]
Agreed...kill it! This is just cruft that was never really used.

**Comment by ewinslow** [comment]
Good riddance!

**Pull request merged**
