### PR TITLE
perf(filestore): added internal file exists cache

### PR DESCRIPTION
**Pull request by jdalsem**

### CODE REVIEW

**Review by jeabakker — APPROVED** [review]

**Comment by hypeJunction** [comment]
I think this is redundant. PHP already does this internally: https://stackoverflow.com/a/4099146/677409

**Comment by jeabakker** [comment]
Except when you set `open_basedir` restrictions than the internal file cache will be disabled https://www.php.net/manual/en/ini.core.php#ini.open-basedir

**Comment by hypeJunction** [comment]
Wouldn't that just break Elgg?

**Comment by jeabakker** [comment]
> Wouldn't that just break Elgg?

no, why?

**Comment by hypeJunction** [comment]
The way I understood the doc you linked, it's not just the cache that's disable, but the access to file is prevented. If you limit it, Elgg won't be able to access the dataroot (I suppose you could have docroot and dataroot under the same directory, but overall it seems like it could be problematic for Elgg to have limited access to the file system).

**Pull request closed without merging**
