### PR TITLE
feature(js): dropped rel='popup' feature in favor of rel='toggle'

### LINKED ISSUE #7944: Suggestion: drop rel='popup' in favor of 'toggle'
Currently `rel='popup'` is barely used in core and only causes issues like #3087. I suggest we drop this in 2.0 and replace the current occurences with `rel='toggle'`

### PR DESCRIPTION
**Pull request by jdalsem**
BREAKING CHANGE:
if your plugin is using rel='popup', you should change it to use
rel='toggle' and update the related code

fixes #7944

### CODE REVIEW

**Comment by hypeJunction** [comment]
I would be interested in a consolidated solution for popup and light box.
Having both seems like extra API and work

**Comment by jdalsem** [comment]
> I would be interested in a consolidated solution for popup and light box. Having both seems like extra API and work

popup !== lightbox in this case. Behaviour is completely different. This just drops the rel='popup' feature. If you need toggleble content, use rel='toggle'. If you need stuff in a "popup" use lightbox

**Comment by hypeJunction** [comment]
Oh, sorry. I didn't pay enough attention.

**Comment by juho-jaakkola** [comment]
I'm using popup a lot in my plugins. And in ways that would currently work neither with lightbox nor toggle.

So I'm against removing it. If we would first enable the same features (mainly positioning) for lightbox I could consider it.

**Comment by jdalsem** [comment]
> And in ways that would currently work neither with lightbox nor toggle

can you give an example?

**Comment by juho-jaakkola** [comment]
Users need to be able to "peek" the contents so that the popup won't cover the page like lightbox does. Also the popup needs to be located in a particular location to understand the context better.

**Comment by jdalsem** [comment]
can still be done using toggle

**Comment by juho-jaakkola** [comment]
Toggle requires a lot of space from the layout itself. The elements where I use popup have either very small or nonexistent amount of space around them.

**Comment by jdalsem** [comment]
toggle has no layout... is only toggles visibility of an item

**Comment by jdalsem** [comment]
are you not mixing it up with the popup module?

**Comment by juho-jaakkola** [comment]
When the togglable element becomes visible it requires space from the page itself. Whereas popup appears *on top* of the page.

**Comment by jdalsem** [comment]
> When the togglable element becomes visible it requires space from the page itself. Whereas popup appears on top of the page.

there was no styling what so ever related to popup or toggle... other then the specific modules. So i still do not get what you are refering to...

**Comment by juho-jaakkola** [comment]
I wonder if we're talking about the same thing.

By toggle do you mean the "Toggle (rel=toggle)" in www.example.com/theme_sandbox/javascript ?

Here's an example of a case where popup cannot be replaced with toggle:
notifier2

**Comment by jdalsem** [comment]
ah, you were talking about the feature of popup where the content is lazy loaded from an url... that is what lightbox is for, however i see your point that that will be too much in this case... what if we add the 'load content from url' feature to the toggle functionality? That way you are saved :)

**Comment by juho-jaakkola** [comment]
Where would the togglable element be displayed in the above case when it becomes visible?

**Comment by jdalsem** [comment]
Without any extra styling... where you position the placeholder. Additional css can position it anywhere else

**Comment by juho-jaakkola** [comment]
Ah, so you mean absolute positioning via CSS?

**Comment by jdalsem** [comment]
> Ah, so you mean absolute positioning via CSS?

yep

**Comment by jdalsem** [comment]
or relative... whatever you need

**Comment by mrclay** [comment]
docs/guides/upgrading should be updated for all BC breaks

**Comment by mrclay** [comment]
Needs a 2.x deprecation and rebase. https://github.com/Elgg/Elgg/issues/7944#issuecomment-192405787

**Pull request closed without merging**
