### PR TITLE
fix(admin): use correct params for redis server information

### PR DESCRIPTION
**Pull request by RiverVanRain**

### CODE REVIEW

**Review by jeabakker — APPROVED** [review]

**Comment by jeabakker** [comment]
thank you

**Comment by RiverVanRain** [comment]
This is affected on Elgg 4.3 too

**Comment by jdalsem** [comment]
Is it possible for you to create a PR on 4.3 combined with the memcached fix (and also look at related invalid config examples in the docs)?

**Comment by RiverVanRain** [comment]
I couldn't find anything in the docs except for this [1](https://github.com/Elgg/Elgg/blob/4.3/engine/classes/Elgg/Cache/Config/Redis.php#L44), [2](https://github.com/Elgg/Elgg/blob/4.3/engine/classes/Elgg/Cache/Config/Memcached.php#L38).

For 5.x is OK.

**Comment by jdalsem** [comment]
Replaced by #14425

**Pull request closed without merging**
