### PR TITLE
feature(urls): Adds service for working with URLs

### PR DESCRIPTION
**Pull request by mrclay**
Fixes #5527

Please comment on the API below and I'll move forward with docs.

``` php
$urls = elgg()->urls;

// current URL
$urls->getPath(); // "blog/view/123/my-title"
$urls->getUrlSegments(); // ["blog", "view", "123", "my-title"]
$urls->isWithinPath('blog/view'); // true

// returns false if $some_url not within site.
$path = $urls->analyzePathWithinSite($some_url);
$path->getPath();
$path->getUrlSegments();
$path->isWithinPath('blog/view');
```
- [x] tests
- [ ] docs

### CODE REVIEW

**Comment by hypeJunction** [comment]
Love it

**Comment by mrclay** [comment]
Right now \UFCOE\Elgg\Url\Result splits the path segments into first and rest. Would we rather have the same as this service: path is `"blog/view/123"` and url_segments as `['blog', 'view', '123']`? I kinda think so.

**Comment by mrclay** [comment]
Reworked this, and the URL analyzer a bit. Now you only get the result object if it's a path within the site. Not much different, though.

```php
$urls = elgg()->urls;

// current URL
$urls->getPath(); // within site
$urls->getUrlSegments(); // within site
$urls->isWithinPath('blog'); // we're on a blog page

// returns false if some URL not within site.
$path = $urls->analyzePathWithinSite($some_url);
$path->getPath(); // within site
$path->getUrlSegments(); // within site
$path->isWithinPath('blog'); // URL represents a blog page
```

**Comment by hypeJunction** [comment]
I love your script, but I don't thi k it's reliable enough. We should instead teach our router what segments mean. This could be a short-term solution, but it would have to be aware of Elgg's routing system and route rewrites.

**Comment by mrclay** [comment]
I see your point. Simple access to the path within the site (public and internal) would help us most in the short term.

**Pull request closed without merging**
