### PR TITLE
fix(languages): thewire create river language string

### PR DESCRIPTION
**Pull request by rohit1290**
Fix for https://github.com/Elgg/Elgg/issues/12490

### CODE REVIEW

**Comment by jeabakker** [comment]
The old keys should still work see https://github.com/Elgg/Elgg/blob/72e57ac100ff446302b422887016e89d8687ffb9/views/default/river/elements/summary.php#L71-L72 

Yes these new keys also work, but if others rely on these (old) keys being present we'd break plugins. That's why when we added the new river language keys we also supported the old ones

**Comment by rohit1290** [comment]
but what i found was there was no consistence in the language files.
Example: In `cs.php`, `da.php`, `es.php`, `eu_es.php`, `fi.php`, `gl.php`, `it.php`, `ja.php`, `pl.php`, `pt_br.php`,` ru.php` and `sr.php` has the string `'river:create:object:thewire'`
but in other language file like` en.php`, `de.php`, `fr.php` and `river/object/thewire/create.php` has the string `'river:object:thewire:create'`

Shouldn't we maintain a consistent language string across all the language files for the plugin?

**Comment by jeabakker** [comment]
translations for other languages are managed by Transifex and are pulled in every once in a while. 

Changing keys in other language file has no point as they'll get overridden when we pull in the translations

**Comment by rohit1290** [comment]
but again.. if `river:$action:$type:$subtype` is deprecated then the core language file should be updated accordingly. Currently the language file has the old string and my pull request is updating the language string to new one so that the elgg deprecated notice is not generated.

**Comment by jeabakker** [comment]
I did a language pull and clean up from transifex in #12501 
Lots of translations have been improved

**Pull request closed without merging**
