### PR TITLE
chore(release): v2.3.2

### PR DESCRIPTION
**Pull request by jeabakker**

### CODE REVIEW

**Comment by hypeJunction** [comment]
Composer didn't complain?

**Comment by jdalsem** [comment]
no composer update done, so no changes

**Comment by hypeJunction** [comment]
sites won't be able to update to this version using composer

**Comment by jdalsem** [comment]
nothing changed in composer, so why would that be different from 2.3.1?

**Comment by hypeJunction** [comment]
If you run composer update from starter project, it will likely try to update dependencies. Not sure... Whatever, can't be bothered now.

**Pull request merged**
