### PR TITLE
chore(i18n): Adds limited support for new languages on Transifex

### LINKED ISSUE #7540: Transifex breaks sprintf format/dollar signs in translations
Change lang file name of portuguese files to "pt_br" (currently this as pt_BR). for this reason the translation is not working.

### PR DESCRIPTION
**Pull request by mrclay**
Updates release script to normalize language filenames and remove unrecognized language files. Adds missing InvalidLocaleException.

Fixes #7540

Unlike an earlier PR, this keeps languages lowercase to keep add_translation() BC. Currently using "en" or "EN" with add_translation() works identically.

### CODE REVIEW

**Comment by ewinslow** [comment]
Please resubmit against 1.12. This seems like one of the more difficult bugs blocking 2.0 final

**Comment by iionly** [comment]
Elgg 1.12.1 pulled yet another new language from Transifex. This time it's eu_ES.php (Basque). These files are most likely not handled yet (lowercase etc.), i.e. the same problem again...

**Comment by hypeJunction** [comment]
Can't we have a list of supported languages listed in core and pulled from
Transifex. When someone completes another translation, they can make a pull
request to add that language to the list to be pulled?

**Comment by iionly** [comment]
@hypeJunction 
There is already a list / an array of supported languages in core. Best would be to update this list / array already when allowing a new language at Transifex and not require the translator to provide a PR (translators are not necessarily coders and also you can't be sure that the PR is really made before the files are pulled).

There's an other issue here already with a discussion / PR about adding all languages of Transifex to core. But this would be hundreds of languages (and quite a number of these language codes are duplicates or belong to obscure dialects).

**Comment by hypeJunction** [comment]
As far as I can tell we have under 10 fully translated languages, I don't
think anything below 100% should be in core.

**Comment by iionly** [comment]
> I don't think anything below 100% should be in core.

I do agree with that. Nevertheless, this has already been discussed in the past and decided otherwise...

**Comment by ewinslow** [comment]
We only pull down resources that are 100% translated. That is the best we can reasonably do with the API transifex gives us.

**Comment by mrclay** [comment]
Moved to #8954

**Pull request closed without merging**
