### PR TITLE
feature(messages): recipient selection by userpicker

### PR DESCRIPTION
**Pull request by jeabakker**
The messages recipient selection give better visual feedback of who will
be the recipient

Current visual feedback
messages recipient current

New visual feedback
messages recipient new

### CODE REVIEW

**Comment by mrclay** [comment]
Great idea.

**Comment by hypeJunction** [comment]
I would suggest we use one of the many jquery libs out there and
consolidate the abundance of autocomplete patterns that the core offers
(none of which are really user friendly). I have moved most of inputs that
have over 10 options to my tokeninput implementation, but it can be any
other lib, really. Even Chosen seems like a better option than anything we
presently have.

**Comment by jdalsem** [comment]
Agree with @hypeJunction that we could use a lot better #4679, but at least this (already existing) input/userpicker is better then the one messages was using, so for now i see this as an improvement.

Sometimes we just need to make baby steps...

**Comment by jdalsem** [comment]
@jeabakker maybe the subtext should be changed (as you are not required to enter a username, but a name will also suffice), or drop the text, or better move it to a placeholder for the input (if that is possible)

**Comment by ewinslow** [comment]
Clearly an improvement. If we want to make further improvements later I certainly can get behind such an effort

**Pull request merged**
