### PR TITLE
chore(aalborg_theme): changes comment style

### PR DESCRIPTION
**Pull request by PerJensen**
Fixes  #7161

### CODE REVIEW

**Comment by jdalsem** [comment]
I recently found out that this PR also removed the h3 with the "Comments" text. Now there is no title anymore for this section on a page. Any reason for the removal of the h3? I know @juho-jaakkola said in the fixed issue that it could be removed, but that only applied to the river and not to regular sections (like blog). Should we restore it there?

**Comment by mrclay** [comment]
I don't think it should be visually restored, but I wouldn't be against having the markup there. See also #8228. Can you make a new issue for this?

**Comment by juho-jaakkola** [comment]
Yes, I also thought the title would be removed only from the river view. I think it might be best to restore it for the other views.

**Comment by ewinslow** [comment]
I don't see the need for a visual heading for the comments section, as long as there is an accessible version.

**Pull request merged**
