### PR TITLE
Drop extras menu

### LINKED ISSUE #7729: Report this page link missing from pages without sidebars

### LINKED ISSUE #8718: Files gallery/list toggle should go in page menu
...not in the "extras" where it will likely be missed.

### PR DESCRIPTION
**Pull request by jdalsem**
- removed(navigation): removed usage of the extras menu

BREAKING CHANGE:
The extras menu is no longer used. Register your menu items to other
menus.

Fixes #7729
Fixes #8718

### CODE REVIEW

**Comment by mrclay** [comment]
"RSS feed for this page" is pretty wordy. Why not just "RSS" and clarify that in the title attribute? A general problem with this feature is people likely expect a site to have *one* primary feed, or link to a page of specific feeds, not one for *each page*. Especially considering we're putting this next to the global About/Terms/Privacy page links.

**Comment by mrclay** [comment]
May I suggest we consolidate page-specific stuff? 
footer

**Comment by hypeJunction** [comment]
Loose RSS from core. It's prehistoric technology that Elgg can't deal with gracefully. If there were lists API fin, but all this overhead without any gain in an access controlled system makes no sense

**Comment by mrclay** [comment]
Opened ticket to consider RSS removal #11021.

**Comment by jdalsem** [comment]
i moved expages menu items to the left

**Pull request merged**
