### PR TITLE
WIP feature(db): adds internal DB methods for common operations

### PR DESCRIPTION
**Pull request by mrclay**
I'd like to reach consensus around the new methods in the 1st commit. I'll remove the 2nd commit before merging, but it shows how the API can be used.

### CODE REVIEW

**Comment by hypeJunction** [comment]
Could we only merge the first commit, then bring in my mock services, then you can add the second?

**Comment by mrclay** [comment]
Yeah, see the new description.

**Comment by hypeJunction** [comment]
Works for me.

**Comment by hypeJunction** [comment]
Master is up to date now. The canvas is ready for your magic.

**Comment by mrclay** [comment]
Setting this aside for now. Several things I don't like:

1. adds yet another way to make queries
1. would prefer specifying columns like PDO: `:column`
1. would prefer it to use named PDO params internally to ease testing
1. Doctrine's QueryBuilder makes 2 and 3 messy, would have to extend it
1. ROI on reworking queries (and tests to match) is... nothing. Might just add bugs.

**Pull request closed without merging**
