### PR TITLE
Loggin changes

### LINKED ISSUE #6244: Adopt PSR-3 standard of logger Interface
See: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md

That requires using namespaces (and as a result PHP 5.3), so moving it to 1.10 if noone objects.

### LINKED ISSUE #10787: ElggLogCache has no size limiting
If developers screen logging is on, (and I'm reading this right) even cron scripts will capture all log messages in ElggLogCache.

I'm not sure what's a reasonable limit for messages on screen and which to include, the first N, the last N, or keep both and put "..." in the middle.

### LINKED ISSUE #11899: developer tools should not prevent default logging when outputting to screen
in various situation where there is no screen output (as in a default page_shell) developer_tools should always let default logging take place. This way logging will show in both on_screen and in php log files for example.

### PR DESCRIPTION
**Pull request by hypeJunction**
**feat(logger): Logger now uses Monolog**

 Logger is now based on Monolog, which also makes it PSR compliant.
Error logs now contain more detailed information about the errors
and the context in which they have occurred thanks to additional
processors and formatters. Logger can be easily extended with custom
handlers, processors, and formatters.
elgg_log() now accepts any arbitrary data, including an out of the
box support for logging Exception instances, which are treated in
a special way providing devs/admins with more detailed debugging
information.
Developers plugin now maintains a user friendly HTML error log.
Logger is now a public service.

Fixes #6244
Fixes #11899
 
**feat(developers): screen logging is now written to file** 

 To avoid using too much memory, runtime logs are written to file and
removed after being rendered

Fixes #10787

error_log

### CODE REVIEW

**Comment by hypeJunction** [comment]
Don't merge yet. I am moving us to monolog.

**Comment by hypeJunction** [comment]
Fixes #6244

**Comment by hypeJunction** [comment]
Fixes #11899

**Comment by hypeJunction** [comment]
@jdalsem @jeabakker any idea what upgrade script is doing something with widgets? It seems to be broken: https://travis-ci.org/Elgg/Elgg/jobs/369495872#L936

**Comment by jdalsem** [comment]
> @jdalsem @jeabakker any idea what upgrade script is doing something with widgets? It seems to be broken: https://travis-ci.org/Elgg/Elgg/jobs/369495872#L936

why is this not failing the build?

**Comment by hypeJunction** [comment]
> why is this not failing the build?

Not sure, probably exception is caught somewhere within the code and reported as error.

**Review by jeabakker — APPROVED** [review]

**Comment by hypeJunction** [comment]
The errors are still there, but they don't bother me for now. We can fix later on. I think all handlers will need to be closed for each test. Need to do more digging, but no time now.

**Comment by jdalsem** [comment]
Could you solve the conflicts? Then i can merge

**Comment by hypeJunction** [comment]
All done

**Pull request merged**
