### PR TITLE
chore(tests): report code coverage to scrutinizer

### PR DESCRIPTION
**Pull request by jeabakker**

### CODE REVIEW

**Comment by hypeJunction** [comment]
I have configured scrutinizer to run it's own tests. This will just add a few minutes of processing to already heavy build process

**Comment by jeabakker** [comment]
we're also working on speeding up the tests. I think it's easier to manage all tests from one place

**Comment by hypeJunction** [comment]
I am not sure how much faster the tests can be without migration to in-memory sqlite. Even then, reliability of tests is questionable without proper process isolation. I got sqlite working, but we need to drop all raw SQL for it to be of any use. There will be a PR coming soon refactoring all ege* to OO query building, which can then be used to rewrite all other queries. I won't manage it all alone, so if you want to help with that it might be better use of time that trying to speed up tests

**Comment by hypeJunction** [comment]
If you are not interested, I have already forked Elgg, so I will be diverging and doing my own thing.

**Comment by jeabakker** [comment]
our first focus for speeding up the test is moving to local images for seeding, the current Faker site is slowwwwwww

**Comment by hypeJunction** [comment]
We probably don't even need images there, can be moved to an options array similar to metadata and populated only for on-site seeding. IMO, not needed for Travis builds

**Comment by hypeJunction** [comment]
Did you back up scrutinizer config before making changes? I have spent quite a lot of time putting it all together, and now it's just barebones.

**Comment by jeabakker** [comment]
I didn't make the changes but here is the backup https://gist.github.com/jeabakker/d7f7f03967e6a1f05974f9ab6a4fb8e8

**Comment by hypeJunction** [comment]
Could you update scrutinizer please, I need to see the code coverage report.

Re: builds. One option is to eliminate seeding entirely on the upgrade build. We could create a MySQL dump of a seeded vanilla 2.3 install and data for and just import those during Travis build. The idea is to test the migration, so burning cycles on 2.3 seeding makes little sense from the testing standpoint

**Comment by jdalsem** [comment]
codecoverage on scrutinizer has been restored for the time being

**Comment by jdalsem** [comment]
we need to merge this... scrutinizer resources are too little for good progress... maybe actual runtime is indentical, but it takes ages for scrutinizer to free up resources before the job starts

**Comment by hypeJunction** [comment]
At least do it during e2e build, no reason to add a separate job

**Comment by jdalsem** [comment]
Merging this... can combine with other job later... lets see how this goes... waiting on scrutinizer is a pain, so we need to speed things up

**Comment by hypeJunction** [comment]
You need to update scrutinizer config

**Comment by jeabakker** [comment]
I updated the scrutinizer config according to https://scrutinizer-ci.com/docs/tools/external-code-coverage/

**Pull request merged**
