### PR TITLE
chore(docs): updated project README.md

### PR DESCRIPTION
**Pull request by jdalsem**
Borrowed text from @hypeJunction in https://github.com/Elgg/Elgg/issues/10328

This should make the readme a bit more attractive for people visiting the project on github

### CODE REVIEW

**Comment by hypeJunction** [comment]
You should add:

- Phinx database migrations
- nginx or Apache compatible
- CSSCruss for CSS preprocessing

**Review by jeabakker — APPROVED** [review]

**Comment by jdalsem** [comment]
updated with @hypeJunction suggestions

**Comment by jdalsem** [comment]
updated badges to use master/stable instead of 2.0 branch

**Comment by jdalsem** [comment]
@mrclay if you do not have any more suggestions, you may merge this

**Pull request merged**
