### PR TITLE
feature(application): Introduces Elgg\Application for loading/booting Elgg

### PR DESCRIPTION
**Pull request by mrclay**
(cleaned up version of #8187. cc @Srokap @ewinslow )

Removes references to engine/start.php in docs.
Removes load_plugins().
Deprecates inclusion of start.php for booting the core.
Moves settings loading to Elgg\Config and allows setting the config file path or bypassing loading a settings file.
Allows Elgg\Config to not use the global $CONFIG.
Allows use of Elgg\Database without booting core via the Application.
Refactors Elgg\CacheHandler and several other direct-call scripts to use Application
Allows the cache handler, export handlers, and thumbnail server to work using the CLI server.
Allows the Logger to be injected into Database during boot for lighter partial boot (e.g. cache_handler).
Removes unneeded join date GET param from profile icon URLs.

Refs #7721

### CODE REVIEW

**Comment by mrclay** [comment]
I added some notes to the upgrading docs that should be all we need for this. I think this is a step forward, but the most controversial thing is that users can get direct access to the Elgg\Config and Elgg\Database classes. I think this is still better than plugin devs using mysql_connect themselves for similar purposes.

**Comment by mrclay** [comment]
Whether we refactor this again for 2.0 this seems like a step forward. We can always add service location to this and deprecate the unneeded methods later.

**Comment by ewinslow** [comment]
Want to pull this in but has merge conflicts now. Please rebase and lets get this in ASAP

**Comment by juho-jaakkola** [comment]
Yeah, let's get it in.

**Comment by ewinslow** [comment]
Yay!!!!

**Pull request merged**
