### PR TITLE
fix(htaccess): removing of obsolete entry in htaccess.dist incompatible with Apache 2.4

### PR DESCRIPTION
**Pull request by iionly**

### CODE REVIEW

**Comment by beck24** [comment]
Travis builds failed - looks like it was a network issue during composer install, not related to the PR.  Restarting the checks.

**Comment by hypeJunction** [comment]
Composer install/update is f*****. We depend on security advisories, which has now listed older version of PHP CodeSniffer as vulnerable, hence we can't create a build. You can see my PR with an attempt to upgrade our sniffs to CS 2.8.1, but it's a mess and I have given up. Not sure what we are going to do: either remove security advisories from the repo until we update our sniffs (which not sure who is going to do, because I am not), or we just disable CS altogether.

**Comment by iionly** [comment]
Any chance to get these failing tests sorted out? Anything I can/need to do?

**Comment by mrclay** [comment]
I'd be open to just removing CS for the 1.12 branch.

**Comment by mrclay** [comment]
Add a commit that removes these lines:

- https://github.com/Elgg/Elgg/blob/1.12.15/composer.json#L46
- https://github.com/Elgg/Elgg/blob/1.12.15/composer.json#L26
- https://github.com/Elgg/Elgg/blob/1.12.15/composer.json#L45
- https://github.com/Elgg/Elgg/blob/1.12.15/.travis.yml#L31

**Comment by iionly** [comment]
Maybe checks will pass when restarted. It seems to have worked now for #10815 and I had made the two PRs at the same day. Otherwise I can make a commit for removal of the CS later on if the checks still fail.

**Comment by mrclay** [comment]
Builds still fail due to CS.

**Comment by mrclay** [comment]
@iionly it's only the 1.12 branch with the remaining CS problems. That's why your other PR is OK.

**Comment by iionly** [comment]
@mrclay commit made in https://github.com/Elgg/Elgg/pull/10881.

**Comment by mrclay** [comment]
You can now update your 1.12 branch and rebase this.
```
git checkout 1.12
git pull
git checkout htaccess-cleanup
git rebase 1.12
```

**Review by jeabakker — APPROVED** [review]

**Pull request merged**
