### PR TITLE
chore(views): refactored widget content view

### PR DESCRIPTION
**Pull request by jdalsem**
- [x] Update commit message to include the benefits of the refactor

### CODE REVIEW

**Comment by ewinslow** [comment]
What are the benefits of this refactor?

**Comment by jdalsem** [comment]
1. both the action and the object/widget view did the same content related checks. With this refactor the both use the same object/widget/elements/content view to handle the logic for the content output (no view logic in the actions). Reducing boilerplate.

2. Improved readability of the object/widget view

3. A side effect is that it now is easier to modify the generic content output of a widget instead of the full widget view. Also it is easier to extend...

**Comment by ewinslow** [comment]
Can you put these points into the commit message? Very helpful.

**Comment by ewinslow** [comment]
@jdalsem Don't want this to go stale. Should be a simple `git commit --amend`. Can we make this happen?

**Pull request merged**
