### PR TITLE
fix(reportedcontent): clicking on reported content links again opens lightbox

### PR DESCRIPTION
**Pull request by mrclay**

### CODE REVIEW

**Comment by hypeJunction** [comment]
I rhought @jdalsem was fixing it in another commit

**Comment by iionly** [comment]
@hypeJunction I think the other kind of fix suggested was about always loading the lightbox JS/CSS on all pages.

@mrclay I think for the reported content plugin to fully work as intended the lightbox JS and CSS should also get loaded in the init function within the if-clause registering the extra menu item and in the if clause within the function reportedcontent_user_hover_menu() when registering the hover menu item. The lightbox link_class is already referred to on the registering of the menu items but without the lightbox JS/CSS this fails to work. Maybe with loading the JS and CSS issue https://github.com/Elgg/www.elgg.org/issues/91 will also be automatically fixed (if not really a community theme issue).

**Comment by hypeJunction** [comment]
@iionly, we added `deps` to menu item registration.

**Comment by iionly** [comment]
@hypeJunction But not yet in 2.1 or am I wrong.

**Comment by hypeJunction** [comment]
Ah, right, it went in 2.x. There is so much happening I am confused :monkey_face:

**Comment by mrclay** [comment]
To clarify, this *is* the fix necessary for 2.1. In 2.x we can remove the additions.

**Pull request merged**
