### PR TITLE
WIP (mrclay) test upgrade path from Elgg 2.3 to current pull request

### PR DESCRIPTION
**Pull request by mrclay**
Racing @hypeJunction for the prize

### CODE REVIEW

**Comment by mrclay** [comment]
We need to get `$CONFIG->dataroot = getenv('HOME') . '/elgg_data/';` into the config file.

**Comment by mrclay** [comment]
Feel free to steal from me https://github.com/Elgg/Elgg/pull/11111/commits/0a8d3c6452344e729e32fc06a77417f741fbb954#diff-906fae229b5696c49d5e4913d4e662e9

**Comment by hypeJunction** [comment]
:) Sorry, was torn between two things

**Comment by hypeJunction** [comment]
We need to connect to the database, grab dataroot and write it to config file...

**Comment by hypeJunction** [comment]
loadSettingsFile should throw exception instead of exiting quietly

**Comment by mrclay** [comment]
We can use `getenv('HOME') . '/elgg_data/'`

**Comment by hypeJunction** [comment]
It would be nice to allow upgrade without having to make anyone edit any settings files.

**Comment by mrclay** [comment]
No way. Having dataroot in settings is worth it.

**Comment by hypeJunction** [comment]
What I am saying, is when upgrade is first run after 3.0 codebase is deployed we can fetch the data from the database and write it to the settings file. Then the upgrade script can proceed with wiping stuff

**Comment by mrclay** [comment]
Good news: with dataroot set, the PHP server curl call succeeds on the upgraded codebase. Of course, with dataroot set, simpletest isn't happy :rofl:

**Comment by mrclay** [comment]
Replaced by #11113

**Pull request closed without merging**
