### PR TITLE
feature(core): remove duplicate tags upon input

### PR DESCRIPTION
**Pull request by bruno-infotrad**
- [ ] resubmit for 1.12

### CODE REVIEW

**Comment by jdalsem** [comment]
LGTM

**Comment by mrclay** [comment]
Seems like a `fix` and useful in 1.12

**Comment by jdalsem** [comment]
@bruno-infotrad can you resubmit this PR against 1.12? and change the commit message to be a fix instead of a feature?

**Comment by bruno-infotrad** [comment]
Sorry for the delay. Done #9607

**Pull request closed without merging**
