### PR TITLE
feature(routing): allow more reliable URL path rewriting

### LINKED ISSUE #9388: Changing identifier in route hook
Should the core run the route hook on a new identifier if the route hooks changes the original identifier? e.g. if hook routes 'courses/all' to 'groups/all', all route hooks registered for 'groups' will never be fired. It seems that they should be.

### PR DESCRIPTION
**Pull request by mrclay**
Adds an early called `route:rewrite` hook expressly for URL rewriting. Changes there update the request object and affect the default context, and functions like current_page_url().

Removes legacy magic quotes-related code.

Fixes #9388

### CODE REVIEW

**Comment by mrclay** [comment]
My goal was to minimize the API surface area we have to support, and make conversion to the new hook easy.

**Comment by mrclay** [comment]
While this only covers the the path, you can still use get/set_input for GET vars, but ?hl and ?view have already been read by the time this hook executes.

**Comment by hypeJunction** [comment]
:+1: LGTM

**Comment by juho-jaakkola** [comment]
LGTM

**Pull request merged**
