### PR TITLE
chore(travis): fix hhvm build

### PR DESCRIPTION
**Pull request by hypeJunction**

### CODE REVIEW

**Comment by hypeJunction** [comment]
@mrclay Could you take a look at the failing tests? They are stash wrapper related. If we can fix those, we would be HHVM compatible.

**Comment by mrclay** [comment]
See https://github.com/hypeJunction/Elgg/pull/24

**Comment by hypeJunction** [comment]
Argh, I think it squashe them a d lost the commit messages

**Comment by hypeJunction** [comment]
Just 1 fail with ElggAutoP, and a warning in simple test password hash

**Comment by mrclay** [comment]
Ugh, Problem is https://github.com/facebook/hhvm/issues/2843 is still a real bug I'm convinced.

**Comment by mrclay** [comment]
I'm going to re-file this bug with HHVM with more clarity.

**Comment by mrclay** [comment]
Replaced by #10852

**Pull request closed without merging**
