### PR TITLE
Merge 1.12 to 2.0

### PR DESCRIPTION
**Pull request by juho-jaakkola**
After this the Travis tests should work again.

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
What is this then...

```
npm test

> Elgg@ test /home/travis/build/Elgg/Elgg
> node_modules/karma/bin/karma start js/tests/karma.conf.js --single-run

WARN [watcher]: Pattern "/home/travis/build/Elgg/Elgg/vendor/bower-asset/jquery/dist/jquery.js" does not match any file.
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Linux 0.0.0)]: Connected on socket ZDQwCMgNp-NU49JyYxb0 with id 55184644
PhantomJS 1.9.8 (Linux 0.0.0) ERROR
  ReferenceError: Can't find variable: jQuery
  at /home/travis/build/Elgg/Elgg/js/lib/elgglib.js:42
```

**Comment by mrclay** [comment]
During `composer install` travis hits the GitHub API rate limit and simply installs the repo for jquery and the other Bower assets, hence the `dist/` directory doesn't get created.

**Comment by mrclay** [comment]
We can give Travis a user token, but anyone could create PR that exposes it. The token wouldn't need any special scopes so maybe that's OK? http://blog.wyrihaximus.net/2015/09/github-auth-token-on-travis/

**Comment by mrclay** [comment]
Actually when I `composer install --prefer-source` locally I still get the `jquery/dist/jquery.js` file, so I don't know why it's missing on Travis.

**Comment by mrclay** [comment]
The big question: can end users also end up with incomplete bower-asset/ trees?

**Comment by mrclay** [comment]
Closing in favor of #9145

**Pull request closed without merging**
