### PR TITLE
feature(ckeditor): added js plugin hook to ckeditor config

### LINKED ISSUE #7131: Pass ckeditor config array through a hook
Would be nice to alter bits of this without replacing the whole view.

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #7131 

also tested this and it works pretty nice

### CODE REVIEW

**Comment by mrclay** [comment]
I'm a little weary of race conditions mixing AMD with hooks, but I'm probably being paranoid. What do you think @ewinslow ?

BTW, does CKeditor allow per-instance configs?

**Comment by jdalsem** [comment]
CKEditor does per instance configs... i always liked having a full (blog edit) and a minimal (comments)... but that is for another ticket

**Comment by ewinslow** [comment]
@mrclay yea, anything that wants in on this hook would have to be loaded before this AMD module is executed, and there's nothing enforcing that, so it also makes me a tad nervous...

**Comment by jdalsem** [comment]
alternative is to move it to php, but that will be a bit messy and a breaking change (view rename)

**Comment by mrclay** [comment]
This view is tiny, seems not too bad to have plugins override it.

**Comment by mrclay** [comment]
Do we really not have a reliable method for plugins to run code before AMD modules?

**Comment by ewinslow** [comment]
@mrclay Correct. Modules list their own dependencies. It's not possible to modify those without changing the source of the module.

This is a Good Thing, I think. We should step back and reconsider the design if there's some case that isn't satisfied by this...

**Comment by mrclay** [comment]
For now: Move the defaults to a new module: elgg/ckeditor/config_defaults.js and have this depend on it. Plugins would then just override config_defaults.

**Comment by mrclay** [comment]
Scratch that, that's all this module does anyway...

**Comment by mrclay** [comment]
I think we're missing a way for plugins to register their AMD module to be a dependency of the elgg module.

**Comment by ewinslow** [comment]
@mrclay yea, but then that feels backwards. Will have to noodle on this...

**Comment by mrclay** [comment]
Making a new issue...

**Comment by jdalsem** [comment]
Should we close this PR and as such do not fix #7131?

**Pull request closed without merging**
