### PR TITLE
fix(docs): display all code and code-blocks in docs

### PR DESCRIPTION
**Pull request by iionly**

### CODE REVIEW

**Comment by iionly** [comment]
See https://github.com/Elgg/Elgg/issues/12150.

**Comment by jdalsem** [comment]
thanks for noticing. actually both ``.. code::php`` and ``.. code:: php`` are incorrect. It should be ``.. code-block:: php``. Only using code-block will we have php highlighted code (see docs/guides/access.rst for examples). 

Could you update all ``code:: php`` (with and without space) to ``code-block:: php`` ?

**Comment by iionly** [comment]
I've gone over all doc files to update ```code::``` to ```code-block::``` usage and also added a whitespace after :: for other languages where needed.

Additionally, I changed whitespace usage (within each code example separately) to have a consistent whitespace usage at least within each example (not overall as there are different styles used throughout the different files). It might not have made a difference on display of the docs in a webbrowser but my editor at least didn't correctly highlight the code otherwise.

I also made sure that lexers usage is consistent.

**Comment by jdalsem** [comment]
there is a small error in one of your changes https://travis-ci.org/Elgg/Elgg/jobs/429207940#L780

**Comment by jdalsem** [comment]
why was the javascript -> js change needed? sphinx docs tell to use javascript AFAICT

**Comment by iionly** [comment]
Hmm.. code-block:: is supposed to work (without highlighting) with no lexers provided. code:: does but apparently code-block does not for whatever reason...

Both js and javascript was used as lexer throughout the various files. js was used more often so I changed all javascript to js to have consistent usage.

**Comment by iionly** [comment]
Great... now I have messed up my local branch.

**Comment by jdalsem** [comment]
just reset to the PR branch

**Pull request merged**
