### PR TITLE
feature(views): Allow sites to specify views.php at root

### PR DESCRIPTION
**Pull request by ewinslow**

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
Why is this needed?

**Comment by ewinslow** [comment]
When you install elgg via composer, you can use the root directory like a plugin, but without a manifest.xml and it cannot be disabled. Plugins can use a `views.php` in their root to define custom view mappings, so it makes sense for you to use this in your site's root dir as well.

**Comment by juho-jaakkola** [comment]
Could you add that also to the body of the commit message? Otherwise LGTM.

**Comment by ewinslow** [comment]
Will do. We need to do a bunch of screencasts or something to get everyone caught up on what's possible in 2.0!

**Comment by mrclay** [comment]
Hmm, the core views.php is also in the root. Are we sure this only applies when Elgg is installed via composer?

**Comment by mrclay** [comment]
I mean, I guess it doesn't matter...

**Comment by ewinslow** [comment]
This is only triggered when we detect that elgg is installed as a composer
dependency, I.e. not at root.

**Comment by ewinslow** [comment]
This is a feature, but it is actually a completion of one introduced in 2.0, so I figure we just pull this in before 2.0. It would be too awkwardly absent otherwise.

**Comment by ewinslow** [comment]
https://github.com/Elgg/Elgg/pull/8804/files#diff-906fae229b5696c49d5e4913d4e662e9L257 is the check that it's not Elgg core's views.php file.

**Pull request merged**
