### PR TITLE
Legacy urls chores and fixes

### PR DESCRIPTION
**Pull request by hypeJunction**

### CODE REVIEW

**Comment by hypeJunction** [comment]
@ewinslow What was your thinking in terms of fixes to bundled plugins that now have their own repos?

**Comment by mrclay** [comment]
I think I'd rather fix this by having the Application capture and remove the __elgg_uri from input very early. It's not something that should even creep into the Request object ideally.

**Comment by ewinslow** [comment]
We can push any new commits from this repo to those ones using 

```
git subtree push -P mod/{plugin_name} git@github.com:Elgg/{plugin_name} master
```

**Comment by ewinslow** [comment]
We should also run this from a checkout of Elgg/Elgg at master, and always push to master for those repos.

**Comment by mrclay** [comment]
Let's pull this in and do a [better refactor](https://github.com/Elgg/Elgg/pull/8498#issuecomment-112503281) in 1.x.

**Comment by mrclay** [comment]
LGTM

**Pull request merged**
