### PR TITLE
chore(contributors): add Matt Beckett to contributors

### PR DESCRIPTION
**Pull request by beck24**

### CODE REVIEW

**Comment by mrclay** [comment]
@Elgg/owners anyone else we need to add here?

**Comment by juho-jaakkola** [comment]
What would you suggest as the minimum amount of commits?

**Comment by beck24** [comment]
I just assumed people who wanted to be listed would PR themselves in :)

**Comment by hypeJunction** [comment]
I think I am with Juho on this. There needs to be some guideline.

**Comment by juho-jaakkola** [comment]
My initial though was that 100 commits sounds like a good number. But then I checked, and that would mean neither matt or ismayil would make it. ;)

@jdalsem @jeabakker @Srokap and @sembrestels are well above 100.

**Comment by beck24** [comment]
heh, I thought I would be over that... I'll have to call a "quality over quantity" defence :)
But @jdalsem @jeabakker @Srokap and @sembrestels I would think should certainly be listed

**Comment by hypeJunction** [comment]
Quality is important, but 100 sounds fair. We could also count in the
feedback contributed, as well as the good will that went into reviewing
thousands of lines of code contributed by others :)

**Comment by mrclay** [comment]
We've removed people from these files as well https://github.com/Elgg/Elgg/commit/5b0c8591a5e1f6cfc53e6f5131145a07ac7ae0cf

I think the copyright file has some formal guideline associated with it, but in the age of git I'd be willing to lose this file. It's just another thing to worry about.

**Comment by beck24** [comment]
That's true, git records all

**Comment by jeabakker** [comment]
why not replace the contents of the file with just a link to https://github.com/Elgg/Elgg/graphs/contributors, this way it's always up-to-date

**Comment by juho-jaakkola** [comment]
Yeah, the links seems like a good idea.

**Comment by ewinslow** [comment]
+1 on pointing to the github list

On Thursday, September 17, 2015, Juho Jaakkola <notifications@github.com>
wrote:

> Yeah, the links seems like a good idea.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Elgg/Elgg/pull/8935#issuecomment-141097547>.
>


-- 
Evan Winslow
http://community.elgg.org/profile/ewinslow

**Comment by jeabakker** [comment]
another suggestion, also add a link to https://elgg.org/supporter.php as they contribute financialy

so maybe
```
Code contributors
https://github.com/Elgg/Elgg/graphs/contributors

Financial contributors
https://elgg.org/supporter.php

We'd like to thank all contributers for their support
```

**Pull request closed without merging**
