### PR TITLE
Merge 2.x master

### PR DESCRIPTION
**Pull request by hypeJunction**

### CODE REVIEW

**Comment by hypeJunction** [comment]
Is this the first merge to master since we added \Elgg\TestCase? I think we will need to work on this.

**Comment by mrclay** [comment]
It might be better to do this on my bitbucket account, where we can see and collaborate on merge conflicts. Shall I set that up?

**Comment by hypeJunction** [comment]
How is that different from doing it here?

**Comment by mrclay** [comment]
See https://bitbucket.org/mrclay/elgg-private/pull-requests/18/merge-2x-into-master/diff

**Comment by hypeJunction** [comment]
Let's wait until next week. I am packaging all database mocking stuff from different PRs into one. Coming soon. Refactoring some tests, so it will be better to resolve conflicts afterwards.

**Pull request closed without merging**
