### PR TITLE
Ckeditor resize/autogrow

### LINKED ISSUE #8727: CKeditor is not resizable

### PR DESCRIPTION
**Pull request by jdalsem**
- feature(ckeditor): allowed resizing of editor window fixes #8727
- feature(ckeditor): added editor autogrow plugin

### CODE REVIEW

**Comment by mrclay** [comment]
LGTM, but let's get some feedback. Will conflict with #9684.

 Could surprise site owners. Another case for #9713?

**Comment by hypeJunction** [comment]
I wouldnt worry about #9684, we can update config later. The problem is that ckeditor is darn slow as is. Adding more plugins will make it slower.  We should worry about making it configurable/extendable instead.

**Comment by jdalsem** [comment]
https://github.com/Elgg/Elgg/issues/9391 will help for the configurability... but i agree that ckeditor is slow... i do not know if the amount of plugins is the major reason for that

**Comment by jdalsem** [comment]
Going to merge this for now... will work on #9391 this week

**Comment by hypeJunction** [comment]
Ehm, I don't really want this in a minor release.

**Pull request merged**
