### PR TITLE
chore(core): Replaced deprecated elgg_file_get_simple_type() with elgg_get_file_simple_type()

### PR DESCRIPTION
**Pull request by rtugores**
Function "elgg_file_get_simple_type()" does not exist. Replaced "elgg_file_get_simple_type()" per "elgg_get_file_simple_type()"

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
Thanks for the pull request!

Could you just update the commit message to this format http://learn.elgg.org/en/1.10/contribute/code.html#commit-message-format and we'll merge the PR right away.

So instead of this:
```
Minor bug in name function fixed
```
the message should be something like:
```
chore(core): Replaced deprecated elgg_file_get_simple_type() with elgg_get_file_simple_type()
```

**Comment by mrclay** [comment]
LGTM

**Comment by juho-jaakkola** [comment]
Thanks for fixing the commit message, that was fast!

BTW, when you edit an existing PR, make sure to mention it in the comments. Github does not send a notification to the repository owner when the contents of a PR gets changed.

**Comment by rtugores** [comment]
OK. I appreciate your advice!
Sorry for not having done so, since I am new at Github.
Thank You!

**Pull request merged**
