### PR TITLE
fix(js): catch global ajax errors and report to the user

### LINKED ISSUE #5134: elgg ajax does not handle 404 errors
Or any other errors. To test, stop your web server. The user is never told them something has gone wrong.

We need to notify the user when connectivity has been lost and when it has been regained.

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #5134

### CODE REVIEW

**Comment by jdalsem** [comment]
http://api.jquery.com/jQuery.Ajax/ -> error event

**Comment by mrclay** [comment]
:+1:

**Comment by jdalsem** [comment]
Somebody else with a LGTM? Then it can be merged.

**Comment by mrclay** [comment]
Seems safe to me.

**Comment by hypeJunction** [comment]
Looks fine to me, but haven't tested.

**Pull request merged**
