### PR TITLE
fix(language codes): correcly language codes: from zh_hans to zh-cn.

### PR DESCRIPTION
**Pull request by ewail**

### CODE REVIEW

**Comment by jdalsem** [comment]
Isn't `zh-hans` and `zh-cn` the same? They are both simplified chinese if i am correct. Why do you want this changed?

**Comment by ewail** [comment]
More commonly used is zh-cn.
zh-Hans unrecognized by ckeditor

from msdn：
zh-CN → zh-CHS → zh-Hans → zh → Invariant
zh-TW → zh-CHT → zh-Hant → zh → Invariant

**Comment by ewail** [comment]
If we refer to third-party plugins, zh-hans can't be identified.

**Comment by jdalsem** [comment]
ok, but isn't the language different somehow? Can we just change `hans` to `cn` without any changes to the translation contents?

**Comment by iionly** [comment]
Elgg uses no "-" in language file names so far but only "_". I'm not sure if it would cause issues if allowong language file names with a "-".

Apart from that the translations would need to come from Transifex. Also, I'm not sure if zh_hans or zh_cn is the right one - different standard documents list different codes. If you make the code fit one 3rd party script it will surely result in breaking some other.

You could try renaming the language file of the ckeditor. I did the same for tinymce and it works. Maybe it will also work for ckeditor. Just rename the language file and change the CKEDITOR.lang key within the file to fit the name of the file. If it is changed to zh_hans it work fine.

**Comment by jdalsem** [comment]
I am thinking that zh-hans and zh-hant are the best language codes for Chinese Simplified or Traditional. I can not find anything that says it should be otherwise. Elgg currently uses `zh` and `zh-hans`. I am not sure what the difference between those codes is. If anything, we could change it to `zh-hans` and `zh-hant`. I don't think we should switch to `zh-CN` and `zh-TW`.

CN/TW are region indicators
Hans/Hant is a script indicator
See: https://www.w3.org/International/articles/bcp47/

If we also look at other frameworks like Drupal; they are using zh-hans (https://localize.drupal.org/)

For these reasons i am closing this PR. If you would like to discuss this further you may open a issue for that.

**Pull request closed without merging**
