### PR TITLE
chore(system_log): log browser works again

### LINKED ISSUE #11710: Systemlog not functioning
actions do not show in log browser... do not know if logging fails or getting results

ref #11701

### PR DESCRIPTION
**Pull request by hypeJunction**
Fixes some normalization logic of parameters in legacy usage of
system_log_get_log()

Fixes #11710

### CODE REVIEW

**Comment by jdalsem** [comment]
can you fix this?

**Comment by hypeJunction** [comment]
Don't have any more energy for that stupid plugin. It's useless to me and I already burnt a ton of hours on it. Ideally need to rewrite all the junk into a proper service and do unit testing on each operation. I have no clue what's failing and why

**Comment by hypeJunction** [comment]
That's, as much as I can do. Everything is passing locally, so if it fails, I don't know what else can be done. That code is just mess, I'd be happy to toss it out of core.

**Comment by jdalsem** [comment]
LGTM have you tested logbrowser now works?

**Comment by hypeJunction** [comment]
Seems to be working fine

**Comment by jdalsem** [comment]
be advised.. as we already have a beta out, the commit messages should be a fix instead of a chore... so the change log is correctly populated

**Pull request merged**
