### PR TITLE
checking entered email

### PR DESCRIPTION
**Pull request by raghukul01**
to check if entered email has a @ sign or not

### CODE REVIEW

**Comment by hypeJunction** [comment]
It's unnecessary. Emails validated elsewhere.

**Comment by raghukul01** [comment]
is there any issue that i can resolve. Actually I am a beginner and I have to do a assingment ( commiting to  a repository with many stars).

**Comment by hypeJunction** [comment]
There is an Easy tag in the issues section

**Comment by mrclay** [comment]
Try https://github.com/Elgg/Elgg/issues/5871. Most of the other "easy" issues look not easy or already done.

**Comment by raghukul01** [comment]
thank you sir

**Pull request closed without merging**
