### PR TITLE
docs(js): modernizes the JS docs to emphasize AMD usage

### PR DESCRIPTION
**Pull request by mrclay**
Documents each AMD module available for public use.

### CODE REVIEW

**Comment by hypeJunction** [comment]
LGTM. Maybe it's worth mentioning that core still uses inline scripts to load AMD modules to ensure instantiation on ajax requests

**Comment by juho-jaakkola** [comment]
LGTM

**Comment by mrclay** [comment]
@hypeJunction do devs need to know that? I figure it's better to just tell them the preferred way to do things.

**Comment by mrclay** [comment]
Anyway, we can add that anytime.

**Pull request merged**
