### PR TITLE
feat(plugins): autoload plugin composer autoloader

### LINKED ISSUE #8829: Autoload plugin dependencies
As we are moving to dependency management with composer, plugins can no longer be sure where their dependencies are in `elgg-root/vendor/` or in `elgg-root/mod/elgg-plugin/vendor`. To avoid duplication and confusion, it would be helpful if the core checked if `elgg-root/mod/elgg-plugin/vendor/autoload.php` exists, and required it automatically on plugin boot. That would save the hassle of implementing additional steps for zipped installs.

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #8829

### CODE REVIEW

**Review by hypeJunction — CHANGES_REQUESTED** [review]
Require is more appropriate.  And better to check if file exists than to silence the error,  IMO

**Comment by jdalsem** [comment]
> Require is more appropriate

no objections to changing this, but why is it more appropriate?

**Comment by hypeJunction** [comment]
If you include it you will pollute the variable scopes

**Comment by jdalsem** [comment]
Updated with comments

**Pull request merged**
