### PR TITLE
fix(mail): additional library for SMTP e-mail support

### LINKED ISSUE #13161: require zendframework/zend-servicemanager for smtp mail support
This was forgotten

```
"zendframework/zend-servicemanager": "^3.3.1",
```

### PR DESCRIPTION
**Pull request by jeabakker**
fixes #13161

### CODE REVIEW

**Comment by MarkMicallef** [comment]
Does SMTP work? I cannot get Elgg to send email via my SMTP service provider.

**Comment by jeabakker** [comment]
yes SMTP works. 

It can be a bit tricky to get the correct configuration (ssl/tls, account credentials, port number, etc) FInd more information in the ZendFramework Mail documentation https://docs.zendframework.com/zend-mail/transport/smtp-authentication/

**Comment by MarkMicallef** [comment]
I have spent quite some time on it. The link at the bottom is a screenshot from the settings.php. I am also using this server to send mail for my Mastodon instance and it works fine, but Elgg just will not work. Can you see what I might have wrong here?

https://lh3.googleusercontent.com/vGBa_e9A50Bout0T9zyyTU7VhpjroRrx3xEFrTPTnh_lK5B2fgEjHvKFgJkWGY4inlJEEuK51IrwCl_nq0OvegQ4zHh_4V02Mejl9N3fe0EsPcgXgT7ruj10TF6LmdWdvhlONlI8xZ7RePvlOTznpzWhpkxoEQF3Pk8gaxyiVzwodZMYyWBS_lFApY_VwXb5vxdT--sveYo1q5S9dKwJeHx68-sdgAfIdp6W91-Y4TyDdnOC0biO6QMeXv4pVJ9JTgseIx-A_5VdJp_uiVVGpbKuogs51q4jTEtRhTqNbPaw1_A_pSA7I-I_wz1mNv4NAcI1SN18yLC_Nn69bl7bxcLpw9jlarMbbs-jMx4mlHyLRcxo-aD-ucSki689W_Q6NO36FaFE7Ph21jMvtBEbJ3wVut9tvEDN86w87h0t43qp3gAx5iXqtRJOmweIpBzpXyN0EK68KTmu2DGuyAIXC1mAIMFil7vrGBJ_EpfrJeDTE_R-Tn-XW6dRbJ04Rjrl3tYkSi0Ldzf6He-X7eYVrvj_YUplrB6rqGUMmsf8oLMPtxQ17MiAV_rcEG8EEuJ9vjXntA9XKE3LQKdNvPWj08TkSOHETkIp-JAas-ChAz93CD5Lomr3BfuLOsQ7i-aNAIeKiz6zVfpDKWnPXThXoObNDgzwRzSqE-wNiRcyPrHjzQQgQG69j-sjEWmEFUI=w676-h328-no?authuser=0

**Comment by MarkMicallef** [comment]
Also, may I ask, what is the difference between the name and host fields?

**Comment by MarkMicallef** [comment]
Okay, found the problem - the "name" field requires the from email address. That was very confusing.

**Comment by jeabakker** [comment]
> Also, may I ask, what is the difference between the name and host fields?

I don't know exactly but `name` is probably used for internal administration, maybe it's possible to have multiple configurations?
`host` is the actual host to which the connection is made

**Comment by jeabakker** [comment]
> the "name" field requires the from email address

that's not my experience, i just had a random name in it

**Comment by MarkMicallef** [comment]
Hmmm... nope. Just cannot get it to work. Is there a log somewhere I can look in to see what the problem might be?

**Comment by MarkMicallef** [comment]
Sorry - that was a mistake. I got a test email from a different system and I mistook it for Elgg.

**Pull request merged**
