### PR TITLE
WIP feature(js): Allows sending HTTP errors for elgg/Ajax

### LINKED ISSUE #9767: Plugins using elgg/Ajax can't tell if action is successful
Old API used to sniff for errors and set `status` to `-1` if it found registered errors. Current `elgg/Ajax` implementation strips error messages from the response and expects actions to implement their own status logic hence there is no reliable way of telling if the action has succeeded.

### PR DESCRIPTION
**Pull request by mrclay**
(builds on #9777)

Adds API version option to `elgg/Ajax`. If set to 3, the server behaves a bit differently for these requests:

HTTP error codes can be sent back with `elgg_set_response_code`. If none is set and `register_error()` was called, the response sends a 500.

### CODE REVIEW

**Comment by mrclay** [comment]
Note callers now receive a `data` object and they have to use `data.value` in their code. This was done for two reasons that might not apply anymore:
1. We needed a way to sniff data.error (indicated register_error() usage). We no longer need this.
2. I wanted a general way for hooks to pass metadata to the caller. This metadata could instead be put on the xhr object and be available as `jqXHR.metadata`.
we can stick metadata on the jqXHR object, meaning.

Hence, I can make upgrading client code as simple as using elgg/Ajax3 instead of elgg/Ajax.

**Comment by hypeJunction** [comment]
I am not sure. I was playing with some code earlier today and it felt like it was much simpler. It seems like you are overthinking this. Let me get my version of things together and we can compare notes. For 2.2 let's just somehow preserve error messages for plugins to sniff. This is not critical so I'd rather we keep elgg/Ajax before we make it ok to maintain multiple versions of APIs and have elgg/Ajax8 by 3.0

**Comment by mrclay** [comment]
The source of the server-side complexity is the BC limitation: we cannot start sending back HTTP error codes for requests that generate 200s in 2.x. Sending a new version header with the request is the only way around that I see.

As for elgg/Ajax3, I think I can refactor the changes into elgg/Ajax, but the Q becomes is it BC to start sending the new header automatically in 2.2. That would indeed be nice because no virtually client code would need to be updated.

**Comment by mrclay** [comment]
Tip: When making server changes, run the ajax demo at the console as an integration test: `require(['developers/ajax_demo'])`. It should make 4 requests and finish with an alert.

**Comment by hypeJunction** [comment]
I want to abstract from what we have and focus what we want to have, put together a tested API and then worry about BC. If it's not BC we roll it in 3.0.

**Comment by mrclay** [comment]
Latest change just adds saner error handling to elgg/Ajax, which I think is BC and I'll just send a separate PR for that.

> Let me get my version of things together

Looking forward to it. I really don't want to wait for 3.0 for elgg/Ajax to be usable.

**Comment by hypeJunction** [comment]
> Tip: When making server changes, run the ajax demo at the console as an integration test: require(['developers/ajax_demo']). It should make 4 requests and finish with an alert.

@mrclay I am a bit confused about the error message in the action demo. As far as I understand the error is always appended. What is elgg/Ajax supposed to do?

**Comment by mrclay** [comment]
The demos are really more like integration tests, I should go ahead and write them as such with PASS/FAILs in the console.

I'm not sure exactly what you're asking, but we should probably focus on #9777 first. Until that's settled this is still messy.

**Comment by hypeJunction** [comment]
I just wasn't sure what kind of feedback it is supposed to give me. Action had both success and error messages so I was confused.

**Pull request closed without merging**
