### PR TITLE
chore(schema): no longer create the unused geocode_cache table

### PR DESCRIPTION
**Pull request by jdalsem**
leaving the existing table intact

### CODE REVIEW

**Comment by hypeJunction** [comment]
This should be done after we merge phinx database migrations

**Comment by jdalsem** [comment]
i thought before... saves you the creation of a phinx file

**Comment by hypeJunction** [comment]
it takes 2 seconds to create a phinx file

**Comment by jdalsem** [comment]
i do not get why this requires a phinx file... it removes a table from the creation proces... nothing else. That means if this gets merged in before your PR... You need to create 1 less table... Otherwise this PR is removing that 'initial create table' phinx file

**Comment by hypeJunction** [comment]
phinx exists for versioning control of database migrations. It will be easier to follow that the table has been removed, instead of having to dig through all the commits to see what changes have been made.

**Comment by jdalsem** [comment]
but i do not want to remove the table... only not create it anymore... thats a difference... how does phinx handle that?

**Comment by hypeJunction** [comment]
Why would you want to keep the table? Either remove it completely, or keep it. No need to create discrepancies, IMO

**Comment by mrclay** [comment]
> This should be done after we merge phinx database migrations

Agreed. It's a perfect opportunity for all of us to gain some experience with it.

> it takes 2 seconds to create a phinx file

Do you tell us how in your PR?

**Comment by hypeJunction** [comment]
> Do you tell us how in your PR?

Yes, in the docs

**Comment by jdalsem** [comment]
i will update this PR to remove the table once we have phinx in

**Comment by jdalsem** [comment]
Will be replaced by a new PR

**Pull request closed without merging**
