### PR TITLE
fix(context): added admin context in ajax details plugin view

### PR DESCRIPTION
**Pull request by oseg**

### CODE REVIEW

**Comment by jeabakker** [comment]
I tested this locally but i don't see any difference. Could you maybe add a screenshot from before and after the fix to show what is fixed

**Comment by oseg** [comment]
The problem happens in my case because I use a theme plugin based on bootstrap (with a CSS class strategy different from ELGG).

However I don't want to apply bootstrap CSS strategy in the admin pages and keep them as they are: with ELGG CSS classes.

I then need to render the ELGG menu differently depending on the 'admin' context. To give an example, I overload views/default/navigation/menu/default.php file and I added a test like this:

`if (elgg_in_context('admin') && elgg_is_admin_logged_in())`

to know if I must apply bootstrap or elgg classes.

The point is: everything is working fine except that in the plugin details view which is loaded through ajax, the context stack only contains 'ajax', the 'admin' context is missing.

**Comment by jeabakker** [comment]
But since this is clearly an issue of your theme there is no need to fix anything in core

**Comment by oseg** [comment]
As you wish, but it is a core issue because:
- core provides the object/plugin/details.php view
- core register this view as ajax in _elgg_plugins_init()
- core provides the API `elgg_in_context()`

But calling `elgg_in_context('admin')` in this view or any code called from this view will return FALSE ! A pity for a view displayed in the admin pages !

**Comment by jdalsem** [comment]
there are way more ajax views in the admin context that are missing this context in the stack. These views are not garanteed to be used in an admin context only, so they should not set the context.

**Comment by oseg** [comment]
Ok, it is a security measure, I can understand. But it also means, that the `elgg_in_context('admin')` call is not reliable in ajax context. Hopefully, this use case does not happen often.

**Comment by hypeJunction** [comment]
JS API is not aware of the context, so there is nothing you can do about it. In general I have been advocating for the context to be dropped entirely, because it is unreliable global state that causes more issues than it solves. You can use view_vars hook and push the context for the admin views, but meh. 

To be honest, I don't understand the problem. Why do you want to style ajax views separately, if they are loaded in the admin context, they should be using the admin theme styles, so there is nothing else you need to do. If your theme sniffs the context to do some custom rendering, that is really a bad approach on the side of the theme itself.

**Comment by oseg** [comment]
You are right, instead of sniffing the view and add the good CSS class depending on the context, I can add both CSS classes (elgg & bootstrap). In the init of the plugin, depending on the context, I will load only elgg or bootstrap CSS file (admin elgg css file is loaded by core).

Small erratum: in one of my previous posts, I talked about `views/default/navigation/menu/default.php`, but I meant `views/default/navigation/tabs.php`

**Pull request closed without merging**
