### PR TITLE
chore(core): Add getLanguage function to User.  Fixes #9857

### LINKED ISSUE #9857: ElggUser should have a getLanguage function
this is handy if you want to send notifications in the recipients language. You can not use elgg_get_language for that... also $recipient->language is unreliable, because theoretically that is null.

$user->getLanguage should first check $user->language, then fallback to $site->language

### PR DESCRIPTION
**Pull request by smellems**
#9857

### CODE REVIEW

**Comment by jeabakker** [comment]
could you maybe amend your commit message according to http://learn.elgg.org/en/stable/contribute/code.html#commit-message-format

so include a 'fixes #9857'

**Review by jeabakker — CHANGES_REQUESTED** [review]
commit message changes as described, then LGTM

**Review by jeabakker — APPROVED** [review]

**Comment by smellems** [comment]
Is something wrong?  Travis failed..

**Comment by hypeJunction** [comment]
We have commit message format check in place. See Jerome's comment above.

**Comment by smellems** [comment]
I changed the commit.  I think the change was approved.  I'm wondering because I see the Travis build failed X.  Should I edit the pull request as well?

**Comment by hypeJunction** [comment]
Can you squash the commits?

**Comment by hypeJunction** [comment]
And you don't need Fixes in the first line of the commit message, you should put it in the body. Commit messages can span multiple lines.

**Comment by smellems** [comment]
I think I made it worse..  I removed my merge, but it added some other commits..

**Comment by hypeJunction** [comment]
You need to rebase:

```sh
git remote add upstream https://github.com/Elgg/Elgg
git fetch upstream
git rebase -i upstream/2.x
```

**Comment by hypeJunction** [comment]
It's also a good practice to create branches to work on individual issues.

```
git fetch upstream
git checkout 2.x
git reset --hard upstream/2.x 
git checkout -b my-new-branch
```

This way you branch from the latest 2.x.

**Comment by smellems** [comment]
I followed your steps and sbumitted a new pull request #10257

**Pull request closed without merging**
