### PR TITLE
chore(services): Exposes config service as interface, adds services docs

### PR DESCRIPTION
**Pull request by mrclay**
Follow-up to #8273.

### CODE REVIEW

**Comment by ewinslow** [comment]
Love all the Docs! Interface especially.

Services directory makes a lot of sense too. Makes it easy to know where to look and see what's available.

One thing we're inconsistent about or rather haven't standardized yet is whether to suffix interface names with the word "Interface". My personal preference is not to do that and instead have implementations use a more descriptive name to clarify implementation details.

**Comment by juho-jaakkola** [comment]
Very nice!

**Comment by mrclay** [comment]
So maybe "Config" as interface and rename the class "GlobalConfig"? I'd probably prefer just "IConfig" to make it easy and generally recognizable as an interface.

**Comment by ewinslow** [comment]
Let's put this to a vote in a separate ticket

**Comment by mrclay** [comment]
Altered interface name to `Elgg\Services\Config`

**Pull request merged**
