### PR TITLE
chore(db): no longer use INSERT DELAYED query writing to system_log

### PR DESCRIPTION
**Pull request by jdalsem**
Ref #4993 

This is one of the issues in Elgg preventing a move to InnoDB

### CODE REVIEW

**Comment by mrclay** [comment]
Can you change the commit summary type to `chore(...`?

**Comment by jdalsem** [comment]
i would rather see it being mentioned in the changelog as i think a lot of people make core changes to make Elgg innodb compatible...

**Comment by mrclay** [comment]
Getting Elgg off MyISAM is a great goal, and experienced devs will want to mod core to get those benefits early, but the core framework has to discourage people from doing those things or people will get themselves in trouble and it becomes a problem for support and for the reputation of the platform.

Until Elgg is on InnoDB, if you or someone else wants to maintain a guide to modding Elgg (and are willing to support folks who run into problems) that would be the place to mention this kind of thing. I would read it! Or just comment on the release blog post...

Is that unreasonable?

**Comment by jdalsem** [comment]
updated commit to a chore

**Comment by mrclay** [comment]
LGTM

**Pull request merged**
