### PR TITLE
chore(tests): add simplecache symlink tests

### PR DESCRIPTION
**Pull request by hypeJunction**
Adds test to ensure that simplecache can by symlinked

### CODE REVIEW

**Comment by hypeJunction** [comment]
This adds new `_elgg_symlink_cache()` but I think the trade off of having a test wins over versioning here.

**Comment by iionly** [comment]
I've tried it now from the command line how php handles symlink paths (on my system at least):
```php
<?php

mkdir("./symlink_test_real_dir");
touch("./symlink_test_real_file");

symlink("./symlink_test_real_dir", "./symlink_test_symlink_dir");
symlink("./symlink_test_real_dir", "./symlink_test_symlink_dir2");

symlink("./symlink_test_real_file", "./symlink_test_symlink_file");
symlink("./symlink_test_real_file", "./symlink_test_symlink_file2");

echo("Start of output\n\n");
echo("Symlink on directory with trailing slash: " . readlink("./symlink_test_symlink_dir/") . "\n\n");
echo("Symlink on directory without trailing slash: " . readlink("./symlink_test_symlink_dir2") . "\n\n");
echo("Symlink on file with trailing slash: " . readlink("./symlink_test_symlink_file/") . "\n\n");
echo("Symlink on file without trailing slash: " . readlink("./symlink_test_symlink_file2") . "\n\n");
echo("End of output\n");

unlink("./symlink_test_symlink_dir2");
unlink("./symlink_test_symlink_dir");
unlink("./symlink_test_symlink_file2");
unlink("./symlink_test_symlink_file");


rmdir("./symlink_test_real_dir");
unlink("./symlink_test_real_file");

?>
```
Result:
> Start of output
> 
> PHP Warning:  readlink(): Invalid argument in /home/xxx/symlink_test.php on line 13
> Symlink on directory with trailing slash: 
> 
> Symlink on directory without trailing slash: ./symlink_test_real_dir
> 
> PHP Warning:  readlink(): Not a directory in /home/xxx/symlink_test.php on line 15
> Symlink on file with trailing slash: 
> 
> Symlink on file without trailing slash: ./symlink_test_real_file
> 
> End of output
> 
So, at least in my case readlink() has an issue with trailing slashes in the filepath both for symlinks pointing to files and directories. Though you get a different warning in both cases the readlink() call fails in both (no output).

**Comment by hypeJunction** [comment]
Goes into master now.

**Comment by hypeJunction** [comment]
Resolved the merge conflict. Since it just adds tests which are passing I am merging this in.

**Pull request merged**
