### PR TITLE
WIP feature(hooks): Adds a function to call 3rd party plugin APIs

### LINKED ISSUE #8763: Ease communication/API calls between plugins
To avoid the use of things like `function_exists()`, Elgg devs have to bend over backwards to allow their APIs to be used across plugins, e.g. moving logic into views, or using hooks in awkward ways.

E.g. consider options I considered to make a type/subtype likeable:

``` php
// using hook
elgg_register_plugin_hook_handler('likes:is_likable', 'object:mysubtype', 'Elgg\Values::getTrue');

// direct API
if (function_exists('likes_register_type')) {
    likes_register_type('object', 'mysubtype');
}
```

Here the hook-based version we chose is only an option because the API is so simple. Once the API is more complex, it becomes more awkward to stuff it into hooks & handlers and to document it. Worse, static analysis tools can't reason about the API usage; devs can't jump to the API implementation; and the handler is registered even if it's never used.

Basically I think pushing cross-plugin API calls out of normal functions and into hooks and views is a mistake.

One compromise would be a function like:

``` php
// don't care about result or if called or not
elgg_call('likes_register_type', 'object', 'mysubtype');

// need to use return value
$res = elgg_call(MyPlugin\Invokables\SayHello::class, 'Steve'); // calls __invoke()
if ($res->was_called) {
    echo $res->return; // "Hello, Steve"
}
```

### PR DESCRIPTION
**Pull request by mrclay**
DO NOT MERGE

elgg_call() allows use of many callables whether or not the API is defined. Hooks allow overriding the method to be called and filtering the value returned. The user must check the result object to verify that the method was called.

Fixes #8763

### CODE REVIEW

**Comment by hypeJunction** [comment]
I like it. This could even be used internally within plugins.

**Comment by ewinslow** [comment]
I don't follow the reasoning behind this.

**Comment by mrclay** [comment]
Consider the need to register type/subtype as likeable. To cram this into plugin hooks requires weird thinking and documenting the hook somewhere:

```php
elgg_register_plugin_hook_handler('likes:is_likable', 'object:mysubtype', 'Elgg\Values::getTrue');
```
This allows:
```php
elgg_call('likes_register_type', ['object', 'mysubtype']);
```
...a straightforward imperative solution where `likes_register_type` would be a regular function with PHPDoc.

If the API is more complex, or you need a return value immediately, hooks are even less appealing.

**Comment by mrclay** [comment]
If I wanted to unregister a subtype and there was no `likes_unregister_type` API, I could still register for `elgg_call:method`, check the arguments, and selectively hijack the API call. It's basically the power we have for views, expect in the general function space instead of view space, and not limited to returning strings.

**Comment by mrclay** [comment]
This (and our views system) definitely cuts against the prevailing winds of statically called service methods, but we still have no great plan for allowing plugins to host their own services so other plugins can call them.

**Comment by mrclay** [comment]
Replaced by #8951

**Pull request closed without merging**
