### PR TITLE
fix(views): changed text of the # more comments text in the river

### LINKED ISSUE #5026: In River, display "+N more" link above the comments (Trac #5026)
_Original ticket http://trac.elgg.org/ticket/5026 on 43090748-03-03 by trac user mrclay, assigned to unknown._

Elgg version: 1.8

Being at the bottom makes me think I'm seeing the first 3 comments, but actually it's the last 3.

The label should be something like "+N previous comments"

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #5026

### CODE REVIEW

**Comment by ewinslow** [comment]
Not a chore. Has user facing impact.

**Comment by jdalsem** [comment]
Feature?

**Comment by ewinslow** [comment]
I'd say fix. Previous ux was broken

**Comment by jdalsem** [comment]
updated commit message to a fix

**Comment by ewinslow** [comment]
LGTM once build failure are fixed

**Pull request merged**
