### PR TITLE
chore(core): objects_entity subtable attributes are moved to metadata

### PR DESCRIPTION
**Pull request by jdalsem**
Ref #2675

BREAKING CHANGE:
The objects_entity table no longer exists. Update your queries if
needed.

### CODE REVIEW

**Review by jeabakker — APPROVED** [review]

**Comment by mrclay** [comment]
What happens if an unprivileged user tries to change an object's title/desc? I suppose the action statement setting the (now metadata) value will fail silently due to permissions and the script would continue until the object save fails?

**Comment by jdalsem** [comment]
> What happens if an unprivileged user tries to change an object's title/desc? I suppose the action statement setting the (now metadata) value will fail silently due to permissions and the script would continue until the object save fails?

Metadata write access will never be checked (also see #11211) using __set... so anyone can change any metadata if the entity is accessable. This is currently already the case.

**Comment by hypeJunction** [comment]
@mrclay, I think what we need is a mentality shift. We should forget what attributes used to represent and treat them like any other metadata. There is no reason to expect that every object has a title or a description, they are just metadata naming convention.

**Comment by jdalsem** [comment]
> We should forget what attributes used to represent and treat them like any other metadata.

yep, that is what we are doing now.. no special treatment at this moment for special attributes... will be doing user entities next, but there will be some special stuff for things that are unique in the users_entity table like username

**Comment by mrclay** [comment]
> I think what we need is a mentality shift.

I'm fine with this shift. My worry, again, is how the behavior change will affect existing action code that is unlikely to be touched upgrading a plugin for 3.0. Nothing yet has been put in the upgrade guide warning devs of the new behavior. We still imply title/desc are stored as attributes: http://learn.elgg.org/en/master/design/database.html#elggobject

That said, I'm cool with you all plowing ahead and getting as much done as possible. We can revisit the docs later.

**Comment by jdalsem** [comment]
yeah need to revisit docs to reflect new database design... also need to update schema image... will create issue to do so

**Pull request merged**
