### PR TITLE
Release 2.0.0 rc.1

### PR DESCRIPTION
**Pull request by mrclay**

### CODE REVIEW

**Comment by mrclay** [comment]
Can't figure out why sphinx-intl is failing.

**Comment by mrclay** [comment]
Shall we just ignore this sphinx build failure?

**Comment by juho-jaakkola** [comment]
It seems like the ```--locale-dir``` option has been removed completely from the current version of sphinx-intl. I cannot find any mention of it's removal though.

**Comment by juho-jaakkola** [comment]
Would you be able to test locally the ```sphinx-intl``` command we're using?

**Comment by mrclay** [comment]
Runs without warning locally. I don't know if it does what it's supposed to though.

**Comment by mrclay** [comment]
@Elgg/owners pushing ahead to get 2.0 out the door.

**Comment by ewinslow** [comment]
+1 thank you!

Evan Winslow
http://community.elgg.org/profile/ewinslow

**Pull request merged**
