### PR TITLE
chore(cron): removes cron/run endpoint

### LINKED ISSUE #10803: cron/run is unreliable
i would not rely on cron/run at this moment as the way the cron determines which ts to check/run is wrong. It uses the endtime of the previous run to determine if execution is needed. I would like to see it determined on some modulo time() instead. 

Currently (because of the bug mentioned here: #10797) it works, but if that bug is fixed it will break cron/run.

If a hourly cron finishes at 10:30 (started at 10:00) the next hourly will be 11:30. I expect (based on cron/hourly) that cron/run should kick the hourly cron at 10:00 and the next one at 11:00.

Instead of determining the need to run a specific interval based on the ts in the database it should determine it based on the start ts of the cron.

### PR DESCRIPTION
**Pull request by mrclay**
This reverts #8916 which added the cron/run endpoint. This was never documented and has some problems described in #10803.

Fixes #10803

(I'm open to revisiting if issues can be ironed out and docs are provided)

- [ ] vote on keeping this.

### CODE REVIEW

**Comment by hypeJunction** [comment]
I already have multiple sites using /cron/run

**Review by jeabakker — APPROVED** [review]

**Comment by hypeJunction** [comment]
Please keep it in. Makes cron config so much easier. Neither period is ever precise enough, but at least this one saves the hassle of configuring 10 crontab jobs

**Comment by mrclay** [comment]
Y'all should leave it until you can vote or something. Doesn't affect me currently.

**Comment by beck24** [comment]
I vote for nixing it, I've never used it because of issues I identified with it.  Doesn't hurt me if it stays, but I wouldn't use it or recommend using it for anything.  Therefore my opinion is it shouldn't be there.
Configuring multiple crons is a minor inconvenience well worth the reliability IMO.

**Comment by hypeJunction** [comment]
Let me take a stab at it. I want to add a server side cron runner anyway, because it doesn't make sense hitting public URLs when we should be running cron server side. Might as well start adding some cli tools

**Comment by hypeJunction** [comment]
Here is a nice tested scheduler https://github.com/peppeocchi/php-cron-scheduler/blob/master/README.md

**Comment by jeabakker** [comment]
We never used this, I think there are problem with it keeping the schedule.
So i vote remove it.

The 10 min you spend during the first installation of a site setting up the crons (this is includes learing a new webinterface to setup crons) isn't all that much.

**Comment by hypeJunction** [comment]
Cron needs rework anyway. It should be possible to run Cron jobs without having to curl the public URL

**Comment by jdalsem** [comment]
public url is at least protected in Elgg 3.0

i like the idea of cron/run, but currently it is very flawed, that needs to be fixed. So if we can not fix it for Elgg 3.0 we need to remove it before releasing 3.0

**Comment by hypeJunction** [comment]
I will try to make some time next week to push a cron service

**Comment by jdalsem** [comment]
Replaced by #11463 that fixes cron/run

**Pull request closed without merging**
