### PR TITLE
Adds hook to web services to filter method output

### PR DESCRIPTION
**Pull request by hypeJunction**
Not entirely sure about the hook name.
Also, not sure if we want to wrap the parameters as an element of $params or just pass them as is.

### CODE REVIEW

**Comment by mrclay** [comment]
Add to hooks-list.rst

**Comment by mrclay** [comment]
Otherwise LGTM

**Comment by hypeJunction** [comment]
@mrclay Done

**Comment by mrclay** [comment]
LGMT

**Pull request merged**
