### PR TITLE
feature(js): datepicker will now show month and year selector

### LINKED ISSUE #5936: Display month and year menus in date input
Lets use a UI that has a dropdown for month and year:
http://jqueryui.com/datepicker/#dropdown-month-year

This makes it easy to select dates from a long time ago.

(Some people actually click the "previous" link hundreds of times to get to their birth year. And then they naturally complain about having to do it.)

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #5936
- [ ] Wait until #7852 has been accepted and merged up to 1.x

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
I absolutely want this, but first we need to do something about the Prev/Next links:

datepicker

We can't expect all languages to fit into so small space. One solution could be to go through all the languages in Transifex and change the words into ```«``` and ```»``` characters.

 - I'm not sure what users of different languages would think about this
 - The icon is too small for mobile devices

Might be best to first find out what kind of words/characters languages are currently using and then decide if we can change them all to something simple but practical.

**Comment by jdalsem** [comment]
> but first we need to do something about the Prev/Next links

isn't that for another ticket? As that problem is already the case without the selectors

**Comment by juho-jaakkola** [comment]
The current translations have been made on the assumption that there is certain amount of space available. This commit changes that amount.

**Comment by jdalsem** [comment]
datepicker-width

The difference is a few pixels... the issue with long "next / previous" texts is already the current case, and i would not want to block this change on that issue

**Comment by jdalsem** [comment]
you can always increase the width in your theme

**Comment by jdalsem** [comment]
why not switch to the icons as seen here? http://jqueryui.com/datepicker/#default

**Comment by mrclay** [comment]
How about http://fortawesome.github.io/Font-Awesome/icon/chevron-left/ with fallback text using [this technique](https://github.com/filamentgroup/a-font-garde#critical-icons-with-fallback-text).

**Comment by mrclay** [comment]
Moving to an image (or icon) seems to be the only "safe" way to do this in 1.x

**Comment by jdalsem** [comment]
Lets open a new ticket for that
Op 29 jan. 2015 18:46 schreef "Steve Clay" <notifications@github.com>:

**Comment by jdalsem** [comment]
Dunno, maybe too early for FA (there is another ticket for that) + plz open
a new ticket for the navigation limited space issue
Op 29 jan. 2015 19:02 schreef "Steve Clay" <notifications@github.com>:

**Comment by juho-jaakkola** [comment]
The difference is small in English but it may be huge is some other language. It isn't necessarily possible to shorten the month into three characters like "Jan". So yes, it'll have to be an icon.

Sorry for nitpicking, but I *really* want people to be able to believe that 1.x upgades do not break **anything**. :)

This means that we don't accept PRs that require more PRs to work properly. 1.11 won't be released until 15th or March, so there's really no excuse to hurry this PR in until it's been updated to use icons.

**Comment by iionly** [comment]
The overlay issue is not a new one: https://github.com/Elgg/Elgg/issues/7542

**Comment by ewinslow** [comment]
Agree with Juho

**Pull request closed without merging**
