### PR TITLE
fix(database): Uncallable callback arguments now throw exceptions

### LINKED ISSUE #6937: Elgg_Database::getResults ignores bad callbacks
If $callback is not empty but isn't callable, that seems like a concern worth raising. Instead the function just doesn't call it.

### PR DESCRIPTION
**Pull request by mrclay**
Fixes #6937

### CODE REVIEW

**Comment by Srokap** [comment]
looks ok

**Comment by beck24** [comment]
Looks fine to me

**Comment by hypeJunction** [comment]
Travis error was composer related. Restarted, if passes, I will merge

**Comment by hypeJunction** [comment]
@mrclay Travis complains for PHP 7
  Problem 1
    - This package requires php ~5.4 but your PHP version does not satisfy that requirement.
  Problem 2
    - The requested PHP extension ext-mysql * is missing from your system.

**Comment by mrclay** [comment]
Rebased, maybe it'll fix it

**Pull request merged**
