### PR TITLE
Fix: special char in username & RSS show 

### PR DESCRIPTION
**Pull request by rohit1290**
Fix for https://github.com/Elgg/Elgg/issues/12418, https://github.com/Elgg/Elgg/issues/12390

### CODE REVIEW

**Comment by jeabakker** [comment]
Looking good except for your commit messages. They don't have the correct format. Please look here http://learn.elgg.org/en/stable/contribute/code.html#commit-message-format for the correct format

**Comment by rohit1290** [comment]
@jeabakker Do i need to do something else?

**Comment by jeabakker** [comment]
change
`fix(registration): Not allow , and : in username at registration`
to `fix(account): don't allow , and : in username`

and 
`fix(rss view): Don't show RSS if disabled`
to `fix(rss): prevent RSS output if disabled`

**Comment by rohit1290** [comment]
@jeabakker Why is it showing "All checks have failed"? Have I missed anything?

**Comment by jdalsem** [comment]
Our code style rules are automatically checked. See https://travis-ci.org/Elgg/Elgg/jobs/509457706#L715

There are some spaces at the beginning of the line. Indentation should be tabs only.

**Comment by rohit1290** [comment]
@jdalsem I have fixed the indentation and spacing problem but now it showing a new issue:
Elgg\ActionsServiceUnitTest::testCanRefreshTokens - Failed asserting that two strings are equal.

I know I am asking a lot or question here. Its all because i am willing to contribute more and it's better that I learn all these.

**Comment by jeabakker** [comment]
@rohit1290 this sometimes happens. The action tokens are time based. If the test flips over 1 second during runtime the test will fail.

Nothing you did. I restarted the test and it'll probably succeed

**Comment by jdalsem** [comment]
@rohit1290 next time make sure that you have no styling issues in your commits... it is harder to look at the commit history if there are specific commits to cleanup code that is introduced in a previous commit (in the same PR). You can squash commits to merge them together. Other than that... thanks for the work!

**Comment by rohit1290** [comment]
@jdalsem and @jeabakker is there any way i can run the travis-ci check locally before pushing the changes to github. I have found very limited article on testing but no doc on how to setup phpunit testing environment on local system.

**Comment by jeabakker** [comment]
you should be able to run the unit tests localy. integration test is harder.
`phpunit --testsuite=unit` or `vendor/bin/phpunit --testsuite=unit` or `vendor/phpunit/phpunit/phpunit --testsuite=unit` should do the trick

**Pull request merged**
