### PR TITLE
Ajax comments

### PR DESCRIPTION
**Pull request by jdalsem**
- [x] mention in upgrading

### CODE REVIEW

**Comment by mrclay** [comment]
- What if the user submits comment #11 on a 10 limit page? Or other users' comments bump us to the next page?
- If user is typing and has been on the page awhile we should load new comments periodically.
- Does this implementation keep track of offset?

**Comment by mrclay** [comment]
@hypeJunction can we address the issues I raised without making this too complex? Anything important this is missing?

**Comment by hypeJunction** [comment]
I have spent a few years polishing hypeIntetactions. It's complex.

**Comment by jdalsem** [comment]
> What if the user submits comment #11 on a 10 limit page? Or other users' comments bump us to the next page?
> If user is typing and has been on the page awhile we should load new comments periodically.
> Does this implementation keep track of offset?

all tackled in this PR.. it just reloads complete comment list and resets offset... same as what would have happened without ajax

**Comment by mrclay** [comment]
Currently non-ajax comments forward to the particular offset that displays the comment. Consider the behavior of this PR if you comment from page 2. The displayed comments won't match the URL nor show the user's new content.

A "good enough" solution would be to check the refreshed list for the expected comment ID and redirect to the comment/view handler if not found.

**Comment by jdalsem** [comment]
> he displayed comments won't match the URL

this is true... but not important to me... we could rewrite the URL client side if you want



> nor show the user's new content.

it will always show the new content

Have you tested this PR manually or only thinking out loud.. Just pull it and check how it works

**Comment by mrclay** [comment]
I'll test it this evening.

**Comment by mrclay** [comment]
This indeed works fine. Maybe unrelated question: what is the `'reverse_order_by' => true,` in the page/elements/comments query supposed to do? Since descending time created is the default, why is it needed? And if it isn't, why doesn't it reverse the ordering? Is this a bug?

**Comment by mrclay** [comment]
BTW... this works great because comments are displayed latest first. Are they *supposed* to?

**Comment by jdalsem** [comment]
> what is the 'reverse_order_by' => true, in the page/elements/comments query supposed to do

if you use an `order by` param, this is reversing the order... but this does not seem to work for default order... i do not want it reversed, so i removed it. Creating a new ticket for the bug

> BTW... this works great because comments are displayed latest first. Are they supposed to?

yes

**Pull request merged**
