### PR TITLE
chore(db): Revert 10808: improved performance of disable/delete of an entity

### PR DESCRIPTION
**Pull request by mrclay**
This reverts commit 5adf2ecfcb211cc473beadd06d83dbf7da558f14.

### CODE REVIEW

**Comment by jdalsem** [comment]
don't like the reason why you want to revert this as there is nothing wrong with the change, other than it causing unknown issues in master (reason of these issues may well be caused by something else)

**Comment by jdalsem** [comment]
Look at this: https://github.com/Elgg/Elgg/pull/10835

I cherry picked the entity delete improvements to master and they are not causing any issues...

**Comment by jdalsem** [comment]
i can also explain why the tests fail (or look like a endless loop)... if in the `foreach (owner, container, site)` loop during delete/disable `site_guid` is processed, it is passed to `elgg_get_entities`. But that function does nothing with `site_guid` anymore, thus it will return 'all' entities to be deleted, which will result in deleting so much the tests seem to be running out of time.

So if, in the merge, site_guid is removed from the foreach, this change will not be a problem (as #10835 already proved).

**Comment by hypeJunction** [comment]
We should probably patch ege to return false if site guid is passed and log an error. In any case this was too big of an API churn for 2.3. I'd prefer to revert and deal with it in master

**Comment by jdalsem** [comment]
> We should probably patch ege to return false if site guid is passed and log an error

good idea to add this to master



> In any case this was too big of an API churn for 2.3.

disagree



> I'd prefer to revert and deal with it in master

i do not

**Comment by hypeJunction** [comment]
I'd rather we use a strategy from #10770. We need a failsafe mechanism to avoid infinite loops. If for whatever reason A own B owns C owns A (which is an unlikely case but out API doesn't prevent that from happening), we are in for a treat

**Comment by hypeJunction** [comment]
If you disagree, then add thorough tests in 2.3, I am not confident with our coverage there, so passing tests is not an indication of a plausible solution

**Comment by jdalsem** [comment]
> If for whatever reason A own B owns C owns A (which is an unlikely case but out API doesn't prevent that from happening), we are in for a treat

yes this case exists, but also existed before the change... so nothing new



>I am not confident with our coverage there, so passing tests is not an indication of a plausible solution

This may be, but there current is no REASON to revert. If you have any indication that is needs to be reverted, i can agree, but currently nothing indicates that there is something wrong with the change. We already have various sites using this (without issues).

**Comment by hypeJunction** [comment]
Well, not sure presumption of innocence is how we should treat potential bugs. I'd rather say guilty until proven otherwise. The burden of proof is on you :) I don't think the problem would have existed before the change as the API wouldn't have bumped into the case with a single fetch. Even if it did exist, it's not a reason to ignore it. Anyhow, do what you want, but if you want to keep it, deal with the merge into master.

**Comment by jdalsem** [comment]
We can discus the potential and prevention of infinite loops in #10836.

The PR for merging of the #10808 into master has been made here: #10835

Closing this issue as there is no clear notion of why there should be a revert

**Pull request closed without merging**
