### PR TITLE
fix(ckeditor): updated to full ckeditor package version 4.4.7

### LINKED ISSUE #7574: Elgg Core should come with full ckeditor
Currently the ckeditor plugin provides the basic ckeditor package. I think the plugin should deliver the full package, but only load the basic needs. Allowing other plugins to extend the feature set.

http://ckeditor.com/presets

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #7574

### CODE REVIEW

**Comment by mrclay** [comment]
Does this happen to fix #7771?

**Comment by jdalsem** [comment]
don't think so as the loaded config is still the same...

**Comment by juho-jaakkola** [comment]
This could be used immediately by overriding the config view, right? If so, LGTM.

**Comment by jdalsem** [comment]
> This could be used immediately by overriding the config view, right

yep

**Pull request merged**
