### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by hypeJunction**

### CODE REVIEW

**Comment by jdalsem** [comment]
are you going to hunt the problems down?

**Comment by hypeJunction** [comment]
Eventually. I don't have any more patience for them at the moment.

**Comment by jdalsem** [comment]
ok, then we will go on with wrapping up the beta release

**Comment by hypeJunction** [comment]
Well, there are obviously issues with tests, which should be fixed before anything is released

**Comment by hypeJunction** [comment]
Something is wrong with metadata. Values become arrays instead of being reset. I don't think you want to release that.

**Comment by jdalsem** [comment]
nope

**Comment by jdalsem** [comment]
but i do not see that issue happening on site... yet

**Comment by hypeJunction** [comment]
I have to run now. If you want to look into, go ahead. I have noticed that happening with banned metadata, and group tool tests are failing for that same reason. I won't be back for a few hours, and have other things I was planning to do today.

**Pull request merged**
