### PR TITLE
feat(groups): added join/leave actions to entity menu

### LINKED ISSUE #8872: Remove Leave Group from title menu
Currently, the first thing you see when visiting the group page is "Leave Group" call to action button in a place reserved for things like "Add a blog" and "Join group". Perhaps that would be a more logical place for "Start a discussion", at least on the community site. Curently one has to click around before figuring out how to add a discussion topic.
"Leave group" should probably go into "My status" menu instead.

### PR DESCRIPTION
**Pull request by jdalsem**
The title leave action has been removed from the group profile

Fixes #8872

### CODE REVIEW

**Review by mrclay — CHANGES_REQUESTED** [review]
There's no way to leave the group from its profile.

**Comment by jdalsem** [comment]
> There's no way to leave the group from its profile.

yes, thought about that, but i can live with that... group management (join/leave) can be done from your groups list

**Comment by jdalsem** [comment]
maybe improve the group stats box (where it says that you are a member) with a small link to leave

**Comment by hypeJunction** [comment]
Join group should remain in the title menu, both Join and Leave can be added to status menu, if we haven't removed it yet.

**Comment by jdalsem** [comment]
with this PR join stays in the title menu.... status menu has been removed... only way to leave after this PR is via the entity menu shown in Your Groups listing page

**Comment by jdalsem** [comment]
can we agree on not having the 'leave' action on the group profile available?

**Comment by mrclay** [comment]
I don't think it's acceptable at all to have no way to leave a group from the profile. We seriously need to grab a friend and ask them to try some tasks with Elgg because we know the system too well.

**Comment by hypeJunction** [comment]
Let's just render the entity menu in the sidebar all over the place.

**Comment by mrclay** [comment]
Facebook's solution: The join button turns blue and "joined" to indicate you've joined, and click opens a menu to leave or edit notifications.

**Comment by jdalsem** [comment]
replaced with #11520

**Pull request closed without merging**
