### PR TITLE
Chore(site_notifications): modify loading of js

### PR DESCRIPTION
**Pull request by bruno-infotrad**
Align loading of javascript piece with messages plugin, i.e. use extend_view

### CODE REVIEW

**Comment by ewinslow** [comment]
What bug are you trying to fix? Are you sure this is appropriate for master?

I do not want to promote the practice of extending js/elgg anymore

**Comment by bruno-infotrad** [comment]
What bug are you trying to fix?
In some conditions (which I have not quite yet pinpointed - possibly jquery mobile), I get double-firing for the jquery actions.
Are you sure this is appropriate for master?
Messages is using the exact same method in master
 
Otherwise, both may be good candidates for AMD...But I like consistency - especially when one works for me and the other does not.

**Comment by ewinslow** [comment]
OK, see if you can find out exactly what's going wrong and then we can figure out the right fix.

Just blindly appending to `elgg.js` shouldn't be a fix for anything. Something deeper is happening...

**Comment by bruno-infotrad** [comment]
Very weird. When my plugin is on, using http://borkweb.com/story/discovering-the-events-attached-to-elements-in-jquery, I see <b>the same selectors</b> twice for the events in mod/site_notifications/views/default/js/site_notifications.php. But the only thing I did is unregister the pagehandler and register my own.
Will keep digging.

**Pull request closed without merging**
