### PR TITLE
feat(forms): input/checkbox view support 'switch' styling

### LINKED ISSUE #10606: Create a input/toggle view
I think elgg could use a toggle/switch feature like http://www.w3schools.com/howto/howto_css_switch.asp

Could be used on many form situations where you have yes/no, enable/disable or on/off situations.

Forms like plugin settings, group tools or notifications could benefit from this.

We can create some simple custom css or try to look for a helper library to do this

Examples/Ideas
http://www.bootstrap-switch.org/
http://www.bootstraptoggle.com/
http://naeka.github.io/jquery-switchbutton/
https://proto.io/freebies/onoff/

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #10606 

- [x] decide on color scheme
- [x] add switches to various forms

image

### CODE REVIEW

**Comment by jdalsem** [comment]
On the group form...
image

**Comment by jdalsem** [comment]
or in aalborg colors
image

**Comment by jdalsem** [comment]
By the way... the 'button' toggle is animated... it slides from left to right...
Also clicking on the buttons also serves as clicking on the label/checkbox

**Comment by hypeJunction** [comment]
Looks nice. I prefer less color (aalborg option looks less intrusive)

**Comment by jdalsem** [comment]
Admin page sample
image

**Comment by jdalsem** [comment]
The big green/red conflicts with the blue scheme on the front end... so the blue/grey scheme for the switch is also my favorite... should we keep blue grey on the backend also? Or should we use black/grey switches?

image

**Comment by hypeJunction** [comment]
Grascale for both?

**Comment by iionly** [comment]
Greyscale both for on and off might cause some confusion regarding the current state. The blueish on the frontend looks nice and the green/red for the admin sections wouldn't conflict with the admin theming at the moment (and if I remember correctly somone complained about the admin area lacking colors in some other issue here). With green and red used the state of an option would be obvious (and if necessary some less bright red and green might be enough to appear less intrusive).

**Comment by jdalsem** [comment]
i think i will go for the blue/grey themed buttons. They look good on front and backend. I am using just one css file for both front and back end, so would like to style them the same.

**Comment by jdalsem** [comment]
> is it really (theme) developer friendly to only use one css file

this is how you look at it... currently admin css (and other non frontend css) lacks some features because we 'forgot' to add (new) css rules for all situations. There are various efforts to break down global elgg (frontend) css into separate files to be reusable. That way front/backend css share the same files. Using just one css file for both backend and frontend does not mean you need to have the same styling. This can be done by adding some extra css lines for backend color, but css does more than just colors. It requires a lot of boilerplate code to add the switch feature to both backend and frontend. That is why i choose to use just 1 file.

Going to 3.0 i guess we will see more reuse of css files on both front-end and back end. If there remain a few changes for separating backend front front-end color wise... this can be done by some extra css lines, but i guess that will be done later in the process...

**Comment by jdalsem** [comment]
another approach is by reusing css files and with a css preprocessor replace color-variables with frontend or backend colors...

**Comment by iionly** [comment]
Of course, you can add separate styling for backend. My point is that this seems an additional effort from the theme developer point of view if the intention is mainly to change the look of the frontend only. If the css styling of frontend and backend are separate - even if this means boilerplate code - you change the frontend styling and you're done. If style changes on the frontend result in style changes in the backend, there's additional work necessary - especially if the developer first of all has to add up all the additional code necessary to separate backend from frontend styling. And as you said, colors are not necessarily the only change you might have to fix then.

**Comment by hypeJunction** [comment]
In 8 years working with Elgg, I never touched the admin theme in a project. But for a core team it's an extra hassle to maintain two separate sets of files that are 99% identical.

**Comment by hypeJunction** [comment]
One option is to add admin theme views that just echo front theme views.  It will make it easier to work with the admin theme for devs.

**Pull request merged**
