### PR TITLE
fix(views): prevent php notice if value not is a string in output/text

### PR DESCRIPTION
**Pull request by jdalsem**

### CODE REVIEW

**Comment by hypeJunction** [comment]
Maybe log an error?

**Comment by jdalsem** [comment]
Or just return the value without htmlspecialcharring it?

**Comment by hypeJunction** [comment]
Well, it's a view, so you should return a string of some sort :)
We need a view similar to output/tags, but without the icon

**Comment by mrclay** [comment]
Consider object with `__toString`: it should get output and escaped.

Arrays should cause a warning to let the dev know there's a logic error somewhere.

**Comment by mrclay** [comment]
IIRC PHP 7 is going to throw a catchable Exception on array coerced to string. That would hit us hard due to metadata.

**Comment by juho-jaakkola** [comment]
Error is better than silently failing to output anything.

Best would be to work on preventing wrong types in the first place instead of adding boilerplate to views. Have you investigated what is causing the view to receive non-strings? Could we fix it at the source of the problem?

**Comment by mrclay** [comment]
Consensus seems to be this would mask a problem and we'd prefer leave an error as a sign of an underlying issue.

**Pull request closed without merging**
