### PR TITLE
Release 2.0.0 beta.2

### PR DESCRIPTION
**Pull request by juho-jaakkola**

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
Don't merge yet. Italian translation for embed still has syntax error.

**Comment by juho-jaakkola** [comment]
The translation is fine in Transifex. I wonder why the client doesn't pull it even through the it's newer than the one in git. The ```-f``` flag (force) might help.

**Comment by mrclay** [comment]
You're right about the translations being super noisey. I can think more about this later.

**Comment by juho-jaakkola** [comment]
The syntax error is now fixed: https://github.com/Elgg/Elgg/pull/8969/files#diff-1d2b897696769e841168336e1f0c69b5L6

**Comment by mrclay** [comment]
LGTM

**Pull request merged**
