### PR TITLE
chore(theme): adds file type icons to theme sandbox

### PR DESCRIPTION
**Pull request by hypeJunction**

### CODE REVIEW

**Comment by jdalsem** [comment]
shouldn't this be extended from the file plugin?

**Comment by hypeJunction** [comment]
I wasn't sure what a better would be

**Comment by jdalsem** [comment]
i think to do it in the file plugin, as it only produces output if the file plugin is enabled

**Comment by hypeJunction** [comment]
Moved this to the files plugin

**Comment by juho-jaakkola** [comment]
LGTM

**Pull request merged**
