### PR TITLE
feat(email): more granular API for handling system emails

### PR DESCRIPTION
**Pull request by hypeJunction**
Implements a more granular approach to handling of system emails,
which allows plugins to collaborate on emails without stepping on each
others toes.

BREAKING CHANGE
email,system hook has been replaced by a set of more granular hooks

### CODE REVIEW

**Comment by hypeJunction** [comment]
Please take a look and let me know if there are other use cases that I didn't think about. I will add tests once I get a green light.

**Comment by hypeJunction** [comment]
Added tests. Not sure that what to do with the Transport. We need a way to configure/replace it at runtime with a hook, but it's a service. @mrclay What do you reckon?

**Comment by mrclay** [comment]
> We need a way to configure/replace it at runtime with a hook, but it's a service.

Looks like you have elgg_set_email_transport(). Seems OK to me, right?

**Comment by hypeJunction** [comment]
It works but if plugin were to collect settings e.g. for SMTP transport, it would be a bit heavy to run on each request. But I suppose it's better than nothing

**Comment by mrclay** [comment]
Ah I see. Why not trigger a hook inside the "mailer" factory?

**Comment by hypeJunction** [comment]
Nothing to worry in terms of race conditions? If not, then it's a good option. I wasn't sure how great of an idea it is to call hooks in service factory. We could do the same for image service to replace GD with ImageMagick

**Comment by mrclay** [comment]
> Nothing to worry in terms of race conditions?

Well, yes, but what can you do? We could pretty easily set up ways to configure via settings.php, but obviously that takes us out of plugin API.

**Comment by hypeJunction** [comment]
I did think about it but Zend constructors are a bit of a mess, I'd rather not deal with them in core. A plugin could always save as site config and load cheaply at runtime. I will just add a comment about that and leave as is.

**Comment by hypeJunction** [comment]
Done

**Comment by hypeJunction** [comment]
Resurrected in #11069

**Pull request closed without merging**
