### PR TITLE
chore(i18n): changed text for actiongatekeeper:pluginprevents

### LINKED ISSUE #6959: “A extension has prevented this form from being submitted.”
Found during translation. For consistency, it should probably be **plugin** instead of **extension**.

### PR DESCRIPTION
**Pull request by jdalsem**
Be less technical and do not expose system terminalogy.

fixes #6959

### CODE REVIEW

**Comment by mrclay** [comment]
LGTM

**Comment by ewinslow** [comment]
Stinks that we have this kind of error at all. "Not going to let you do that and not going to explain why not or how you can work around." Agree the text is better. I'd even be ok with dropping the "Sorry".

**Comment by ewinslow** [comment]
But then again people who have done more research than I seem to think saying sorry is a good idea in error messages: http://ux.stackexchange.com/questions/31359/should-error-messages-apologize

**Comment by mrclay** [comment]
I'm going to keep pushing for "Something bad happened. It was probably your fault."

**Pull request merged**
