### PR TITLE
chore(access): refactored get_reabable_access_level into service

### LINKED ISSUE #7364: Duplication of global access arrays with labels
As noted in #7355, mess detector will not like the duplication of global access array.
I think ideally, ```get_readable_access_level()``` should not rely on ```get_write_access_array()```, and the latter should be getting it's strings for ```ACCESS_*``` constants from the former.

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #7364

### CODE REVIEW

**Comment by ewinslow** [comment]
Cool! Can you make it private? Or do you need it to be public?

**Comment by jdalsem** [comment]
Do you mean a real private function? Thats not possible as we use it in `get_readable_access_level`. If you mean to mark it as `@access private`, that seems like overkill as the whole class is marked as private...

**Comment by ewinslow** [comment]
OK sgtm

**Comment by ewinslow** [comment]
Let's wait to pull this in until build failure are fixed

**Comment by jdalsem** [comment]
@hypeJunction does this also look good to you? As you reported the issue that is fixed by this PR

**Comment by hypeJunction** [comment]
Yeah, looks good. Perhaps using isAdmin method on the user entity would be more phpunit friendly.
Could you maybe add a test or a stub?
Another thought is that we have write/read access collection hooks, so we might need to trigger those and not assume that only owners can write into collections.

**Comment by jdalsem** [comment]
> using isAdmin method

will add that


> add a test or a stub

will add that



> we have write/read access collection hooks, so we might need to trigger those

kinda disagree, as this function is used on a lower level most of the time, after the write/read hooks, but i can see a situation where it is not a default acl AND not a saved custom acl, but that the description comes from a custom global ACL, like Logged Out users, so maybe we should trigger a hook specific for readable access level, just before access:missing

**Comment by jdalsem** [comment]
added test stubs and changed `elgg_is_admin_logged_in()` into `_elgg_services()->session->isAdminLoggedIn()`

**Pull request merged**
