### PR TITLE
feat(upgrade): upgrade.php now routes the request

### LINKED ISSUE #11825: logged out going to upgrade.php in walledgarden should forward

### LINKED ISSUE #11888: Get rid of UPGRADING monstrosity
https://github.com/Elgg/Elgg/pull/11883/files#diff-906fae229b5696c49d5e4913d4e662e9R545

### PR DESCRIPTION
**Pull request by hypeJunction**
upgrade.php no longer holds any upgrade logic, instead it routes
the request to a proper controller

Fixes #11888
Fixes #11825

### CODE REVIEW

**Comment by hypeJunction** [comment]
Something is weird in upgrade job. Overflowing state perhaps. Not sure.

**Comment by jdalsem** [comment]
Is this done? Did you do a manual upgrade test?

**Comment by hypeJunction** [comment]
There are some problems with upgrades from 2.0. For some reason plugins entities are not fully loaded during initial boot. I am working now breaking down the upgrade into two steps: first upgrade core without plugins, then run plugin upgrades.

**Comment by jdalsem** [comment]
ok, let me know when you think you are done

**Comment by hypeJunction** [comment]
I am out of ideas. I can't untagnle the mess that the boot process is.

**Pull request closed without merging**
