### PR TITLE
chore(tests): simplifies testing application bootstrap

### PR DESCRIPTION
**Pull request by hypeJunction**
Integration testing config no longer reads settings from
installed application, instead looks for environment variables.

A new instance of Application is now bootstrapped for each test.

Core plugins start.php now returns a Closure, allowing the
application to bootstrap itself multiple times.

Entity tests have been updated to not rely on database state.

### CODE REVIEW

**Comment by hypeJunction** [comment]
@mrclay Could you take a look at the failing simpletest? I am not sure where the plugins_path setting value should be coming from. Shouldn't it resolve itself to Paths:elgg() . 'mod/'?

**Comment by mrclay** [comment]
Curious what this returns during testElggPluginGetID:
 
https://github.com/hypeJunction/Elgg/blob/f51f70f691a7e63df4424786d97312cb0911e37e/engine/classes/ElggPlugin.php#L84

**Comment by hypeJunction** [comment]
I just added `plugins_path` to `tests/elgg-config/simpletest.php` and rebooted the app. Let's see what that does.

**Comment by hypeJunction** [comment]
Everything else is green. Take a fresh look, because I am blind already. And merge it, because it's grown out of hand.

**Comment by hypeJunction** [comment]
I'll work on language, view and action tests, when I have had a chance to destress.

**Comment by hypeJunction** [comment]
It feels as if it's instantiating the plugin as `ElggObject` and not `ElggPlugin`, not sure why

**Comment by mrclay** [comment]
You know how I could xdebug `php elgg-cli simpletest`?

**Comment by hypeJunction** [comment]
Not sure. Don't regular breakpoints work?

**Comment by mrclay** [comment]
testElggPluginIsValid passing, testElggPluginGetID failing. Almost identical, so the issue is either shared state between the tests, or `$test_plugin->getID()` is loading an entity...

**Comment by mrclay** [comment]
CLI debugging: `export XDEBUG_CONFIG="remote_enable=1"` 👍

**Comment by hypeJunction** [comment]
So, the problem was indeed with lacking `plugins_path` in config. The installer wasn't creating plugin entities during installation, and it was all going wrong from there.

**Pull request merged**
