### PR TITLE
Comment and reply permissions overrides

### PR DESCRIPTION
**Pull request by hypeJunction**
feat(discussions): discussion topics now have their own class

feat(comments): entities can now inherit canComment permissions
Extending classes can now explicitly pass default canComment permissions value to the parent class

feat(discussions): adds a shortcut ElggDiscussion::canReply method

### CODE REVIEW

**Comment by hypeJunction** [comment]
Reopening. This needs to go in in some form

**Comment by mrclay** [comment]
Considering the desire to make replies into regular comments, does this make that harder?

**Comment by hypeJunction** [comment]
$entity->disable_comments !== true

**Comment by hypeJunction** [comment]
Oh. I sorry I misunderstood your comment. I thought this was thr PR about disabljng comments.  
Not sure. Depends what the strategy is for makjng replies comments.

**Comment by hypeJunction** [comment]
Replaced by #10465

**Pull request closed without merging**
