### PR TITLE
Merge 1.12 into 2.0

### PR DESCRIPTION
**Pull request by mrclay**
(resolved) Conflicts:
- engine/load.php
- views/default/forms/plugins/settings/save.php

### CODE REVIEW

**Comment by hypeJunction** [comment]
Maybe just remove the form fixes now? It will create a mess afterwards.

**Comment by mrclay** [comment]
@hypeJunction I refactored your recent patch to forms/plugins/settings/save a little for 2.0.

**Comment by hypeJunction** [comment]
I mean #9720

**Comment by mrclay** [comment]
So we should revert #9717, then merge, and fix #9704 in 2.x?

**Comment by hypeJunction** [comment]
That's fine by me. We can use the view_vars hook output you put together

**Pull request closed without merging**
