### PR TITLE
chore(profile): adds views to clean up profile owner block menu

### PR DESCRIPTION
**Pull request by mrclay**
@jdalsem would this interfere with your work?

### CODE REVIEW

**Comment by jdalsem** [comment]
> @jdalsem would this interfere with your work?

no

can't this be done in a special menu? no need for views... that menu ('profile_menu') could pull in the required menu items in a register hook... admin is just a section

**Comment by hypeJunction** [comment]
That would mean you would have to duplicate all of the hover menu logic

**Comment by jdalsem** [comment]
don't think so

**Comment by hypeJunction** [comment]
Plugins woukd have to register all the menu items twice. I am in favor of loosing user hover menu in general. We need to cut down on the number of menus: entity, title, owner block, user hover -way too many places.

**Comment by jdalsem** [comment]
> Plugins woukd have to register all the menu items twice

no need.. an elgg hook will pull them in... just like it is done in the views right now



> I am in favor of loosing user hover menu in general.

maybe menu items can be removed/reduced but we need some vcard hover thingy



> We need to cut down on the number of menus

disagree. they server their need at the moment

**Pull request closed without merging**
