### PR TITLE
chore(uservalidationbyemail): remove registration to undefined function

### PR DESCRIPTION
**Pull request by jeabakker**
An action hook was defined, but the callback function doesn't exist.

fixes: #8838

### CODE REVIEW

**Comment by hypeJunction** [comment]
I don't see the function being remove in upgrading docs.

**Comment by jeabakker** [comment]
> I don't see the function being remove in upgrading docs.

do you mean the registration of the plugin hook? or the callback function which doesn't exist?

**Comment by hypeJunction** [comment]
The function that doesn't exist

**Comment by jeabakker** [comment]
I can't find the function anywhere, i looked in 1.7.15 and it wasn't there, so what should i say?

**Review by hypeJunction — APPROVED** [review]

**Pull request merged**
