### PR TITLE
Translations of Basque and Catalan

### PR DESCRIPTION
**Pull request by hectorespert**
Translations of Basque and Catalan from: [Som Energia Elgg](https://github.com/Som-Energia/plataforma)

### CODE REVIEW

**Comment by iionly** [comment]
Translations for Elgg are maintained at https://www.transifex.com/elgg/public/ and pulled in from there when an Elgg release is made. You can provide your translations there.

**Comment by jdalsem** [comment]
No, not for 1.10, but 1.10 is no longer supported. 1.12 will accept bug fixes, but new translations best should be added to transifex. New Elgg 2.x versions will pull those translations in.

**Comment by iionly** [comment]
@blackleg if Elgg 1.10 would still be supported the translations would have been pulled from Transifex when the next release would have been made. But as it is Elgg 1.12 is the only Elgg 1.x version still supported, so any changes made in the 1.x translations at Transifex will only be added to the (following) 1.12 release.

If you still have to use Elgg 1.10, you would have to maintain any modifications in translations on your own. But there's really no reason to stay on Elgg 1.10. All 3rd party plugins for Elgg 1.10 should work perfectly fine also on Elgg 1.11 and 1.12. So, it's recommended to update to Elgg 1.12. The only blocker for updating an Elgg 1.10 site to 1.12 might be the php version installed on the server (not sure right now) as 1.11 or 1.12 might require php 5.5 at minimum while 1.10 might still work on php 5.4. But if the php version is blocking the upgrade it's better to update the php version (best to 5.6 as older versions are no longer maintained either).

**Comment by blackleg** [comment]
@iionly @jdalsem Thanks

**Pull request closed without merging**
