### PR TITLE
feat(cache): boot cache is now enabled by default

### PR DESCRIPTION
**Pull request by jdalsem**
the small default TTL we had was conflicting with the Invalidation Policy of stash, causing single processes to always invalidate the bootcache..

i trust in bootcache working correctly, so storing it for 1 hour and using default Precomute invalidation strategy

### CODE REVIEW

**Review by jeabakker — APPROVED** [review]

**Comment by jdalsem** [comment]
@hypeJunction do you have an idea why this is happening? https://travis-ci.org/Elgg/Elgg/jobs/333298759#L856

bootcache is now default enabled... and i do not see what is causing 'site' to be missing in config... maybe you have a clue?

**Comment by hypeJunction** [comment]
The whole boot sequence is such a f***** mess. I have no idea. 
It looks like boot cache is created without the site entity, and then loaded from there. Maybe you need to create site entity earlier in the test case.

**Comment by jdalsem** [comment]
i can easily fix this by disabling ttl for the test site, but we might just hide a bug then... will investigate some more

**Comment by hypeJunction** [comment]
I am going to cherry pick this on top of #11665 and see if I can make it work

**Comment by jdalsem** [comment]
give it a try... i will probably be not active until Monday, so you have some time :) good luck

**Comment by hypeJunction** [comment]
Like I don't have a life and have nothing else to do :(

**Comment by hypeJunction** [comment]
Got it working here: #11665

**Pull request closed without merging**
