### PR TITLE
chore(travis): Add GitHub OAuth token to composer on Travis

### LINKED ISSUE #9139: javascript tests are failing
```npm test``` is failing:

```
WARN [watcher]: Pattern "/home/travis/build/Elgg/Elgg/vendor/bower-asset/jquery/dist/jquery.js" does not match any file.
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Linux 0.0.0)]: Connected on socket ZDQwCMgNp-NU49JyYxb0 with id 55184644
PhantomJS 1.9.8 (Linux 0.0.0) ERROR
ReferenceError: Can't find variable: jQuery
at /home/travis/build/Elgg/Elgg/js/lib/elgglib.js:42
```
https://travis-ci.org/Elgg/Elgg/jobs/92918942#L607

### PR DESCRIPTION
**Pull request by mrclay**
Fixes #9139

### CODE REVIEW

**Comment by Srokap** [comment]
How do we know that this variable is set? It's not listed in docs: https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables

I did similar thing for https://github.com/Elgg/starter-project/blob/master/.travis.yml but I keep token in encrypted variable on the bottom of the file (genereated using travis cli).

**Comment by mrclay** [comment]
I just defined here: https://travis-ci.org/Elgg/Elgg/settings. I'll do it the same way you did.

**Comment by mrclay** [comment]
I updated it. I still get this every time, but rest works fine:
```
- Installing fxp/composer-asset-plugin (v1.1.1)
    Downloading: Connecting...    Failed to download fxp/composer-asset-plugin from dist: Could not authenticate against github.com
```

**Comment by Srokap** [comment]
Wow, didn't notice that Travis has this option now.

:+1: from me

**Comment by mrclay** [comment]
Still seems like anyone could make a PR that exposes it, but I removed all roles.

**Pull request merged**
