### PR TITLE
fix(embed): Inserting medium thumbnail size again instead of small on embedding images

### PR DESCRIPTION
**Pull request by iionly**

### CODE REVIEW

**Comment by jdalsem** [comment]
Does this work? Even with caching on? If so this LGTM

**Comment by iionly** [comment]
Tested now with and without caching. Works in both cases.

Caching shouldn't matter here anyway. The image size correction happens before posting. The src url of the image to be embedded is parsed (if the url contains "/serve-file/") and "small" is replaced with "medium". It no difference as such to what has been done before. Only the src url is different now and therefore it stopped working as intended.

**Comment by jdalsem** [comment]
Strange it works for you... the embed url is `serve-icon/397/small`, so the replacement logic should not replace `size=small`... but something else

**Comment by jdalsem** [comment]
this replacement thingy in embed should work differently i think... maybe there should be some hidden html that is used for insertion instead of the listing html....

**Comment by hypeJunction** [comment]
I was thinking about this recently, and was going to implement an ajax based solution. On click, ajax.view with file guid, scan embed/$type/$subtype, embed/$type/default views and embed whatever the response is. A bit slower, but at least easily customizable.

**Comment by iionly** [comment]
Sorry. I had forgotten to commit the change necessary in content.replace() for the replacement to work with the new url scheme as intended. Now it should work.

**Comment by jdalsem** [comment]
Replacing all occurrences of small in the content is too tricky.. It could replace parts of the text that should not be replaced..

**Comment by iionly** [comment]
Content string has the form

> 
<a href="http://site.url/file/view/979/IMAGE-TITLE" class="embed-insert">Test image</a>

IMAGE-TITLE could contain "small" indeed but any other occurance of "small" in the posting won't get replaced.

How about placing "/small"></a>" with "/medium"></a>" then?

**Comment by jdalsem** [comment]
> but any other occurance of "small" in the posting won't get replaced

what if you have a site name... like small.community.com or a class name 'image-small'... even /small is risky... if we want to keep it the way it works for now and do better improvements in a future release, the best we can do now is to use a preg_replace on the url... `/serve-icon/[0-9]*/small`

**Comment by iionly** [comment]
Argh! Formatting of my last posting ended differently than I wanted it.

 I wanted to suggest to search for the end of the string ``` /small"></a> ``` and to replace it with ''' /mediuml"></a> '''. My idea was that by including the closing ``` </a> ``` tag there wouldn't be a problem with falsely replacing any occurance of "small" in site url or image title. Other option would be preg_replace() as you suggested.

**Comment by hypeJunction** [comment]
This approach locks us into never changing filenames.

**Comment by iionly** [comment]
Presently, the comment in the code says
```
/ this is a temporary work-around for #3971
```
Now the url HAS changed and the workaround is no longer working at all. My change is only a fix for the workaround indeed. But at least it would restore the previous functionality until #3971 is fixed with a real solution.

**Comment by jdalsem** [comment]
i think a preg_replace is the safest workaround for now... that way we know at least we are only changing icon urls...

The workaround should go in as a fix on 2.3. A better more stable approach could go in 3.x

**Comment by iionly** [comment]
Updated once more. Hope it's okay at last.

**Comment by jdalsem** [comment]
Lgtm as a workaround.. Need to test it

**Pull request merged**
