### PR TITLE
chore(travis): rebuild matrix

### PR DESCRIPTION
**Pull request by hypeJunction**

### CODE REVIEW

**Comment by hypeJunction** [comment]
Found the problems that resulted in phpdbg memory issues. A bunch of scripts were not closing directory handles after themselves, which results in too many open files. Also further optimized language loading.

**Comment by hypeJunction** [comment]
I have switched to memcached for all builds

**Comment by jeabakker** [comment]
> I have switched to memcached for all builds

so for users of Elgg which don't use memcached (+/-99%) we don't test their setup, hmmm.......

**Comment by hypeJunction** [comment]
The new caching API is chained, so the assumption is that Stash would have tested all their implementations. It shouldn't matter if memcached is enabled or not.

**Comment by jeabakker** [comment]
> so the **assumption** is that Stash would have tested all their implementations. It **shouldn't** matter if memcached is enabled or not.

famous last words.... ;)

**Comment by hypeJunction** [comment]
Feel free to redo to your liking

**Pull request closed without merging**
