### PR TITLE
feat(views): added elgg_parse_emails to output/longtext

### LINKED ISSUE #7052: Output longtext can use a parse_emails
Besides converting urls in text to clickable urls, we could also do that for email adressen converting them to mailto links.

```php
$search  = '/([a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4})/';
$replace = '<a href="mailto:$1">$1</a>';
$new_text = preg_replace($search, $replace, $subtitle);
```

Any objections?

### PR DESCRIPTION
**Pull request by jdalsem**
This makes emails in text clickable mailto links.

Fixes #7052

i am no regex wonder... so this is the best i could steal from someone else...

tests here https://regex101.com/r/lbTbwE/3
- [x] add tests

### CODE REVIEW

**Comment by hypeJunction** [comment]
The best way to know if the stuff you stole works is by adding tests for all possible scenarios :)

**Comment by hypeJunction** [comment]
A simple test  `a.b@example.com` fails. I don't think we can merge this without proper tests.

**Comment by jdalsem** [comment]
was a faulty leftover from my own tests... you can test the regex here https://regex101.com/r/lbTbwE/2

any idea on how to add these kinda test to elgg?

**Comment by hypeJunction** [comment]
Just add a PHPUnit test with a data provider. Add a bunch of cases to the data povider with litetal input and expected output. I think there is something already for url parse you could check

**Comment by jeabakker** [comment]
maybe related ticket #8490

**Comment by hypeJunction** [comment]
Just devised this regex in case tests fail: `<a[^>]+>.+?<\/a>|(^|\s|\!|\.|\?>)+[\w\-\.]+@[^\s\r\n\t<>"\'\)\(]+\.+[0-9a-z]{2,}`

**Comment by jdalsem** [comment]
added tests... and they are passing :)

**Review by jeabakker — APPROVED** [review]

**Comment by jdalsem** [comment]
Replace by #10502

**Pull request closed without merging**
