### PR TITLE
feature(javascript): Adds plugin boot modules

### LINKED ISSUE #7926: Race conditions with AMD and plugin hooks
How does a plugin use AMD and plugin hooks, but guarantee that its hook handlers are registered by the time they're triggered in another module?

### PR DESCRIPTION
**Pull request by mrclay**
Plugins can provide an AMD module `boot/<plugin_id>`, which will be automatically loaded by a new elgg/booted module. Plugin boot modules are the ideal place to register plugin hooks.

The elgg/booted module can be required to make sure all the plugin hooks have been registered.

The final system hooks are now triggered in elgg/booted.

This also adds a boot module for likes, and has elgg/ckeditor/config depend on elgg/booted so plugins will have their handler registered in time for the config hook.

Fixes #7926

### CODE REVIEW

**Comment by mrclay** [comment]
Compared to #8319 this does add an optional "init" function to Plugins which Elgg promises to fire in plugin order. Otherwise the order of boot module loading is unpredictable.

**Comment by mrclay** [comment]
@ewinslow got any better ideas here?

**Comment by ewinslow** [comment]
Not at the moment :(

**Comment by ewinslow** [comment]
Random: do the customization and configuration server side and only ship the final configuration to the client. Avoid the issue altogether... :)

**Comment by mrclay** [comment]
Latest idea: https://github.com/Elgg/Elgg/issues/7926#issuecomment-107433119

**Comment by mrclay** [comment]
Moved to #8993

**Pull request closed without merging**
