### PR TITLE
fix(plugins): pages with no annotation no longer cause fatal errors

### LINKED ISSUE #7793: Fatal error: Call to a member function getURL() on a non-object in mod/pages/views/default/pages/icon.php on line 23
This error occurs in a group. For some reason there is no URL available for a page, but I do not know which page. As a result /pages/all fails as well as trying to get a list of pages in that group and the pages widget in the group.

I suggest checking if getURL() is callable. Something like this ?

<a href="<?php if (is_callable(array($annotation, 'getURL'))) { echo $annotation->getURL(); } ?>">

### PR DESCRIPTION
**Pull request by mrclay**
Fixes #7793

### CODE REVIEW

**Comment by gerard-kanters** [comment]
Thanks mrclay, I can confirmed that it fixes the fatal error. I now can see which page causes the error, but cannot delete or edit that page. Will this be removed by the grabage collector ?

**Comment by juho-jaakkola** [comment]
@gerard-kanters Now that you know which page causes it, do you have any idea what might have caused the missing annotation in the first place?

(BTW, garbage collector will not remove the page.)

**Comment by gerard-kanters** [comment]
No, I do not have a clue why this happened. The page without annotation is in the listings but cannot be opened, edited or deleted. I guess the only way is to remove it manually from the database. I have a script somewhere where I can enter a guid to be deleted.

**Comment by mrclay** [comment]
I'm merging this as is. It's the least we should do.

**Pull request merged**
