### PR TITLE
feature(routing): adds hook to rewrite output URL paths

### PR DESCRIPTION
**Pull request by mrclay**
``elgg_normalize_url()`` (and the JS equivalent) allows rewriting URLs if given as a path.

### CODE REVIEW

**Comment by mrclay** [comment]
@hypeJunction I know you've used `route:rewrite`, any thoughts here?

**Comment by hypeJunction** [comment]
Looks helpful. What's your motivation?

**Comment by mrclay** [comment]
`route:rewrite` seems like half an API and this seems like a simple solution.

**Comment by hypeJunction** [comment]
I would leave out the JS part. The only use case I'd have for this is SEF URL rewrites, which would require a database. Otherwise this invites plugins to temper with URLs, which might just create a mess if not used properly

**Comment by mrclay** [comment]
Let's just let this sit until someone really wants it.

**Comment by jdalsem** [comment]
Closing this to clean up the PR list as i see no activity happening on this at this moment

**Pull request closed without merging**
