### PR TITLE
chore(tests): remove coverage build

### PR DESCRIPTION
**Pull request by hypeJunction**

### CODE REVIEW

**Comment by jdalsem** [comment]
we still need to figure out something to improve codecoverage processing... scrutinizer is taken 1 hour to create the coverage report... we have just 1 concurrent job for scrutinizer... with a lot of PR's and merges a day we wait way to long... but that is off topic

**Comment by hypeJunction** [comment]
Do you care about what scrutinizer has to say? I don't. Let it run in the background and take a year if it needs it.

**Comment by hypeJunction** [comment]
I'd say remove Scrutinizer checks from the git project. Let it do it's job without anyone seeing or waiting for it. Quick turnover of Travis builds is a lot more important to the workflow, then yet another random number of issues found by Scrutinizer.

**Comment by jdalsem** [comment]
we could only do codecoverage on scrutinizer for merges/pushes and not PR's...

**Review by jeabakker — APPROVED** [review]
this needs a better strategy agreed. So for now remove it

**Comment by hypeJunction** [comment]
> we could only do codecoverage on scrutinizer for merges/pushes and not PR's...

Makes sense

**Pull request merged**
