### PR TITLE
perf(output): store site_url as static in elgg_normalize_url

### PR DESCRIPTION
**Pull request by jdalsem**
elgg_normalize_url is called a lot of times. This reduces the callstack

### CODE REVIEW

**Comment by ewinslow** [comment]
Why is reducing the call stack a priority?

**Comment by mrclay** [comment]
I think there are lower-hanging fruit if the goal is to reduce function calls (technically only nested function calls increase the call stack). We should make a ticket for this and get some hard data to work with.

Not a fan of this particular change, especially don't want to go down the path of tons of local static cache vars.

**Comment by jdalsem** [comment]
closing as of bad reception :)

**Comment by mrclay** [comment]
Hey if you're looking for perf wins take a look at this https://github.com/Elgg/Elgg/issues/4346#issuecomment-66770626 It's not trivial though :)

**Pull request closed without merging**
