### PR TITLE
fix(notifications): correctly use elgg_log instead of error_log

### LINKED ISSUE #8039: Invalid use of error_log in _elgg_notify_user()
https://github.com/Elgg/Elgg/blob/master/engine/lib/notification.php#L358

When should we, if, ever, be using error_log() directly?

### PR DESCRIPTION
**Pull request by jeabakker**
the use was probably meant to be elgg_log

fixes #8039

### CODE REVIEW

**Comment by jdalsem** [comment]
should this be a fix? Or is error_log not throwing warnings when not passing an int as the second argument?

**Comment by mrclay** [comment]
Yep, a fix.

**Comment by jeabakker** [comment]
changed

**Comment by ewinslow** [comment]
LGTM

**Comment by jdalsem** [comment]
small typo in commit message correclty = correctly

**Comment by jeabakker** [comment]
fixed typo

**Pull request merged**
