### PR TITLE
feature(discussions): allow plugins to use custom discussion reply ob…

### PR DESCRIPTION
**Pull request by hypeJunction**
…ject class

The plugin no longer needlessly enforces class checks for discussion replies,
thus allowing plugin to register subtype class that does not extend ElggDiscussionReply.

### CODE REVIEW

**Comment by hypeJunction** [comment]
My use case:
I have a plugin that implements a custom `Comment` class that extends `ElggComment`. I want this class to be extended by `DiscussionReply` and I can't extend both `ElggDiscussionReply` and `Comment`.
`ElggDiscussionReply` provides no methods that would require such rigid instance checks.

**Comment by hypeJunction** [comment]
@juho-jaakkola What's your opinion here?

**Comment by mrclay** [comment]
I think both your code and our code should be depending on interfaces instead of demanding a particular ancestor class. What methods do ElggComment and ElggDiscussionReply add? If its purely a behavioral thing that's fine it'll be an interface with no methods.

**Comment by hypeJunction** [comment]
They don't add any new methods. Interface was my first thought, but wasn't sure it is worth the trouble, as we would have to modify all references to `ElggComment` as well

**Comment by mrclay** [comment]
Eh, since no behaviors added, this solution LGTM.

**Comment by hypeJunction** [comment]
Just double checked, there are 3 method in `ElggComment`: `initializeAttributes`, `canComment`, `save`. We could even loose them and use hooks/events instead.

**Comment by juho-jaakkola** [comment]
I'm fine with this approach.

**Comment by beck24** [comment]
+1 Huh, I just dealt with the same issue

**Comment by hypeJunction** [comment]
Pull the trigger

**Pull request merged**
