### PR TITLE
fix(menus): make sure entity passed to user hover menu hook is a user

### PR DESCRIPTION
**Pull request by hypeJunction**
Accidentally passing an entity that is not an ElggUser was resulting in WSOD.

### CODE REVIEW

**Comment by hypeJunction** [comment]
Error seems unrelated : `The command "sphinx-intl --locale-dir=docs/locale/ build" exited with 2.`

**Comment by mrclay** [comment]
Wouldn't it be better to fix this upstream, where the hook is called? That would protect all handlers.

**Comment by hypeJunction** [comment]
It would and it's done in a view. I am working on some menu mish-mash and
it just wsoded my setup.

**Comment by mrclay** [comment]
If you rebase on latest 1.12 the tests should pass.

**Comment by mrclay** [comment]
I refuse to be a slave to Travis. Merging!

**Pull request merged**
