### PR TITLE
fix(views): no results listing output should show if empty item views

### LINKED ISSUE #9917: page/components/list should echo no_results if item views return no content
currently no_results is only echoed if there are no items to list... in some cases (like disabling plugins that provide the view of the activity) listings do not show content, but the no_results will not show up...

i think these situations should show the no_results content

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #9917

### CODE REVIEW

**Comment by mrclay** [comment]
Moving to its own view: 👍 
Not sure about showing it when rendering was empty, which could just mean results couldn't be displayed, not that there were none.

**Comment by hypeJunction** [comment]
@mrclay On the other hand, end user shouldn't worry about the internal failures. If there is nothing to show, better to show no results text, if specified

**Comment by mrclay** [comment]
OK worst case a user sees "No results" under a listing of important content (when really it's a views bug). That's acceptable to me. 

Should a warning be logged or is this an expected occurrence?

**Comment by mrclay** [comment]
LGTM with or without warning.

**Comment by jdalsem** [comment]
Edge case only occurs if 'all' provided items generate no html at all... in that case you see the 'no results'. Before this change you see nothing... with change you see the no results text. Warning is overkill

**Comment by hypeJunction** [comment]
> Edge case only occurs if 'all' provided items generate no html at all... in that case you see the 'no results'. Before this change you see nothing... with change you see the no results text. Warning is overkill

This happens sometimes in river after you disable a plugin...

**Pull request merged**
