### PR TITLE
WIP moving pages to resource views

### PR DESCRIPTION
**Pull request by mrclay**
Do not merge. This is progress toward implementing #7543.

To add to this, make PRs on the `f_7543_resource_views` branch (based on 1.x)

TODOs:
- [ ] Convert plugin page handlers to the same format
- [ ] Don't expose segments array to resources views (use set/get_input instead)
- [ ] Move breadcrumb building into resource views ([see](https://github.com/Elgg/Elgg/pull/7679/files#r21842694))
- [ ] test thoroughly

### CODE REVIEW

**Comment by jdalsem** [comment]
i like the changes but shouldn't this be on master instead of 1.x (i expect a lot of breaking changes)

**Comment by hypeJunction** [comment]
I don't see this breaking anything...

**Comment by jdalsem** [comment]
i see a few renamed/moved views and i also expect some plugins to include pages (although that is not part of our BC policy)

**Comment by mrclay** [comment]
You mean 3rd party plugins `include`-ing PHP files from other other plugins/core?

**Comment by mrclay** [comment]
Which views are no longer BC? We should fix those if possible.

**Comment by jdalsem** [comment]
> You mean 3rd party plugins include-ing PHP files from other other plugins/core?

yep, used to be not so uncommon before route hooks were introduced

> Which views are no longer BC? We should fix those if possible.

every view that is renamed / dropped is a possible BC

**Comment by jdalsem** [comment]
css and view change in custom_index for example

**Comment by mrclay** [comment]
I see. Yes, view renames should be dropped or moved to a PR on master if they're really necessary.

We could leave the page scripts with deprecation notices at the top, but it means keeping both the resource view and the script in sync over a minor release. Another option:

```php in pages/foo.php
if (!isset($__deprecated_pages)) {
    elgg_deprecation_notice(...)
}

echo elgg_view('resources/foo');
```

**Comment by jdalsem** [comment]
also take a look at #3726

**Comment by ewinslow** [comment]
Still would like to make this happen but I agree with Jeroen this is probably best moved to master. It's just safer that way...

**Comment by ewinslow** [comment]
Really want to keep 1.x as stable as possible and this is a pretty dramatic shift in approach.

**Comment by ewinslow** [comment]
Replaced by https://github.com/Elgg/Elgg/pull/8372

**Pull request closed without merging**
