### PR TITLE
Release 2.0.0

### PR DESCRIPTION
**Pull request by juho-jaakkola**

### CODE REVIEW

**Comment by hypeJunction** [comment]
Are we sure there is nothing left in 1.x branch like last time?

**Comment by juho-jaakkola** [comment]
AFAIK we have merged up everything from 1.10. I haven't checked the commit logs manually, though. So not 100% sure, just trusting that the merges have been successful.

**Comment by juho-jaakkola** [comment]
Wait, did you mean 1.x branch specifically?

**Comment by juho-jaakkola** [comment]
I haven't checked 1.x at all. We were already supposed to remove it. No-one hasn't gotten around to do it. I'll check it right away and remove it if no changes are found.

**Comment by juho-jaakkola** [comment]
I tried making a PR and Github gave the message:

> 2.0 is up to date with all commits from 1.x.

I'm removing the 1.x branch now.

**Comment by mrclay** [comment]
Did you load the settings page while logged in as admin? That's our only way to catch syntax errors from Transifex.

**Comment by juho-jaakkola** [comment]
Yes, I did load it.

**Pull request merged**
