### PR TITLE
Allows plugin hooks to alter view $vars

### PR DESCRIPTION
**Pull request by mrclay**
Implements #7736 (PR also alters views docs a bit)

### CODE REVIEW

**Comment by jdalsem** [comment]
me like

**Comment by juho-jaakkola** [comment]
@jdalsem Please wait a bit longer before merging. This PR had existed only for 4 hours and didn't have any reviews from other devs.

**Comment by jdalsem** [comment]
we can revert if you want

**Comment by juho-jaakkola** [comment]
This particular PR is fine. I'm just saying that 4 hours is not enough time for everyone to get the chance to review. (Note also the timezone differences.)

**Comment by jdalsem** [comment]
take a look then and do the merge if it looks good to you

**Comment by beck24** [comment]
LGTM

**Pull request merged**
