### PR TITLE
WIP chore(plugins): remove a ton of plugins from core --DO NOT MERGE

### PR DESCRIPTION
**Pull request by mrclay**
I think we need to bravely cut at least these plugins loose, even if we must do it crudely and break things in the short term. Any plugins we can imagine wanting to improve in an non-BC way outside Elgg's timeframe.

Also:
- activity should go in a plugin (or be able to be disabled)
- friends should go in a plugin (or be able to be disabled)
- htmlawed code should move to core: #10323

Jump to https://github.com/Elgg/Elgg/pull/10322/files#diff-1872c4d455a5b90c92b192a3c128695eL27 for the basic list.

### CODE REVIEW

**Comment by hypeJunction** [comment]
I don't care for invitefriends in core - we can do better.
Let's merge aalborg with core - we end up duplicating all changes.
We could make user validation a core feature with a toggle in settings

**Comment by iionly** [comment]
Embed plugin requires Files plugin (or at least a plugin providing "file_uploading"). It could be a problem with separating the Files plugin but not Embed from core.

**Comment by mrclay** [comment]
Maybe the answer is they all go or the best pieces of them get pulled into core. But pulling plugin views/code into core would introduce MIT license issues. Thoughts? cc @brettp

**Comment by hypeJunction** [comment]
Move everything out , go completely GPL. Use composer to pull in stuff until we know if we continue MIT development or write GPL from scratch.

**Comment by hypeJunction** [comment]
Move everything out , go completely GPL. Use composer to pull in stuff until we know if we continue MIT development or write GPL from scratch.

**Comment by mrclay** [comment]
Short term: I'll try to add "friends" and "activity" plugins. Once we're satisfied with move, we can move to repos.

**Comment by jdalsem** [comment]
+1 for aalborg as core theme

**Comment by jdalsem** [comment]
Just as htmlawed we could also move diagnostic into core... No need to have this as a plugin... I never turn it on or off

**Comment by beck24** [comment]
heh, I *always* turn it off because I never use it :)

**Comment by jdalsem** [comment]
Moving it to core is still zero impact... Makes it 1 less plugin to
maintain

Op 3 okt. 2016 7:54 p.m. schreef "Matt Beckett" <notifications@github.com>:

**Comment by beck24** [comment]
yep, I agree

**Comment by hypeJunction** [comment]
Closing. Will need to do this just before the 3.0 release.

**Pull request closed without merging**
