### PR TITLE
feat(lib): remove support for plugin libraries

### LINKED ISSUE #11176: Kill elgg_load_library()
Remove that bloody idiocy from core. It's 2017 and there is OOP.

### PR DESCRIPTION
**Pull request by hypeJunction**
BREAKING CHANGE
elgg_register_library and elgg_load_library have been removed.
Plugins should require their libraries and runtime and make the
API available to other plugins.

Fixes #11176 

BREAKING CHANGE
Blog plugin no longer users fancy functions to build resource views.
Routing and resource handling has been updated to reflect best practices.

### CODE REVIEW

**Comment by jdalsem** [comment]
can you squah your lint fix commit... it makes no sense for the history of the file as it is created as part of this PR

**Comment by jdalsem** [comment]
conflicts after merging your other PR

**Comment by hypeJunction** [comment]
What's up with Travis today?

**Comment by jdalsem** [comment]
> What's up with Travis today?

they had/have a major problem today... should be normal now

**Pull request merged**
