### PR TITLE
chore(simplecache): support web-font extensions as cachable filetype

### PR DESCRIPTION
**Pull request by jeabakker**
This will make sure FontAwesome can be used again

### CODE REVIEW

**Comment by jdalsem** [comment]
Temporary was not working due to https://github.com/Elgg/Elgg/pull/8538/files#diff-65113f01df66ca9aff309408edfa0111R76

**Comment by ewinslow** [comment]
Yup. Sorry about that. Better to have a whitelist though, methinks.

**Comment by jdalsem** [comment]
Agree, yoda does

**Comment by mrclay** [comment]
LGTM

**Pull request merged**
