### PR TITLE
feature(testing): Support for testing plugins using phpunit

### PR DESCRIPTION
**Pull request by stianlik**
Moved  #7431 to 1.x branch.

Linking to https://github.com/stianlik/elgg-phpunit in the documentation for a complete example.

I think we can make testing more convenient by including utility classes for authentication, database cleanup and such in the future, maybe as a seperate testing repository. This PR should ensure that Elgg contains the absolute minimum to get Elgg booted in PHPUnit tests so that we can access the API in tests.

### CODE REVIEW

**Comment by hypeJunction** [comment]
Not sure mixing engine boot with unit testing is such a good idea. I would be more interested in a solution that @mrclay once built as a plugin that scanned test directories within plugin folders and ran tests

**Comment by stianlik** [comment]
I modified the boot script exclusively to override settings. An alternative could be to create a separete boot for testing by duplicating the code in start.php, however that would require more maintenance in the future. As I see it, there are three alternatives:

1. Create a new start.php used only for unit testing in plugins and publis as a part of Elgg core
2. Modify start.php with a conditonal (this solution)
3. Create a start.php script and include in separate test project

Alternative 1 has the advantage that it is completely seperate from the engine boot, however it requires more maintenance work. Every time the boot script is changed, the unit test boot must be updated. This can easily lead do discrepencies between the test setup and the production environment and make tests fail, or even worse succeed when run from PHPUnit even thoug the code does not function properly in a production environment.

Alternative 2 requires no additonal maintenance and will keep the test configuration very similar to the production environment. It allows developers to use a seperate database for testing, and define extra settings if necessary. The disadvantage is that we introduce a conditional in the start script, however this is well isolated so it should not cause any functional problems, and it is cheap, so there should not be noticable performance-wise.

Alternative 3 makes testing independent of the core repository, however it requires every plugin to include a custom boot script, which, in most cases will be indentical. It inherits the disadvantages from alternative 1. Additionally, a change in the Elgg core boot script may cause the setup to fail so that all plugin developers have to updatede their setup accordingly. 

Did you mean this plugin https://github.com/mrclay/Elgg-ufcoe_unit_control? I don't think we can support PHPUnit wit a custom database this way. The database needs to be configured before Elgg is loaded, unless I'm missing something?

**Comment by hypeJunction** [comment]
I think the direction our tests are headed is to be agnostic from the global state, so the boot script shouldn't even matter. I will let @ewinslow and @mrclay comment on that, as they are the driving force behind unit testing.
I just shared my first impression, but my experience in unit testing is still insignificant.

**Comment by stianlik** [comment]
It is definitively best for unit tests to not be dependent upon global state. However, with the existing code base, it can be quite a chore to test Elgg plugins without access to the system. I think this will be easier in the future, but it should be easy to start testing now.

For now, Elgg provides an API that is dependent on global state. In a system using dependency injection from the start, it is likely that we could mock out repositories and such to keep the unit tests separate. E.g.:

```PHP
// Prepare environment 
$entity = new ElggObject();
$entity->title = 'Test';
$mock = $this->getMockBuilder('Elgg\EntityRepository')->getMock();
$mock->method('getEntity')->willReturn($entity);
$this->di->set('entityRepository', $mock);

// Perform action
$manager = $this->di->get('subscriptionManager');
$result = $manager->doSomethingWithEntity(35);

// Verify results
$this->assertEquals('Test', $result->title);
````

Unfortunately, we depend on global functions like `get_entity()` for this type of functionality. This can be amended by creating wrapper classes, but that requires more effort from plugin authors. Without a wrapper classe, we could test the same feature as follows:

```PHP
// Prepare environment
$entity = new ElggObject();
$entity->title = 'Test';
$entity->save();
$guid = $entity->guid;

// Perform action
$manager = $this->di->get('subscriptionManager');
$result = $manager->doSomethingWithEntity($guid);

// Verify results
$this->assertEquals('Test', $result->title);

// Cleanup
$entity->delete();
```

I think many plugins still rely on global functions, and could take great benefit of a unit testing setup that supports this pattern.

I'm using unit testing loosely here, by using functions such as `get_entity()` it may be closer to integration testing.

/rant

**Comment by hypeJunction** [comment]
Perhaps, at this point it would be better to not introduce any support for plugin testing in core. We would be locking ourselves into supporting a pattern that we may want to change in near future. Dealing with BC would be an issue then. Perhaps we should wait until Elgg services become available for DI, and then decide on a testing pattern we want to support. Just my 5 cents.
In the meantime plugins can just add their own bootstrap and require libs/classes they need from core for testing.

**Comment by mrclay** [comment]
This would basically allow testing the codebase against a different DB/dataroot, but the tester still has to have a separate DB/installation prepared just for testing that plugin; I don't know that many plugin devs are going to find it worth the trouble, and I agree that we don't want to be stuck with supporting a pattern.

I think @Srokap's work on #7939 is moving in a direction that would allow you to do the same thing (boot up Elgg with your own settings).

https://community.elgg.org/plugins/1148929 is my last testing plugin (I've not tried it on more recent versions, but I expect it will still work).

I'd like to move the entire API to a single Elgg\Core object which has services as properties like our current Elgg\Di\ServiceProvider, and inject that into plugin code, rather than having plugins reach out to global resources.

**Comment by stianlik** [comment]
I see how BC could be a problem. It's great that Elgg is moving away from `start.php`. As @mrclay noted, the purpose of this PR is to test the codebase against a different environment. It is mainly a concern for integration testing. It looks like the configuration issues will be resolved much cleaner by #7939.

Closing this PR in favor of an independent composer package to simplify integration testing (todo).

**Comment by stianlik** [comment]
Moved boilerplate code to separate plugin https://github.com/stianlik/elgg-phpunit

**Pull request closed without merging**
