### PR TITLE
perf(nginx): Turn on gzip by default

### PR DESCRIPTION
**Pull request by ewinslow**
Hard to believe the community hasn't been using gzip this whole time???

### CODE REVIEW

**Comment by mrclay** [comment]
I don't know nginx settings to know if this is right, but types look right.

**Comment by ewinslow** [comment]
I basically copy pasted it from html5 boilerplate. They have a lot more
songs turned on but I didn't understand them and didn't want to just
blindly include them.

**Comment by juho-jaakkola** [comment]
I'm not familiar with nginx either.

**Comment by ewinslow** [comment]
@Srokap is our resident nginx guy, I believe

**Comment by ewinslow** [comment]
This is on and working in production on elgg.org, so I'm pretty sure we're squared away here.

**Pull request merged**
