### PR TITLE
fix(core): use single tmp folder to process file uploads instead of a new tmp folder for each entity

### PR DESCRIPTION
**Pull request by iionly**

### CODE REVIEW

**Comment by mrclay** [comment]
What does this actually fix? Put that in the commit summary and how in the commit body.

**Comment by jdalsem** [comment]
This solution does not solve a problem other than reduce the amount of left over empty folders when generating icons. As mentioned elsewhere this problem has been fundamentally changed in Elgg 3.0 where temp files are no longer created inside the dataroot of the site, but in the system temp folder. More explanation in #11445

**Comment by iionly** [comment]
@jdalsem I've responded at https://github.com/Elgg/Elgg/issues/11445 to your latest comment.

Even if this PR here "only" reduces the number of tmp folders (from indefinite many to one!) what's the harm in doing so? With 3.0 doing it differently the problem still remains on 2.3 and I have made this PR for the 2.3 branch.

**Comment by hypeJunction** [comment]
Just do _elgg_rmdir() afterwards. Using a single tmp location won't stick on a site with heavy traffic

**Comment by iionly** [comment]
That's why I have added the entity_guid as prefix to the temp filenames.

**Comment by iionly** [comment]
...and I don't think a _elgg_rmdir() here won't work to remove all empty folders. It could be used to remove the tmp folder. But not for removal of the possibly also empty parent entity_guid folder if the icon files have been moved elsewhere.

**Comment by iionly** [comment]
No it's not. Because the entity_guid folder is currently created in any case just to host the tmp folder within even if the files are saved somewhere else in the end.

I really don't get it. I try to suggest an alternative that would not result in the empty folders and all I get to hear is "why bother about these folders", "elgg 3 does it differently anyway", "just delete the folders on your own if they bother you". If you don't bother the folders getting created for no use, why do you bother about them NOT getting created?

Yeah. Maybe I should focus on other stuff. Maybe first of all and more on my own stuff for a change.

**Comment by hypeJunction** [comment]
Propose a proper solution that passes tests. Your solution won't work, you can't use site folder.
Add an argument to _elgg_rmdir() to walk up the tree and wipe empty parent directories.
Your arguments are too long, and we get lost in your chain of thought.

**Comment by iionly** [comment]
Thanks for some input on the PR code.

But I've no longer any interest. No interest at all. I will work on my own stuff instead from now for the time being.

**Comment by hypeJunction** [comment]
Sure, sometimes it's best. It's hard to get traction on some ideas. I have gotten frustrated a few times, and working on my own thing helped to eventually come up with a solution that satisfies everyone. The best way to get something in is provide a well rested solution that noone has grounds to object to

**Comment by mrclay** [comment]
This solution is perfectly fine by me, I just wanted a more succinct summary in the commit, because it ends up in the changelog. I don't understand all the opposition to this. We all have our itches to scratch.

**Comment by mrclay** [comment]
Let me qualify this: if it doesn't break tests and will work for all sites I have no issue storing temps in /1/tmp. I really should be asleep.

**Comment by jdalsem** [comment]
i have issues against as it makes no sense... temp folders should not happen in dataroot... this will never fix the 'issue' with empty folders. Best option to get rid of empty folders is suggested by @hypeJunction by saying we could have a cron to cleanup after us... just as garbage collector does for the database... but that is considered a feature. Having empty folders around does not feel like a bug to me, thus it can not happen in a bugfix release. Also if you have a current problem, this PR only fixes it for future creations of empty folders and does not cleanup the mess that is already created... if you want to cleanup the empty folders you should have also written a mechanism to remove the current versions.. thus coming back to @hypeJunction s suggestion...

**Comment by hypeJunction** [comment]
What happens if two people start uploading a large me.jpg file?
An argument to keep tmp does is not to have to create them again. Next time someone does something with files the tmp does need to be recreated

**Comment by jdalsem** [comment]
> What happens if two people start uploading a large me.jpg file?

This is also a issue with current storage location

> Next time someone does something with files the tmp does need to be recreated

yeah but that is even better with this PR... as there is only 1 tmp folder for all icons on site

**Comment by hypeJunction** [comment]
Strawman, for 2.3 document a cli command or a cron handler to do the job. In 3.0, add an asynchronous upgrade that wipes the empty folders. Done, move on with your life in peace knowing there are no tmp monsters coming to disturb your sleep at night

**Comment by jdalsem** [comment]
> In 3.0, add an asynchronous upgrade that wipes the empty folders.

if you agree with this you agree also with the fact that this is a problem... i am still unclear why this would be a problem... having empty folders in dataroot was never a problem. i would like to know what i am fixing

**Comment by jdalsem** [comment]
i could also think of something like on `$file->delete()` remove parent folder...

**Comment by hypeJunction** [comment]
The only argument against empty folders I can think of is shared hosts that set an inode limit, but then again, I don't think anyone should be hosting Elgg on a shared server

**Comment by hypeJunction** [comment]
And again people that go looking for trouble in the datadir need to let it go. There is no reason for anyone to be annal about how files are structured unless they are learning how Elgg's file API works. There is a fluent API layer that just like DB API provides an opinionated, but hookable, way of interfacing with the file system. File API was born out of years of experience, so questioning the decisions without any plausible arguments isn't going to sit well with me.

**Pull request closed without merging**
