### PR TITLE
WIP docs(routing): Adds RST docs on routing

### PR DESCRIPTION
**Pull request by mrclay**
This is what I have so far. Input is welcomed. This is for #7337

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
The list of plugin hooks might be better place for the ``route`` hook. This page could just mention it shortly and link to the list page.

**Comment by Srokap** [comment]
@mrclay See my followup on this here: https://github.com/Elgg/Elgg/pull/7749

@juho-jaakkola Actually I think it should better be the opposite. We could have one list of hooks with brief descriptions and rather link to the detailed, possibly quite extended pages from the main list. This way we don't end up with very long and hard to read list of "everything you could possibly know about all existing hooks" ;-)

**Comment by juho-jaakkola** [comment]
Yes, I suggested the same some time ago, but back then we decided not to worry about the length of the list yet.

**Comment by mrclay** [comment]
Moved to #7749

**Pull request closed without merging**
