### PR TITLE
fix(users): trigger missing events for user validation

### LINKED ISSUE #10576: Trigger before/after events for user validation status
https://elgg.org/discussion/view/2568003/how-to-perform-something-after-user-validates-registration-by-email

### PR DESCRIPTION
**Pull request by hypeJunction**
Adds missing after events for changes in user validation status

Fixes #10576

### CODE REVIEW

**Comment by hypeJunction** [comment]
I suppose this is a feature and has to go into master.

@Elgg/core The docs list `validate, user` event, but I couldn't find anywhere. Any idea where it has disappeared or why it's still listed in docs? Some legacy uservalidationbyemail code?

**Comment by mrclay** [comment]
`validate, user` was last used in 1.7 and finally removed in 2.0. Last seen: https://github.com/Elgg/Elgg/blob/1.12.14/engine/lib/deprecated-1.8.php#L2884

**Comment by jdalsem** [comment]
THis is indeed a feature... rebase and update the commit message and it is ready to be merged

**Comment by mrclay** [comment]
Gonna try rebasing via GitHub!

**Comment by mrclay** [comment]
Replaced by #10670

**Pull request closed without merging**
