### PR TITLE
Consistent by line usage

### LINKED ISSUE #5390: User links should always point to the profile
Right now, the links are different depending on the context. In particular they go to a page relevant to the current content type. There seems to be widespread agreement that this is confusing and when users click on someone's name they expect to go to that person's profile.

### PR DESCRIPTION
**Pull request by jdalsem**
Most notable: owner links in by line now always point to user

fixes #5390

### CODE REVIEW

**Comment by hypeJunction** [comment]
I'd prefer we keep category inputs in forms for now. Many plugins are using that to extend unextendable forms. Given it doesn't cost us much to keep them in, we should keep them.

**Comment by jdalsem** [comment]
removed the categories commit from this PR

**Comment by hypeJunction** [comment]
How about adding `byline` parameter alongside `subtitle` to the `object/elements/summary` view. By default, will render the byline, `false` to not render, and a string value to override (in case there is a comment count line or similar).

**Comment by jdalsem** [comment]
Thought about that too... Can do after this is in... Baby steps

**Review by hypeJunction — APPROVED** [review]

**Pull request merged**
