### PR TITLE
chore(core): cleanup leftovers from 1.x upgrade files

### PR DESCRIPTION
**Pull request by jeabakker**
The upgrade files were removed in 2.0, but some things were left
behind.

### CODE REVIEW

**Comment by jeabakker** [comment]
- removed some language keys
- removed registration to non-existing action files

**Review by mrclay — APPROVED** [review]

**Comment by hypeJunction** [comment]
So, basically we just can't go from 1.12 to 2.2 without 2.0 and 2.1? We shouldn't be removing these scripts, instead define dependencies in upgrade scripts.

**Comment by jdalsem** [comment]
This should go in... the damage of not being able to upgrade directly is already done... unless you wish to re-add all the migration scripts back into elgg... We should determine of going to 3.0 we do a similar drop of migration files or not...

**Comment by jeabakker** [comment]
@hypeJunction 

> So, basically we just can't go from 1.12 to 2.2 without 2.0 and 2.1? We shouldn't be removing these scripts, instead define dependencies in upgrade scripts.

I think you can, just not from < 1.12 to 2.2 as you miss all the 1.x upgrade files

**Comment by iionly** [comment]
just to point to https://github.com/Elgg/Elgg/issues/10141.

I guess it's too late to fix any damage done in the past (pre 1.12). But I think it would be really important to be able to leap over intermediate minor releases in future (and if possible even updating directly to whatever 1.12+ release you currently are to the current latest release at any time).

On the one hand it's maybe not too late for 3.0 to consider making upgrading possible not only from 2.3 but also back from 1.12 stil.

One use case I can imagine more often to happen in the future is people upgrading from LTS release to next LTS release, e.g. 1.12 to 2.3. It would really help a lot if they can be sure to do that directly.

**Comment by jdalsem** [comment]
Merging as current Elgg does not need these registrations and translations... #10141 is a better place to discussion migration paths..

**Pull request merged**
