### PR TITLE
feat(js): all core js is now part of the views system

### PR DESCRIPTION
**Pull request by jdalsem**
had to rename languages.js to translations.js because of crazy elgg magic in `ViewsService->canonicalizeViewName` which mapped the view to an already existing core view... wondering if that was also the case with #10758

### CODE REVIEW

**Comment by hypeJunction** [comment]
Not sure how good of an idea that is. I'd personally enjoy messing with core JS via views system, but that's also inviting issues - I'd rather keep that API private so we can refactor more. I'd rather do what @mrclay did in his branch, moving it into `/engine`

**Comment by mrclay** [comment]
Inviting plugins to replace these files seems like trouble.

**Comment by mrclay** [comment]
I think almost everything from my branch is in master. I'll copy it to my repo and delete it.

**Comment by jdalsem** [comment]
> Inviting plugins to replace these files seems like trouble.

we have multiple views that should not be tampered with... but they still exist in the view system... i see no trouble in adding some more as the benefits are they _can_ be overriden. Core js sometimes need to be changed or fixed by plugins.

> I'd rather keep that API private so we can refactor more

I think we can refactor in views also... maybe even easier

**Comment by hypeJunction** [comment]
> I think we can refactor in views also... maybe even easier

Ask me how easy it was to turn bloody js into amd keeping things BC. Honestly, leave them where they are

**Comment by jdalsem** [comment]
> Ask me how easy it was to turn bloody js into amd keeping things BC

i know that it was hard, but i do not see why having this js in the views system makes it more complex

Maybe we should refactor these files now we have the change in 3.0 and make them AMD while we are at it

**Comment by hypeJunction** [comment]
> Maybe we should refactor these files now we have the change in 3.0 and make them AMD while we are at it

Good luck.

**Comment by iionly** [comment]
@jdalsem maybe nothing to do with the issue here but are you testing on Apache with MultiViews option enabled? The problem I had with ckeditor.js was only showing up with MultiViews option enabled.

**Comment by mrclay** [comment]
On second thought, I think we've done well to simplify core by building Elgg with its own APIs. I'd only suggest we put these in the "core" namespace and place a strong warning in the comments.

**Comment by mrclay** [comment]
> Maybe we should ... make them AMD

@jdalsem Check out the attempt in #9385. Some of it was scavenged later. IIRC doing it right introduced timing issues with elgg.echo() and just didn't bring much of a gain for the headache.

**Pull request merged**
