### PR TITLE
Merge 1.12 into 2.0

### PR DESCRIPTION
**Pull request by mrclay**
Also includes a fix for #9139

### CODE REVIEW

**Comment by hypeJunction** [comment]
Did we release RC1 without these?

**Comment by mrclay** [comment]
These are all coming from 1.12, so yes.

**Comment by hypeJunction** [comment]
I was wondering why I was seeing some odd warnings again in rc1. This explains it. :rabbit:

**Comment by mrclay** [comment]
@juho-jaakkola wanna give this solution a look?

**Comment by juho-jaakkola** [comment]
Shouldn't the fix for #9139 go to lowest supported branch?

**Comment by juho-jaakkola** [comment]
Yay! Tests are now passing!

**Comment by mrclay** [comment]
All 1.x have bundled jquery.

**Comment by mrclay** [comment]
Is there anything in 1.x branch to merge first?

**Comment by juho-jaakkola** [comment]
I think we're good to go here.

**Pull request merged**
