### PR TITLE
feature(engine): added a trigger to elgg_view_menu to adjust menu vars

### PR DESCRIPTION
**Pull request by jdalsem**

### CODE REVIEW

**Comment by jdalsem** [comment]
anybody with an opinion @Elgg/owners @Elgg/contributors

**Comment by jeabakker** [comment]
LGTM

**Comment by juho-jaakkola** [comment]
What are the use cases?

Does this allow doing something that can't be done with ```'prepare', "menu:$menu_name"```?

**Comment by hypeJunction** [comment]
I think you can also do this by filtering the parameters of the menu view

**Comment by jdalsem** [comment]
> I think you can also do this by filtering the parameters of the menu view

no, you can't. 

> Does this allow doing something that can't be done with 'prepare', "menu:$menu_name"?

it allows changing sort order for menus. Currently if i want to change the sort order, i reorder all menu items in the prepare hook, but that is really difficult / stupid

**Comment by juho-jaakkola** [comment]
Ability to easily switch menu sorting is indeed a good feature.

**Comment by ewinslow** [comment]
Fine with this since it satisfies a use-case, but the number of plugin hooks here seems like it is going a bit nuts...

**Comment by mrclay** [comment]
I'm OK with this. FYI I use a class that makes reordering much easier in prepare. https://gist.github.com/mrclay/2242916

**Pull request merged**
