### PR TITLE
fix(ckeditor): CKEditor also works with cache symlink in use

### PR DESCRIPTION
**Pull request by iionly**

### CODE REVIEW

**Comment by hypeJunction** [comment]
This doesn't look like a clean or BC solution. I'd rather we figure out what's going wrong here.

**Comment by hypeJunction** [comment]
Also this seems to be a site specific issue. I have creditor working fine with symlinked cache

**Comment by iionly** [comment]
I don't think it is site specific (caused by another plugin) because CKeditor fails to work for me even on a plain master installation with no 3rd party plugins present. And I'm not the only one who has the problem as it had been reported on the community site even before I had noticed it myself as I normally use my Extended Tinymce plugin in place of CKeditor.

It might be a server environment specific issue. In my case it's Apache 2.4 on Linux with the installations in a subdirectory. But even if the problem is caused by some specific server installation details I think it's necessary to figure out what's causing the problem because it's only the CKeditor plugin that fails while every other plugin including 3rd party plugins seem to work perfectly fine. And it might be better to fix CKeditor to work on the usual server setups instead of keeping CKeditor unchanged but asking to make adjustment on ther server instead.

**Comment by mrclay** [comment]
By what mechanism does this fix the problem?

**Comment by iionly** [comment]
I can't tell you by what "mechanism" this PR fixes the issue. 

What I noticed is that there are two AMD modules defined in the CKEditor plugin relevant here:
```
mod/ckeditor/views/default/elgg/ckeditor.js
mod/ckeditor/views/default/elgg/ckeditor/config.js
```
and the ckeditor comes with
```
mod/ckeditor/vendors/ckeditor/ckeditor.js
mod/ckeditor/vendors/ckeditor/config.js
```
Then there are in views.php of the CKEditor plugin the lines that might also be relevant here (for reasons unknown to me though)
```
'ckeditor.js' => __DIR__ . '/vendors/ckeditor/ckeditor.js',
'ckeditor/' => __DIR__ . '/vendors/ckeditor/',
```

So we should have cached
```
elgg/ckeditor.js
elgg/ckeditor/config.js
ckeditor.js
ckeditor/config.js
```

I think in theory there should be no ambiguousness in the urls/paths of the views. Nevertheless, it doesn't work FOR ME at least. And for whatever reason it ONLY fails to work with the cache symlink in use. I can only guess here that for some reason the equal filenames of elgg/ckeditor.js and ckeditor.js on the one hand and the equal relative paths from ckeditor.js to ckeditor/config.js on the other hand result in a race condition (or maybe rather two?) somewhere.

First, with the editor config defined in ```mod/ckeditor/views/default/elgg/ckeditor/config.js``` I got the error

Failed to load resource: http://site.url/cache/1485283855/default/elgg/ckeditor/config.js
the server responded with a status of 404 (Not Found)

That's why I moved ```mod/ckeditor/views/default/elgg/ckeditor/``` to ```mod/ckeditor/views/default/elgg/ckeditor_essentials```.

But then I got a 404 error about elgg/ckeditor.js not found. That's why I renamed ```ckeditor.js``` in views.php to ```elgg_ckeditor.js```.

If you have any explanation what other reason could cause the CKeditor to fail for me (and at least one other guy who reported it on the community site) I would be happy, too. Maybe it is some server issue nothing to do with Elgg. But I can only say that the CKeditor plugin is the only plugin that seems to fail for me with the cache symlink present. Maybe it's an Apache issue (2.4 in my case) or it might be due to having the test installation in a subdirectory (but then I would think it's an Elgg issue nevertheless).

**Comment by iionly** [comment]
Replaced by https://github.com/Elgg/Elgg/pull/10752.

**Pull request closed without merging**
