### PR TITLE
fix(css): break lines only within words if no other acceptable break point in the line (Firefox)

### PR DESCRIPTION
**Pull request by iionly**

### CODE REVIEW

**Comment by jdalsem** [comment]
In chrome there is no difference in behaviour between  'normal' and 'anywhere' https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap.. is there in FF?

**Comment by jdalsem** [comment]
also Edge will cause issues if we are not using break-all

**Comment by iionly** [comment]
@jdalsem with both ```word-wrap: anywhere;``` and ```word-break: break-word;``` available Chrome ignores ```word-wrap```, so there is no change if you alter the value of ```word-wrap```. In case you missed it's ```word-wrap``` I added and not just changed the ```word-break``` fallback.

For ```word-wrap``` the difference between ```normal``` and ```andwhere``` is exactly what helps to solve the problem with long word. ```normal``` only adds a line break at the normal break points (i.e. between words) whereas ```anywhere``` does a line break at any point (e.g. long word or urls) BUT ONLY if there are no other better suited breaking points available. On Firefox the situation is the opposite of the Chrome workflow: the non-standard  ```word-break: break-word;``` gets ignored and ```word-wrap: anywhere;``` results in correct line breaks (without breaking every word on every line break) but still breaks long words to avoid overflow.

I think ```word-wrap: anywhere;``` would be the only necessary property for every browser. With ```word-break: break-word;``` not present Chrome uses  ```word-wrap: anywhere;``` and everything looks the same. I can't test on Edge/IE but I'm quite sure that  ```word-wrap: anywhere;``` is supported because this property comes from Microsoft.

See also
https://caniuse.com/#feat=wordwrap
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap (overflow-wrap is the property in the css standard but word-wrap must be treated in the same way for legacy reasons according to the standard because that's the property name introduces by MS)

**Comment by jdalsem** [comment]
did you check MS Edge?

**Comment by iionly** [comment]
I have no Windows so I can't test Edge.

**Comment by iionly** [comment]
@jdalsem any chance to get this merged? As the line breaks are currently implemented Elgg 3 is kind of not ready to be used with Firefox (at least I would feel ashamed if any user would see words broken in the middle not following any rules).

**Comment by jdalsem** [comment]
Not going to fix this. As of Firefox 67 `word-break: break-word` is supported. https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/67#CSS

**Pull request closed without merging**
