### PR TITLE
adds several reported content features + fix button size in admin CSS

### LINKED ISSUE #5379: Reported content: Button to open the reported page in an iframe within the report

### PR DESCRIPTION
**Pull request by mrclay**
Ajaxifies the reporting form (form page still BC) and delete/archive
actions. Sorts un-archived reports at the top of results. More compact
report display, and clicking reported link opens page in an iframe
in colorbox.

Fixes #5379, #6082, #5380

This doesn't solve all problems but I think would be a step forward. Potential issue: when deleting/archiving, the list doesn't refresh (several ways to do this and couldn't decide on the best within Elgg's limited framework), so, e.g., you could delete 4 out of the widget and it would show none until you refreshed the page.

### CODE REVIEW

**Comment by mrclay** [comment]
Moved the module to elgg/reportedcontent and allowed the "report user" button to popup the form as well.

**Comment by juho-jaakkola** [comment]
LGTM

**Comment by ewinslow** [comment]
Some of the semantics are a bit off. Anchor tags without valid hrefs should generally be converted to buttons. Easy workaround for now is adding a role=button attribute if you don't want to deal with the styling issues. But button tag is still more correct (better keyboard handling).

Inline js is icky. Is there really no way to avoid that? We took a hard stance with other contributors. I think it would be unfair to relax our standards here.

The data-elgg-action attribute is very angular-esque. I like it. Maybe it could be generalized... However, you still have to add that custom code to update the ui so I'm not sure how much it really buys us to encode the information in the custom attribute...

This seems like a major ux improvement so I'm trying not to block it on minor stuff... Just giving my thoughts

**Comment by mrclay** [comment]
I think I can address all this.

**Comment by mrclay** [comment]
I reworked some of the HTML and added a separate fix to normalize the size of button elements.

**Comment by mrclay** [comment]
Since the delete/archive actions don't refresh the listing (would've blown up this PR) I added a simple "Refresh this list" link (to current URL) that appears after one of those actions is taken.

If there are issue with this addition I'll remove it in another PR.

**Pull request merged**
