### PR TITLE
Changes to allow HHVM to pass Travis builds

### PR DESCRIPTION
**Pull request by mrclay**
Replaces #10843

### CODE REVIEW

**Comment by mrclay** [comment]
@hypeJunction 👍 👍

**Comment by hypeJunction** [comment]
Beautiful!

**Review by hypeJunction — APPROVED** [review]

**Comment by jdalsem** [comment]
Nice! Should we disallow travis to fail on HHVM builds now?

**Comment by mrclay** [comment]
I removed the allow fail bit. If it passes, this is ready.

**Pull request merged**
