### PR TITLE
feature(developers): sandbox now generates forms using core views

### PR DESCRIPTION
**Pull request by hypeJunction**
Forms in theme sandbox are now generated using core forms views. This also adds a submit button
in form footer.

### CODE REVIEW

**Comment by mrclay** [comment]
Test failure is unrelated.

**Comment by juho-jaakkola** [comment]
This PR most likely gets replaced by #9086

**Comment by hypeJunction** [comment]
Yes, will make a new one, once merged.

**Comment by jdalsem** [comment]
@hypeJunction i believe you need to update this PR

**Comment by hypeJunction** [comment]
This went in as part of #9086

**Pull request closed without merging**
