### PR TITLE
chore(license): updated license year to 2017

### PR DESCRIPTION
**Pull request by johnnymast**

### CODE REVIEW

**Comment by jdalsem** [comment]
Hmm... better do a PR against the 2.3 branch... as that would make the most sense but changing branches live on github does not work all that good in this case....

Feels like a lot of work for just changing a year :)

**Comment by jdalsem** [comment]
Elgg has multiple branches that are under active support. 2.3 is even not good... it should be the 1.12 branch to be correct... 1.12 will get a patch and the commit will then be upmerged into 2.3

**Comment by johnnymast** [comment]
So what do you want me to do?

**Comment by jdalsem** [comment]
Good question... resubmit the commit/PR against the 2.3 branch

**Comment by jdalsem** [comment]
im sorry... the 1.12 branch... i get confused myself with all these versions :)

**Comment by johnnymast** [comment]
Oke hold on

**Comment by jdalsem** [comment]
Replaced by #10717

**Pull request closed without merging**
